### ISSUE TITLE
macOS client

### ISSUE THREAD

**Issue by francisdb** [syd711/vpin-studio#1]
How hard would it be to build the client for macOS / linux?

**Comment by syd711** [comment]
The major problem would be to ship a JRE for Linux/macOS. The core product is plain Java, so it's already platform independent (at least it should be). I will take a deeper look into it and will give you feedback here.

**Comment by francisdb** [comment]
First issue:

```
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.4.0:exec (full-installer-creation) on project vpin-studio-ui: Command execution failed.: Cannot run program "ISCC.exe" (in directory "/Users/francisdb/workspace/somatik/vpin-studio/vpin-studio-ui"): error=2, No such file or directory -> [Help 1]
```

Looks like `Inno Setup` is win only

**Comment by syd711** [comment]
Yes, but I will deploy the fat jar with the next release too.
Then, you only need JDK 11 installed and can start the jar on the command line.
Still, this is more of a "test balloon" then.

**Comment by francisdb** [comment]
Fat jar would be great!

**Comment by francisdb** [comment]
This has been implemented, just download the client zip, extract and run the `VPin-Studio.sh` file

**Comment by syd711** [comment]
Great!
