### ISSUE TITLE
Changing of highscore cards after finishing table

### ISSUE THREAD

**Issue by GerhardPK** [syd711/vpin-studio#100]
In my opinion, the high score change will not be written back in the event of a new score after the table is finished. But I'm afraid that I haven't set something up correctly or am using it incorrectly. So my background again.
My Vpin works with Win10, I installed the server there and set it to start with Win. I don't work with VPIN Studio on the VPIn.

VPin Studio 2.10.1 is running on my PC under Windows 11. When I run the scan on my PC, the data is updated with my last entries and is ok.
On the Vpin, Popper 1.4.5 usually runs with Vpinball 10.7
alternatively 10.8. Card is displayed on "other2". Call with key O like other. End of the table is stored with the Q key in the Popper controller menu.
I tested with the table "Big Brave". Text file is ok in the script and rom is displayed in VPin. TXT in User folder is correct.
I have no idea where to look. I'll take a look at the others then - nv.ram.....

Take a look - thank you
Gerhard

**Comment by syd711** [comment]
Sorry that his issue seems not be solved yet. I just played the table and everything worked fine.
The last log file files from the previous tickets indicated that I messed something up with the card generator settings, but his issue should have been fixed by now. Could you zip and upload all server logs files again?

**Comment by GerhardPK** [comment]
Hello, first of all thank you for your - as always - quick answer. I just played a new high score again at big brave - it wasn't entered. The log files from Vpin and PC are attached.
Gerhard
PS 95% aller Computerprobleme befinden sich zwischen Stuhl und Tastatur


________________________________
Von: syd711 ***@***.***>
Gesendet: Samstag, 27. Januar 2024 17:24
An: syd711/vpin-studio ***@***.***>
Cc: GerhardPK ***@***.***>; Author ***@***.***>
Betreff: Re: [syd711/vpin-studio] Changing of highscore cards after finishing table (Issue #100)


Sorry that his issue seems not be solved yet. I just played the table and everything worked fine.
The last log file files from the previous tickets indicated that I messed something up with the card generator settings, but his issue should have been fixed by now. Could you zip and upload all server logs files again?

**Comment by syd711** [comment]
Mmmh, it seems that e-mail attachments are not added to github issues.
Please attach them directly to https://github.com/syd711/vpin-studio/issues/100.

**Comment by GerhardPK** [comment]
Hi, 
next try - logs enclosed:

[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/14075504/vpin-studio-server.log)
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/14075505/vpin-studio-ui.log)

**Comment by syd711** [comment]
I think I found the issue. As far as I can see, the "Table Exit" call is never made. The Studio Server should have automatically added this entry to the emulator scripts, but I don't see it anywhere in the logs. Without it, the highscore is only refreshed on table start.

Could you check if these entries are present in your emulator setup:

![image](https://github.com/syd711/vpin-studio/assets/1169826/1d24d90b-8e02-4fa6-a289-dce58dd1f061)

I will provide a better check here for these entries.

**Comment by GerhardPK** [comment]
The entries are included in the launchscript
![emu](https://github.com/syd711/vpin-studio/assets/155166726/d56de455-e7ad-4f73-ac74-2cbe5327a248)
![controller](https://github.com/syd711/vpin-studio/assets/155166726/d7a2a58d-caed-4601-8189-4dddcf35fbe8)

**Comment by syd711** [comment]
Thanks, these helped. Ok, it's either an issue with multiple VPX emus or the exit key binding to "Q". A take a deeper look in both directions.

**Comment by GerhardPK** [comment]
Hello,
I have now removed all emulators and VP versions (it was a good idea when building the VPIN - has
but it's done - FP and VPX is enough).on VPIN studio and server completely uninstalled and
VPIN 2.11.1 server and client installed. At PC 2.11.1 Client installed . Key for EmuExit is now U.
VpX 10.8 is now changed as default launcher. High score cards are now opened with the H button
displayed on the Help screen.
I played Tom&Jerry - one of the few tables that had 0 high scores. all cards generally created.
The card at T+J is shown as 0 before the game begins. Earned a new high score. No change in the
High score card. At the same time, I displayed the table T+J on the PC VPIN Studio. new high scores will be
shown immediately after finishing table. The reset function also worked on the client
the score is set to 0 and the new high score on VPIN  is entered on the client's VPIN studio - table t+j.
The high score card on the VPIN only changes when I exit popper and restart it.
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/14086902/vpin-studio-ui.log)
[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/14086908/vpin-studio-server.log)

**Comment by syd711** [comment]
I see, thanks for the detailed description. I checked the log and detected your highscore on Tom & Jerry and also the card generation:

```
16:51:07.642 [Popper Game Exit Thread] INFO  d.m.v.s.l.PopperStatusChangeListenerImpl - Executing table exit commands for 'Tom & Jerry (Original 2018)'
16:51:07.643 [Thread-94] INFO  d.m.v.s.l.PopperStatusChangeListenerImpl - Starting 6000ms update delay before updating highscores.
16:51:13.644 [Thread-94] INFO  d.m.v.s.l.PopperStatusChangeListenerImpl - Finished 6000ms update delay, updating highscores.
16:51:13.811 [Thread-94] INFO  d.m.v.s.h.HighscoreService - Calculated changed score: [#1 Gerhard Paul Krill   278.480] has beaten [#1 ???   0]
16:51:13.811 [Thread-94] INFO  d.m.v.s.h.HighscoreService - Calculated changed positions for 'tomjerry': [1]
16:51:13.820 [Thread-94] INFO  d.m.v.s.h.HighscoreService - Created highscore version for Tom & Jerry (Original 2018), changed position 1
16:51:13.821 [Thread-94] INFO  d.m.v.s.l.HighscoreChangeListenerImpl - Skipped dynamic subscription updates, because they are not enabled.
16:51:13.821 [Thread-94] INFO  d.m.v.s.l.HighscoreChangeListenerImpl - Sending default notification for: Tom & Jerry (Original 2018)
16:51:13.825 [Thread-94] INFO  d.m.v.s.h.HighscoreService - Saved updated highscore for Tom & Jerry (Original 2018)
16:51:14.275 [Thread-94] INFO  d.m.v.s.u.ImageUtil - Writing C:\vPinball\pinupsystem\POPMedia\Visual Pinball X\GameHelp\Tom and Jerry (Original 2019) v133.png took 93ms.
```

So the only idea I have right now is that you have shown the highscore card before this 6 second timeout was over. In the long run, I always wanted to listen to actual file changes, but right now, this 6 seconds ensures that VPX has enough time to re-write nvram files when a SS table is exited.
