### ISSUE TITLE
Bug in the update process: Calling the server.vbs file without explicitly specifying the windoes scripting host

### ISSUE THREAD

**Issue by M-oster** [syd711/vpin-studio#104]
During the automated update-process, the server is restarted using the the command: server.vbs
This works fine on systems where the VBS extension is linked to the scripting host cscript.exe or wscript.exe (That's the default windows-configuration)
But for security reasons and for easier debugging, there are systems where the default link for vbs is not linked to wsh or linked to another program like notpad++.
In that case the simple call "server.vbs" does not work or calls notepad++ instead.

solution:
explicitly call the vbs file using "wscript server.vbs"
then the update process runs through

**Comment by syd711** [comment]
I see, thank you for pointing that out. I'll take a look.

**Comment by syd711** [comment]
Added for 2.11.1, so the update after that should run smoothly then.
