### ISSUE TITLE
Filter Table List

### ISSUE THREAD

**Issue by jasoncross** [syd711/vpin-studio#107]
It would be really useful when dealing with a large set of tables to be able to filter by various criteria such as status or update available.

**Comment by syd711** [comment]
Good point. On my dev system I only work with around 150, but I'm aware of the problem and with the latest "type ahead" support in the list view, I tried to improve the handling of large lists. However, providing a filter makes totally sense and I will add this.

**Comment by syd711** [comment]
Here are the ideas to filter by:
- missing assets
- version updates
- other specific validation issues
- popper game status
- pup pack
- alt sound
- alt color

**Comment by jasoncross** [comment]
I'd add POV/INI to the list as it can be helpful if trying to determine which tables you've updated view settings on or not.

**Comment by syd711** [comment]
Delivered with 2.13.0.
