### ISSUE TITLE
Importing Tables IN Pinup Popper

### ISSUE THREAD

**Issue by yoshi98bc** [syd711/vpin-studio#108]
So I cannot figure out how to import the ROM into the ROM folder thru VPin studio.  I did figure out the importing of a table and a backglass.  But now I still have to go to the cab and copy the ROM file over.  

I feel a very useful feature of VPIN studio would be remote importing of tables, the backglass, the PupPack and the ROM into the correct folders.  Maybe a simple table import feature that does this on one screen and maybe an option to rename the backglass and table to same name if we so choose during the import.

Thanks

**Comment by syd711** [comment]
I have to agree that now with all the sections in the table overview, the upload actions are spread all over them.
E.g. the ROM upload is available in the "Script" section, which is not that obvious and doesn't need to be table related.

I will consolidate them in a menu together with the existing table uploads.
Regarding the renaming: I'll open a ticket for this to track this feature separated from this.

**Comment by syd711** [comment]
https://github.com/syd711/vpin-studio/issues/109

**Comment by yoshi98bc** [comment]
You the man. Thanks. Will check it out
