### ISSUE TITLE
Pause menu won't activate

### ISSUE THREAD

**Issue by buffdriver** [syd711/vpin-studio#110]
**Describe the bug**
The new pause menu feature fails to activate on my system when pressing the hotkey

**To Reproduce**
1. Start a table in popper
2. Press the pause menu hotkey (F10)
3. Nothing happens

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Chrome installed
 - Version 121.0.6167.86

**Additional context**
Running Popper 1.5 Beta
[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/14076852/vpin-studio-server.log)
[vpin-studio-server.2024-01-27.log](https://github.com/syd711/vpin-studio/files/14076853/vpin-studio-server.2024-01-27.log)

**Comment by syd711** [comment]
To me it looks like the curl call is not inside your emulator script. Can you verify that this entry exists:

![image](https://github.com/syd711/vpin-studio/assets/1169826/788e19b2-308f-44f4-88ae-6da029426cec)

**Comment by buffdriver** [comment]
Yes, it works!

**Comment by Ltek** [comment]
@syd711 I dont see anywhere documented (other than in this bug report) that a CURL command is required in Popper?
not in the UI itself or the Wiki... https://github.com/syd711/vpin-studio/wiki/VPin-Studio-Preferences#overlay--pause-menu-settings

Mine is not working either and it took an hour searching to find this thread. If that CURL command is required please put it in the UI and Wiki to help others. thx!
