### ISSUE TITLE
Wrong Iconcolor

### ISSUE THREAD

**Issue by wlan4you** [syd711/vpin-studio#113]
Wrong Iconcolor
It must be BLUE or not?
Extern LINK !

And VPS.net it doesn't Exist !
Maybe a smal Icon on the Button, see my 
Idea see a new **FEATURE REQUEST**

![Screenshot 2024-01-28 194349](https://github.com/syd711/vpin-studio/assets/60288714/0be97066-6d79-447c-9e5d-e06f9d46488c)

**Comment by syd711** [comment]
Good catch, missed that one.

**Comment by syd711** [comment]
Fixed, comes with next update.
