### ISSUE TITLE
Method to upload Ultra DMD 

### ISSUE THREAD

**Issue by curtiskam** [syd711/vpin-studio#123]
No existing problem

I'd like there to be a way to upload Ultra DMDs for tables that use them.

I'm currently remoting into my pinball PC and using file transfer to upload the Ultra DMDs

**Comment by syd711** [comment]
I have to confess, I haven't used it yet, but the DMD section contains an upload button. There you can upload zip files which contain Ultra and Flex DMDs. Did you try that?

For the next version, I have also moved all upload actions into one menu so that it is more obvious what upload types are available.

**Comment by curtiskam** [comment]
I tried with the last FlexDMD table that I downloaded (Futurama), and it told me the file was invalid. There was an UltraDMD before that that I couldn’t figure out how to upload, but I don’t remember which one.

I’ll try with the next one that pops up and let you know.

**Comment by syd711** [comment]
Ah, I see. I'll review this upload and also test it with the Futurama table.

**Comment by syd711** [comment]
Thank.
The problem was that the upload validator check was case sensitive. E.g. for Futurama the folder is called "flexDMD" instead for "FlexDMD". The issue has been fixed and comes with the next version (> 2.11.1).

**Comment by syd711** [comment]
Re-opened as reminder for myself: there are other tables not using the this lower case syntax, e.g. cyberraceDMD. The check need to be modified so that only the "DMD" suffix is checked.

**Comment by syd711** [comment]
Softened check, so that all "dmd" suffixes are accepted.

**Comment by syd711** [comment]
Sorry, still broken.

**Comment by syd711** [comment]
That have went smoother. Anyway:
The last hotfix did lowercase the target folder and ignored subfolders. Both issues have been fixed.
Tested with cyberrace, futurama and blood machines.
The fix comes with version > 2.11.2
