### ISSUE TITLE
Support real-time monitoring for highscore changes

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#125]
While it is still not possible to monitor every score update of a table (maybe one day, the DMD team is working on that), it makes sense to monitor the highscore files of a started table:

- the text file for EM tables
- the nvram for SS tables
- and the VPReg.stg file

This way, one doesn't have to exit the table and wait 6 seconds.

**Comment by yoshi98bc** [comment]
Is this gonna be an update? Cause this would be great

**Comment by syd711** [comment]
Started today and seems to be less effort than expected. I estimate the release for this next week.

**Comment by yoshi98bc** [comment]
Your thr best. Appreciate the hard work. This app is great. Love remote
updating my cabinet

**Comment by syd711** [comment]
Too bad. I tested this and remembered that I did the same test three years back. The highscores are only written on VPX exit, not even after a game has been finished. So currently, there is no better option than the existing one available here.
