### ISSUE TITLE
Remote Client : Extremely High CPU and Memory usage when idle or minimized

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#126]
**Describe the bug**
I'm running the client remotely When loaded VPS runs on average 25% of the CPU, even when idle and minimized. This is nutty. I run CAD, 3D Printing slicers, and much more and none of them run the CPU at 25%, ever.

Attached screenshot show VPS stats and even 21 Chrome tabs open which have almost zero CPU and very little RAM use. 

**To Reproduce**
install VPS
run VPS
look at Task Manager 'process tab'

**Expected behavior**
nearly no CPU use when idle. 
maybe 10% when maxed?

**Screenshots**

**Desktop**
AMD Ryzen 7 7735HS
8 core 16 thread  3.20 to 4.75Ghz
Radeon Graphics iGPU          
32 GB RAM
Windows 10, all existing updated drivers and windows updates installed

![Capture](https://github.com/syd711/vpin-studio/assets/1626802/3e480042-5e85-4f4e-898f-92ea29593426)

**Comment by syd711** [comment]
As mentioned on Discord, I have described the reason for this here:
https://github.com/syd711/vpin-studio/wiki/Troubleshooting#why-does-the-studio-use-so-much-cpu

There isn't much I can do about this, so I hope you don't mind that I close this ticket.

**Comment by Ltek** [comment]
> As mentioned on Discord, I have described the reason for this here: https://github.com/syd711/vpin-studio/wiki/Troubleshooting#why-does-the-studio-use-so-much-cpu
> 
> There isn't much I can do about this, so I hope you don't mind that I close this ticket.

There are several ways to do it. Its been a long time (25 yrs) since I've coded so I'm not up on the best/most-modern ways but back then we'd use things like stopping processes (network activity, media streaming/playing, etc) based on the state of the application window.  My understanding is that current methods listen and for events that the OS will send to your application based on actions... window minimized, window maximized, window moved, etc

a quick search turned up...

https://stackoverflow.com/questions/4966194/how-could-i-detect-when-my-application-is-minimized

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-isiconic

https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowplacement?redirectedfrom=MSDN

**Comment by syd711** [comment]
You are right. My answer was a bit sloppy. Sorry for that. I've seen "high CPU usage" and thought, "ah, yes, I know".
Of course I can detect these states and will improve the CPU usage in these situation.

**Comment by Ltek** [comment]
thank you for being awesome. I'm one of 'those guys' ... my 30 year career I work with developers almost daily, I have not coded anything vb script, python, a little SQL, etc in 20yrs... and love when I meet a developer like yourself who builds great stuff and appreciates user suggestions. You app is fantastic... This could be a very nice replacement for Popper.

**Comment by syd711** [comment]
Thank you! Your words are indeed much appreciated and this type of feedback is the reason that keeps me going. I really like to get all the feedback from the community and the ideas people come up with. I guess 90% of the feature and changes released in the last few month were community driven and its fun to shape these stuff together. Although the feedback quadrupled the last two weeks I hope keep it this way.

**Comment by syd711** [comment]
Fixed with 2.12.0
