### ISSUE TITLE
[Feature Request] Table Validation Improvement Suggestions

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#127]
Table Validation is very nice and I have some ideas that will make it easier and more intuitive. 
1. 'Tables' section -> VPX tables tab... add columns for each standard popper media type (loading video, FullDMD video, help card, etc)

2. Create a 'validation template' separate for each table.  Validation template remembers each item status for that specific table. 

3.  Additional color coding and functions in 'Tables' section; as described below...

Table Validation Workflow idea (draft)...

1. All tables have red (!) if table validation is new and has never been dismissed
... Red (!) only ever shows if the table does not have a validation template in VPS

2. When a table validation is dismissed, the template for that table is created and used going forward.

5. When table validation refreshes:
... if table items have changed Status Column shows yellow !
... if table items have changed, each item needing attention has yellow ! in its column
... table items that are good, without any changes keep the white check (like it does today)
... if table validation shows good, no needs/changes; the green icon shows in status column (like it does today)

User Modifiable Table Template using the on-screen grid...
Say a user has a table that is validated but they want to change the existing/current B2S, POV, FullDMD video, etc... those items exist and have a white check in that column. Let the user right click the white check mark, and change the icon color to blue. This indicates that the item exists currently, but the user wants to change it.  This then changes the table validation status to 'blue' in the status column.

**Comment by syd711** [comment]
Good point. The plain red felt always a bit harsh to me and I have to agree that there current "discard" option should provide more flexibility. I'll take a closer look here once the current urgent bugs are fixed.

**Comment by syd711** [comment]
Released with 2.18.0.

I know the new solution is not exactly what you described here, but let's see how it is picked up. Imho for a first step it is less complicate and easier to understand.

I'll close the ticket for now.
