### ISSUE TITLE
not correctly finding tables or media when tables are in seperate folder

### ISSUE THREAD

**Issue by H3RBSKI** [syd711/vpin-studio#129]
When tables are saved in seprate folders Vpin studio will not see the tables (even though shows the folders in the drop down) unless you have "Visual pinball" infront of the folder name in popper emulator config.
When doing this it does show the tables, however it is unable to find OR download any media for the tables in these folders. 

Any tables in the default "Tables" folder work as they should. It appears to only effect tables outside of this folder
![image](https://github.com/syd711/vpin-studio/assets/121908307/9206a83b-26fc-46dd-a4b6-bdbb67b4ff8e)

![image](https://github.com/syd711/vpin-studio/assets/121908307/94bf6e5f-65bd-4832-aadf-e365348a5106)

![image](https://github.com/syd711/vpin-studio/assets/121908307/ee64e7b4-9e00-4271-b5c2-6099d65b683c)

![image](https://github.com/syd711/vpin-studio/assets/121908307/050868b2-cb61-407d-b27d-d3111d1ea8a2)

![image](https://github.com/syd711/vpin-studio/assets/121908307/74e7e5c7-6867-46d9-86f6-ca85bc51bd5f)

Running latest version of the app as of 30/1/24

**Comment by syd711** [comment]
Thanks for reporting this! I negleted the multi-VPX-emulator since I don't use it myself, but of course, this will be fixed.

**Comment by syd711** [comment]
Issue has been and will be part of version > 2.11.1

The emulator lookup now also checks the file suffix ("vpx" or "VPX") to see if the emulator is a VPX emulator.
