### ISSUE TITLE
Highscores Check List (List of tables that need to be revisited)

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#131]
blood machines => highscores are only supported through iscored (I got no additional feedback from the developers here)
cyber race => highscoress likely to come with the next version
stern Dracula =>  highscore is not supported by PinemHI
Beavis and Butthead Pinball Stupidity (bnbps) => ok
ghost busters (spa version)
Mickey mouse steamboat Willie => It seems that this table too writes no highscores.
SpongeBob bikini bottom => Set highscore filename to "spongebob_hiscores.txt"
Star God => highscore is not supported by PinemHI
Star wars data east => highscore is not supported by PinemHI
Star wars episode 1 => highscore is not supported by PinemHI
Beavis and Butthead Pinballed => highscore is not supported by PinemHI
Wizard of Oz (WoZ) => (Original 2018) that one worked ootb for me
**Aloha => The table uses a score format not yet supported. I will add it.**

**Comment by Ltek** [comment]
I play the 3 below regularly, LMK when you need them tested

blood machines
cyber race
Star wars data east

**Comment by buffdriver** [comment]
Also:
Beavis and Butthead Pinballed
Wizard of Oz (WoZ)

**Comment by syd711** [comment]
I will try to setup a database for this, so that I these type of settings will be resolved correctly for all tables.
Here are some updates so far:
- Star Wars Data East: the ROM is not supported by the software pinemhi (http://www.pinemhi.com/) which I rely on.
- Sponge Bob: Enter "spongebob_hiscores" as "Alt. ROM Name" in the scripts section, scan the score afterwards.

to be continued...

**Comment by syd711** [comment]
Beavis and Butthead Pinballed:
- make sure you have achieved one highscore
- make sure the ROM name is set to "bnbps"

**Comment by buffdriver** [comment]
There are 2 Beavis and Butthead tables:
Beavis and Butthead Pinball Stupidity (bnbps)
Beavis and Butthead Pinballed (beav_butt) which is based on Class of 1812; however, it uses a developer supplied rom and beav_but.nv

**Comment by syd711** [comment]
Cyber Race and Blood Machines: There isn't any highscore file written for these table. Only scorebit integrations are availble.
I wasn't aware of these kind of tables before. Kind'a sad, because this way I see no way to support these right now.

**Comment by syd711** [comment]
Cyber Race: I talked to the developer: he is going to support highscore files in on of the next version.

**Comment by rubadub-github** [comment]
Aloha seems to not quite work.

![image](https://github.com/syd711/vpin-studio/assets/68559237/874d618d-69ad-4939-9553-467c7219e183)

**Comment by GerhardPK** [comment]
[SpaceMission_76VPX.txt](https://github.com/syd711/vpin-studio/files/14673054/SpaceMission_76VPX.txt)
Vpin Postit
1 GKS 90300
2 GKS 81450
3 AAA 75000
4 ZZZ 70000
5 XXX 60000
Card
1 70000 0
2 60000 1000
3 GKS 90300
4 GKS 81450
5 AAA 75000

**Comment by syd711** [comment]
Thanks for reporting

**Comment by syd711** [comment]
Support for SpaceMisssion has been added with 2.15.0
I close this ticket for now. For nvram based games, the table data dialog should provide the information if a score is supported or not.

For VPReg.stg tables and text file based highscores: **Please** write a separate ticket. I can extend this list of supported tables this way. But it's easiert to track missing tables using separate tickets.
