### ISSUE TITLE
[Feature Request] High Score Card - blank transparent background

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#133]
I place the High Score card on a 10" 16x9 DMD.  I love these cards but really want to use the backgrounds I've set in Popper.
Some tables I have a video playing or an Info Card (PNG) and would like to use that as the background.

Hoping you can make the High Score Cards be transparent overlays like PuP Packs have. 

thx for considering

**Comment by Ltek** [comment]
> Uhh, that would look fancy. Sure, I'll take a look.

ho-nuda-level ;-)

Think of how amazing it will look with white high score text in front of this FullDMD video I use during loading...
https://vpuniverse.com/files/file/18067-cyberrace-dmd-and-attract-video-with-music/

**Comment by syd711** [comment]
I played around with the transparent cards today.
While generating these is not a problem, transparent PNG will have a white background on videos.
I generated all my cards and tried it: in combination with the Popper video, the transparency gets lost.

**Comment by Ltek** [comment]
> I played around with the transparent cards today. While generating these is not a problem, transparent PNG will have a white background on videos. I generated all my cards and tried it: in combination with the Popper video, the transparency gets lost.

Transparent PNG's displaying on videos is used in probably 95% of all PuP Packs (often in folders PuPAlpha, PuPOverlay, etc). 

If you are creating the PNG with an alpha channel set to the background color (usually black) it should work fine. Most desktop apps has check box for 'save transparency' but since you are using command line, it likely a flag for that. Not sure what app you are using? If VLC they have a wealth of online info (google search should help) or Nailbuster, he should be able to tell you immediately if you are using a tool in Pinup.

**Comment by syd711** [comment]
Gosh, it was late yesterday. I got everything working, but did "only" test with showing the transparent png with Popper displays. There, the transparency isn't working (although it should according to the documentation). Using my own overlays the transparency is working together with background videos.

See:
https://github.com/syd711/vpin-studio/blob/main/documentation/cards/transparent-cards.png

The feature will come with the next update. I'll leave the ticket open for now in case I missed something.

**Comment by Ltek** [comment]
this is going to be SOOO awesome. We REALLY need to get more people knowing about your app. I'm going to promote the heck out of it on the forums

**Comment by syd711** [comment]
Fixed with 2.12.0
