### ISSUE TITLE
[Feature Request] Identify orphaned assets

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#134]
When tables are added and deleted manually, a lot of assets may remain in the Popper media folders (and others).
It would be nice to clean these up and save space.

**Comment by Ltek** [comment]
nice!

**Comment by syd711** [comment]
The tool itself will be released this weekend, after that, I'll check with in with the developer about the integration.

**Comment by syd711** [comment]
The first release is out:
https://github.com/mmattner/vPinBackupManagerApp/releases/tag/2.2

An integration for the Studio is yet to add.

**Comment by syd711** [comment]
Has been released as part of VPBM.
https://github.com/mmattner/vPinBackupManagerApp
