### ISSUE TITLE
Full screen loading video

### ISSUE THREAD

**Issue by GerhardPK** [syd711/vpin-studio#138]
A “Blank” video should be loaded first. Then the actual full video
"append" and displayed on screen 3. (table(Screen03)

The blank video will be found (T-ARC Blank Empty Loading)  and can be downloaded. If I the actual
Loading video or upload from file , there is no question about overwrite, append. and the first blank video
appears to be overwritten.
I just tried it with Theater of Magic, I'm attaching the client log.

Ps the import functions Backglass, Altsound, Table, rom worked very well
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/14158076/vpin-studio-ui.log)

**Comment by yoshi98bc** [comment]
Yeah.  Since new update I cant seem to add more than one Loading video.  Also there should be an option to add a blank screen as well as add a second video and add it to the list on screen 3, just like popper does

**Comment by syd711** [comment]
It appears that when fixing the asset lookup and renaming, I forgot the "screen" named assets. Thanks for reporting. I'll fix this asap.

**Comment by syd711** [comment]
The update 2.11.3 should have fixed this issue. But I'll take a closer look again on the weekend since I hadn't much time to review everything an the the VPS database URL need to be released.

**Comment by syd711** [comment]
Retested and looks good to me.

**Comment by GerhardPK** [comment]
hello,

yes - works very well for me. thx
gerhard
________________________________
Von: syd711 ***@***.***>
Gesendet: Samstag, 10. Februar 2024 15:48
An: syd711/vpin-studio ***@***.***>
Cc: GerhardPK ***@***.***>; Author ***@***.***>
Betreff: Re: [syd711/vpin-studio] Full screen loading video (Issue #138)


Retested and looks good to me.
