### ISSUE TITLE
Add Fuzzy Logic and Renaming Options for .directb2s Files

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#145]
The name of .directb2s files not not necessarily match with VPX files.

- Add option to enable fuzzy matching. (delivered with 2.12.0)
- Add additional rename button for other directb2s files too.
- Add/Fix renaming for table replacements.

**Comment by necromancyr** [comment]
For the rename feature here, having an option for the b2s to be renamed to a new table name when a new version is uploaded to replace an older version would be great.

For example:
- Table & B2S name:  pinballv1.0.vpx, pinball1.0.b2s
- Upload a new version of the table named: pinbballv2.0.vpx
- Option, if enabled, automatically renames pinball1.0.b2s to pinball2.0.vpx to match the newly uploaded table.

**Comment by syd711** [comment]
Mhh, this is actually more of a bug. I have the feature already there, but disabled it for some reasons.
I changed the title and description of this ticket, beause it will include some other stuff

**Comment by syd711** [comment]
With the new backglass manager, shipped with version 2.13.0, you can now manage backglasses that are not linked to any table now. The fuzzy matching can be enabled in the backglass server settings. Note that the Studio itself will stick to exact matchings only, since it will become too cumbersome to take care of proper .directb2s file renaming, e.g. when a table is replaced and renamed. I have added help text and tooltips about this and hope the given solution is sufficient.

@necromancyr Thanks again for reporting the renaming issue. I improved the whole upload and replace dialog and fixed several bugs there. Related files are now properly renamed.
