### ISSUE TITLE
Rescan single table does not refresh screen - scan All Tables does.

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#148]
If I right-click a table and Rescan it, the UI does not refresh.... rescanning all tables Does refresh the UI properly.

minor issue but just ran into it so figured I'd post.

**Comment by syd711** [comment]
Thanks for reporting. Was this happening for all tables? I checked and the reload happens for both menu item: scan and scan all.
I can only assume an error is happening in the back? Something in the logs?
