### ISSUE TITLE
Switch to Fullscreen on Active Monitor

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#152]
The Studio fullscreen mode always uses the primary monitor, not the one it is on.

**Comment by wlan4you** [comment]
This is also NOT possible.
Everytime you open the ASSET MANAGER Again,
it go Back to the Monitor, where Studio is activ.
I have testet it: STUDIO on Monitor 3 not PRIMARY, Asset Manager go after a restart to Monitor 3.
He will not remember on which monitor the old Asset Manager was open.

Maybe you change back to a system which you have 1 Monitor, a button in the setup will be cool, to bring back the Asset Manager Windows from Screen 3 or 2 Back to the Screen where the Studio is working.

Hope you understand what i mean.
![IMG_9215](https://github.com/syd711/vpin-studio/assets/60288714/f8196c4c-ac80-4f15-8d1e-2628a63e4188)

**Comment by syd711** [comment]
- The fullscreen mode will work as expected with the next update. So it will stick to the screen the fullscreen has been triggered for.
- The asset manager dialog will open centered on the main window, no matter on which screen it is located.

**Comment by wlan4you** [comment]
Is it not possible, that the ASSET MANAGER will open in another screen every time (look in the screenshot) ?

**Comment by syd711** [comment]
While technical possible, it is not recommended. Since this dialog is "modal", it should alway be opened on the same screen as the main window (otherwise I would consider it a bug).

**Comment by syd711** [comment]
Solved with 2.12.0
