### ISSUE TITLE
Download Checklist 

### ISSUE THREAD

**Issue by yoshi98bc** [syd711/vpin-studio#153]
Would it be possible to incorporate some type of download manager. I tend to download tables faster than i can install them. It would be great to have a way to keep track of what is downloaded but not installed. Not sure how this could be done but i think it could be very useful. May be as easy as a user controlled check box thay indicates the table was downloaded.  Thanks

**Comment by syd711** [comment]
I get the idea. It is somehow related also to https://github.com/syd711/vpin-studio/issues/149.

I'm not sure if this kind of "Todo List" fits into the tool, but what I want to support in the long run is to provide a "quick"(?) upload:
You simply drop any kind of zip file into the Studio UI and the upload will extract all assets that are found inside. So no more single uploading each asset: vpx, directb2s, etc.

I hope this will make this checklist superflous. I leave the ticket open until then.

**Comment by syd711** [comment]
I've renamed the linked ticket and will continue the topic there.
I hope the aimed solution will fulfill your requirements too, so I close this ticket for now.
