### ISSUE TITLE
Add marker/UI element in Virtual Pinball Spreadsheet UI drop down to highlight updated item

### ISSUE THREAD

**Issue by necromancyr** [syd711/vpin-studio#156]
Add marker/UI element in Virtual Pinball Spreadsheet UI drop down to highlight the specific item that was highlighted that's triggering the update icon in the main interface.  

Concept/Example:
![example](https://github.com/syd711/vpin-studio/assets/3100326/27bef39b-9d69-4acc-a9a7-47849a31e274)

**Comment by syd711** [comment]
This feature is part of the 2.16.0 update.
