### ISSUE TITLE
[Feature Request] Serum DLL's updates since last freezy support

### ISSUE THREAD

**Issue by djfraleo** [syd711/vpin-studio#157]
**integrate or check into System Manager Overview  - New Serum DLL since last freezy update,**
I think you missed to integrate the new SERUM DLL updated since last freezy and mandatory to certain recent SERUM color roms,
like Grease, Guns & Roses, Elvis, etc.

**On freezy section, to be able to download and setup .ini config to enable new SERUM dll**
Need to compare new web files with both freezy and SERUM last updates.

If newer SERUM dll files are on github, then need to download zip file and only extract dlls required to be copied on VPINMAME folder

Check if both paths to dlls are valid, or need to update to the VPINMAME folder location on dmddevice.ini.
Then enable - set to true - plugin.1.passthrough = true into dmddevice.ini on VPINMAME folder.
Update info on System Manager.

**Comment by syd711** [comment]
Thank you for this hint! 

I wasn't aware of that. I started the Systtem Manager with a separate section for Serum. But after some communication in the VPC chat for Freezy, my latest status was that freezy includes Serum. Did this change? You got any documentation sources?

**Comment by djfraleo** [comment]
Yes, it has changed since November 2023, adn last freezy was Septembre 2023.

You can take a look at discusion by SERUM developer at vpuniverse.com for this hint:

https://vpuniverse.com/forums/topic/9486-serum64dll-in-vpinmame-directory-or-not/

**Comment by djfraleo** [comment]
Also, take a look at these roms that require this update:

https://vpuniverse.com/files/file/17835-grease-original-2023-serum-colorization-elvis-re-imagining/
https://vpuniverse.com/files/file/16587-elvis-stern-2004-serum-colorization/
https://vpuniverse.com/files/file/17131-guns-n-roses-data-east-1994-dmd-64-colors-serum-format/

**Comment by syd711** [comment]
Perfect, thank you for this feedback. I totally missed this. It's hard to keep track of the all changes in the stack.
I'll take care of it.

**Comment by syd711** [comment]
Ok, I got feedback from Zedrummer: https://vpuniverse.com/forums/topic/9486-serum64dll-in-vpinmame-directory-or-not/#comment-79025



> You don't need to declare anything, if you use Freezy's DLL, it will look for the file with the same architecture (so either serum.dll > or serum64.dll) in VPinMame directory and load it if available, or use the embedded one if not found. The latest Freezy's has the > latest serum[64].dll embedded, so you shouldn't need to add the serum[64].dll in your vpinmame.
 But adding it from https://github.com/zesinger/libserum/releases anyway ensure that whatever Freezy's version, you have the 
latest serum DLL used.

So I will leave the Serum as it is. You can download the latest one, but I don't have to care about the entries in the DmdDevice.ini.

**Comment by syd711** [comment]
Added serum support for version 2.14.0, including the option to edit the DmdDevice.ini from remote and some additional freezy validation.
