### ISSUE TITLE
Add "Blank Audio"

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#158]
Sometimes you don't want to hear "Loading game, have fun...".
Instead, add a blank audio so that the audio of the original loading video is played.

**Comment by wlan4you** [comment]
https://github.com/syd711/vpin-studio/assets/60288714/4d1366eb-f41a-4b48-af47-82e64723b828

Er wollte keine MP3 Uploaden.

**Bitte die Dateiendung umschreiben**
Audio_Silent_9ms.mp4 --> Audio_Silent_9ms.mp3

**Comment by syd711** [comment]
Released with 2.13.0.

**Comment by wlan4you** [comment]
Amazing !
