### ISSUE TITLE
High Score Card - transparency not working, solid black background

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#162]
v2.12.0 ... card only have solid black backround. I tried all different Alpha settings (highest, lowest, in between) and have Transparent checked... VPS preview looks correct but all generated cards have only a solid black background

**Comment by syd711** [comment]
I tested this on two different machines. When I startup a table, I see the transparent highscore card.
Could you attach one of these files here?

**Comment by syd711** [comment]
I see, now I got it. I only tested the cards using the "Show Highscore Card on Startup" feature where the card is shown by the Studio - not Popper. I've not tested to show the card via Popper screen and will take a look. Thanks for the additional information.

**Comment by syd711** [comment]
Did you enable the transparency in Popper?
![image](https://github.com/syd711/vpin-studio/assets/1169826/3bcfe01c-061a-472d-b3a1-12432bcd84a7)

**Comment by Ltek** [comment]
that was it!  Might want VPS to set that setting inside Popper when someone builds a transparent card :)

**Comment by syd711** [comment]
Awesome! Nice we figured this one out. I took me a while to find the documentation too.
I'm corrently not mingling with the screen setup of Popper and do only read them.
Since the flag is likely only changed once, I took a "cheaper" approach and added an info-box in case the transparency is not enabled.

![image](https://github.com/syd711/vpin-studio/assets/1169826/52843bb1-02f1-4400-863f-4852462dbb41)

**Comment by syd711** [comment]
Damn, I accidently deleted my last comment, but you should have received an email anyway.
So there is the screenshot again:

![image](https://github.com/syd711/vpin-studio/assets/1169826/ccbb9fd6-6f26-4fa8-ad8c-4e5b7fb78a81)

**Comment by Ltek** [comment]
After setting Popper to 'transparent' now VS cards are 100% transparent background, no alpha. The images do show correctly when opened in other apps, just not popper.

My VPS 2.13 settings does not look like your screenshot, and that documentation 'Enable Screen Transparency' does not seem to exist, I searched manually and google. 
![image](https://github.com/syd711/vpin-studio/assets/1626802/6a9d3326-61fc-49b0-96a6-a33d03c003c6)

**Comment by syd711** [comment]
Sorry for the misunderstanding. The picture I posted was only a preview of the next release where the issue will be solved. I should have mentioned that.

I'll check if I can do something about the alpha setting.

**Comment by syd711** [comment]
I got feedback from nailbuster that only one-color transparency is supported (which is the checkbox in the screens option).
Since there is not much else I can do here, I close this ticket.
