### ISSUE TITLE
Check client update when installed in the program files folder.

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#164]
> So, think I may have found the issue re: clicking on updating and the client not updating.  It seems that running update on the same computer as server is running on updates the client and server fine.  Running update on another machine connected via network to the computer running VPIn-studios sever updates the server on the server machine but doesn't do anything re: client updating on either machine.
No logs seem to get captured by the client on the remote PC either.  Full logs on the server computer.  The remote PC install was done just via the "client" installer, not the full one.
...and the answer is you need to run ALPINball as adminstrator.  then it works.
Seems only required for updating.
Odd.
Same for writing to a log file - most likely has to do with it being installed into program files directory I guess?

**Comment by Ltek** [comment]
I think I'm seeing the opposite... I run VPS remotely (network connected front-end). When VPS alerts me there is an update, I tell it to update. BUT, VPS is -not- updating server-side, only the network connected client. It has done this the last 2 updates at least.

**Comment by syd711** [comment]
I recently discovered that the Windows Defender is blocking the file for a few minutes and also causing a high CPU usage on the server.
I documented how to create an exclusion but this needs to be checked by the updater too of course:
https://github.com/syd711/vpin-studio/wiki/Troubleshooting#the-server-is-causing-high-cpu-usage-by-windows-defender

**Comment by syd711** [comment]
The installer now runs with admin permissions, so updates will work when installed with this newer version again.
For the server update issue, I added a hint in the update dialog and also a section in the "Troubleshooting" section of the wiki.
I will close the ticket for now.
