### ISSUE TITLE
Support Custom High Score Cards

### ISSUE THREAD

**Issue by ecchodun** [syd711/vpin-studio#166]
With respect to the high scores displays, is there a way to perhaps modify the font of text so that it changes to fit the window.  For example, I generally like the font size for the table name, but some of the table name's are so long that they get cut-off on each side of the high score window.  Also, tables with various high scores for different purposes are almost unreadable because the fonts are so small.  (pictures attached with various fonts). Perhaps even allowing for different fonts for different tables?
![20240226_194646](https://github.com/syd711/vpin-studio/assets/78839467/aad6f104-881c-4b47-891a-b359aaa3a799)
![20240226_194701](https://github.com/syd711/vpin-studio/assets/78839467/54b9c427-fa1e-46f6-8620-1e2f6ca269f6)
![20240226_194717](https://github.com/syd711/vpin-studio/assets/78839467/55f4c613-8eaa-411a-9719-d160bbc2d43d)

Additional enhancement might be an auto-scrolling high score display (thought I'm not sure this could be implemented in PinUP Player).    To that end, one of the high score implementations I really enjoyed was a plug in off Pinball X.  It was a scrollable high score window that could be the size of a 100 x 100 window and would just display the initials and score.  

My enhancements are not to take anything away from this otherwise excellent program.  Just some suggestions.

**Comment by syd711** [comment]
For the table name I can add an automatic downscale, so that the table name will match.
Regarding the overall text size, there isn't much I can do. The scrollable idea is nice, but doesn not work with Popper.
I could only see to make the score card configurations table specific / to allow custom designs for each table.

**Comment by ecchodun** [comment]
I love the specific configuration for each card only because some cards have more than 4 or 5 scores.  It would also fix the font size issue.

**Comment by syd711** [comment]
The table name scaling has been fixed with 2.14.0.
I changed the title of the ticket for the custom highscore cards support.

**Comment by ecchodun** [comment]
Thank you for everything.  You'r programming skills are excellent.

Eric

**Comment by syd711** [comment]
Fixed with 2.15.0 which now supports individual highscore cards.
