### ISSUE TITLE
Pup-Packs not detected in all cases

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#170]
**Describe the bug**
Not sure how VPS looks for PuP-Packs but it seems it may only be using cGameName?

Another common method is using pGameName  in the script, example with Dragon's Lair...

pGameName = "dragonlair"  ' pupvideos folder name for the Pup-Pack
cGameName = "Mphisto"    ' ROM that runs the table and uses DOF

![image](https://github.com/syd711/vpin-studio/assets/1626802/5e0b0556-f242-4b56-bdc0-26976f98caaa)

**Comment by syd711** [comment]
Interesting. I didn't knew that. You got other examples? I'll see how I can add the support for that.

**Comment by Ltek** [comment]
> Interesting. I didn't knew that. You got other examples? I'll see how I can add the support for that.

most authors create tables using real ROMs and reskinning table made for that ROM. When using PuPs with a table (as most modern table do these days) they must have a different/unique table name to ensure a unique PuP folder. You cant have Pup-Packs using the same folder for different tables, of course. Table authors then must...

1. set cGameName to the 'real' ROM name (to ensure DOF works); then set pGameName (p for PuP) as a unique name for the PuP's folder 
- OR -
2. make the cGameName unique (e.g. not the name of a real ROM) and then put in an entry into VPMAlias.TXT to associate the cGameName to the real ROM name so DOF works without creating a new DOF entry for the unique cGameName

a few recent (past few months) tables...
Total Nuclear Annihilation v1.4
IronMaiden
Dragon's Lair
and many many more

**Comment by mkl66** [comment]
Hi ,
I also had this issue with all my PUP tables which uses a ROM alias.
The is recognized correctly in the VPinMame pane, but the PUP pack is not recognized

**Comment by mkl66** [comment]
Correction of the previous comment: The **ROM alias**  is recognized correctly.....

**Comment by syd711** [comment]
Thanks for reporting. The fix for this will come with the next update next week.

**Comment by syd711** [comment]
Fixed with 2.15.0

I added misc. improvements regarding the lookup. I skipped providing the option to apply the pup pack manually, hoping that the improved table scan and added alias support will resolve these issues. I close the ticket for now.
