### ISSUE TITLE
[Feature Request] DOF "Sync Now" button on main top menu

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#171]
Love the DOF sync timer!  Would be useful to have a Sync Now button on the main window, top menu bar.
With on-screen feedback when its completed success or fail.

![image](https://github.com/syd711/vpin-studio/assets/1626802/efb37c2f-3934-4be7-a313-2b094562abf5)

**Comment by syd711** [comment]
Added in 2.15.0
