### ISSUE TITLE
[Feature Request] User defined "Templates" for High Score Card settings

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#172]
Ask: Allow users to create/save, then set custom defined templates Score Placements, per table. This is useful for several situations but I discovered the need since I place the Cards over the FullDMD videos... which many have 'blank' DMD locations on screen... thus, the high scores are perfect to place in that blank area (see attached examples). Users could share those settings quickly and easily.  

People may have different preferences for where they place the High Score Cards... mine is the FullDMD. My logic is... FullDMD is pretty otherwise mostly or completely useless during, its an easy location to view (no need to look down at the playfield) and you can use the backglass for intro videos (largest screen makes sense IMO for videos)

For FullDMD There are two standard locations: Middle and Low

For Middle, I found these settings place the scores symmetrically in all dimensions inside the blank area...
-- Padding 90
-- Title Font 72px
-- Table Font 80px
-- Score Font 90px
-- Wheel Image Padding 100
-- Row Separator 0

thus, being able to create and re-use templates would save a ton of time and allow users to help each other when using Cards 

![image](https://github.com/syd711/vpin-studio/assets/1626802/7fcb05ad-494a-4dec-9428-df579354252f)
![image](https://github.com/syd711/vpin-studio/assets/1626802/007395e0-a36d-43f3-856e-3ab63cd38490)

**Comment by syd711** [comment]
That would look nice indeed. It is already on the roadmap, continued in issue https://github.com/syd711/vpin-studio/issues/166.

**Comment by Ltek** [comment]
I need to remove the 'High Score' text, an example...

![20240303_114214](https://github.com/syd711/vpin-studio/assets/1626802/9bc50528-0e44-42f3-963f-ab2e047b7a84)

**Comment by syd711** [comment]
Yes, thought the same when reading your post.

**Comment by syd711** [comment]
Fixed with 2.15.0 which now supports individual highscore cards.

**Comment by Ltek** [comment]
Note to Users... this change wipes out all existing settings.
