### ISSUE TITLE
Update the DateFileUpdated field in PopperDB with uploaded datetime on "Upload and Replace" into Popper

### ISSUE THREAD

**Issue by connerhelton** [syd711/vpin-studio#177]
Current popper behavior to update a table is to do so via Game Manager. The user will drag & drop the table update on top of either the "Update" or "Replace" button, most select "Update." On update, Popper will prompt to overwrite the file (already covered by VPS), ask the user if they wish to make a backup (next request), and set the **DateFileUpdated** field in the DB. This field is used to set the system" Recently Updated" playlist and is really handy when testing table updates. 

**Describe the solution you'd like**
As a Table Administrator, when I upload a table update via VPS, and select the option to "Upload and Replace", I want to set the **DateFileUpdated** field in the Popper DB to the datetime (preferably from the server) the file was uploaded & replaced, so that I can use the "Recently Uploaded" playlist to test tables. 

**Describe alternatives you've considered**
Maybe make the feature optional? Its not an option to not set that value in popper.

**Additional context**
I'll create a separate ticket for using popper backup. This should be a "quick win"

**Comment by syd711** [comment]
Good catch. I never noticed this field before. I only do update the "DateUpdated" field.

**Comment by syd711** [comment]
Fixed with 2.14.2
