### ISSUE TITLE
Backup existing tables on "Upload and Replace" into Popper for table updates

### ISSUE THREAD

**Issue by connerhelton** [syd711/vpin-studio#178]
**Is your feature request related to a problem? Please describe.**
I'm nervous VPS just overwrites tables when doing table updates without doing a backup.

**Describe the solution you'd like**
As a Cabinet Administrator, I like using Popper's Game Manager to perform table updates because it asks if I would like to do a backup. I would like an option within VPS that when I do an "_Upload and Replace_", VPS will mimic the "Game Backup" functionality of Popper by copying the existing game file into the **\tables\pupBackups** folder and rename the file to "existingfilename.vpx.bak".

**Describe alternatives you've considered**
Take what popper does a step further and append the extension with a simple form date so that multiple "backup" versions can exist in the same pupBackups folder.

**Additional context**

**Comment by connerhelton** [comment]
As a "Cabinet Administrator", I'm constantly nervous about updating things on my cab. I have VP Backup Manager, but maybe this is a form of lightweight option that can just be done as a simple nice-to-have.

1. Allow the user to define a "Backup" location, this may be local storage, usb removable, or even network location like an Unraid server. 
2. When the server starts, check to see if "backup" folder exists, and if not then create it for the user. 
3. Create subfolders within the primary backup folder for each group of thing (tables, backglass, altcolor, etc). 
5. When the user updates one of the below, a prompt is displayed in the client to ask if the user if they wish to make a backup. 
6. If the user does not agree to a backup, nothing happens
7. If the user **does** agree to a backup, then copy the old file into the appropriate "backup" subfolder for its type, give the file a new extension of ".bak" and append a simple "datetime" something like "foobar.vpx.bak031024_1711"
8. Give some kind of information to let the user know its been backed up. 

**Simple objects to consider for backup**
- Backglass
- AltColor
- AltSound
- Table
- PupPack

Alternatively, maybe VP Backup Manager could invoke a super simple command do a backup if one of these things are triggered.

**Additional context**
Cabinet admins often have multiple emulators (VPX, VPX VR, VPX Beta, FP, etc). A complication I haven't thought through is how to keep SOME things separate such as table & backglass for the use case of VPX & VPX Beta, while shared resources like altcolor are universal. 

Super future thing would be to have some kind of zip archiving, and a simple restoration process that unpacks the zip and replaces new things in case the new bits broke something.

**Comment by syd711** [comment]
> Super future thing would be to have some kind of zip archiving, and a simple restoration process that unpacks the zip and replaces new things in case the new bits broke something.

The early versions of the Studio did provide this. I got immediate response from the vpuniverse that they don't like to see any other distribution methods than their website and these archives can be easily shared with other users. That's why I switched to the third party tool "Backup Manager" which binds the backups to a table.  (I really would have liked to proceed with my own "open" format).

Regarding this VPX file backup: this is something that can be done. But I won't extend it to a level that additional resources are backed up too.

**Comment by oper8r00** [comment]
>  I got immediate response from the vpuniverse that they don't like to see any other distribution methods than their website and these archives can be easily shared with other users

This makes complete sense given some of the troubles the VP scene has had over the years. 

I've wondered if there is a reason to not have a backup like system for other resources too. I know some users who try to mimic the "pupBackup" behavior through creating a folder manually and each time they change a resource they copy & paste into that backup folder. 

Any reason this couldn't be something similar? Even if it was just a "backups" folder in each of the resource folders?

**Comment by syd711** [comment]
The problem I see here is that in the end, these backups wouldn't much differ in what the VPBM is doing. And these backups are only one click away. I get the point that when a table is replaced a backup would be nice, but its hard to draw the line.
Any reason why the VPBM isn't working for you? We could also ask Matt, the developer of VPBM for some adjustments.

**Comment by syd711** [comment]
![uploads](https://github.com/syd711/vpin-studio/assets/1169826/198bddc1-a66f-4738-a7af-2f20393f8811)

I added a backup option for the table uploads. I think these are the most critical resources that may get lost and since my uploads may delete them, it can also backup them now. For the other backups I would still refer to VPBM (https://github.com/mmattner/vPinBackupManagerApp/).

**Comment by syd711** [comment]
The back option for the replaced tables has been delivered with 2.16.0, so I consider this ticket as closed.
