### ISSUE TITLE
Scorecard generation sent to multiple screens

### ISSUE THREAD

**Issue by jestermgee** [syd711/vpin-studio#181]
In the settings I have set the high score card to be saved to the GameInfo screen which it is correctly saving to, but it is also saving/overwriting my "Other2" screen which I use for custom videos.

**Comment by syd711** [comment]
Ups, that would be pretty bad indeed. I'll look into it.

**Comment by syd711** [comment]
I tested this again and the cards were generated into the correct folder.
Maybe the overwriting happened before you changed the settings?
If the issue is reproduceable, could you provide more details and the log files located in the installation folder?

**Comment by jestermgee** [comment]
Thanks for the reply. 

I restored my media folders and I just went to check the settings in vpin studio but when I click on the High Score Card Settings I receive an Error that simply says "Error" and now not able to change any settings. 

Attached logs

![image](https://github.com/syd711/vpin-studio/assets/44385170/f61d1d23-6d8b-4c28-a0ba-dc533a96d625)

[Logs.zip](https://github.com/syd711/vpin-studio/files/14596460/Logs.zip)

**Comment by syd711** [comment]
Interesting. For the highscore parsing I'm using "pinemhi". You have a highscore file where the tool completely crashes.
Could you attach the file C:\vPinball\VisualPinball\VPinMAME\nvram\**robo_a34.nv here**? The folder might differ on your system. But I can then reproduce the error and deliver a patch.

**Comment by syd711** [comment]
Ah, I missed something. While my last message is not the root cause of your problem, it would certainly help me.
I found two other things that might have caused this error. I'll look into it and come back to you.

**Comment by jestermgee** [comment]
I deleted the VPin Studio database file and just setup things again, it is all working now as expected so I am guessing initially when the thumbs were generated I must have first setup to the Info folder before I understood what was happening. 

Running a test again, they appear in my Other 2 folder only now so that side is fine I believe. 

Attached the requested nv file

[robo_a34.zip](https://github.com/syd711/vpin-studio/files/14610280/robo_a34.zip)

**Comment by syd711** [comment]
Phew, happy to hear that! Thanks for the feedback and the file! I'll close the ticket then. I have found the bug when the screen selection is resetted and the fix will come with the next update.
