### ISSUE TITLE
Repair Layout of VPin MAME View

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#186]
The layout is broken, because the pref height is not set

![image](https://github.com/syd711/vpin-studio/assets/1169826/397ded4c-9702-4e77-ac84-ae4023959c9b)

**Comment by syd711** [comment]
Fixed with 2.15.0

**Comment by ecchodun** [comment]
This is not working for me with 2.15.0.
![Overlap](https://github.com/syd711/vpin-studio/assets/78839467/3926cbf0-4381-4271-bb7a-68c0a2ae013e)
