### ISSUE TITLE
Table Data Dialog Size

### ISSUE THREAD

**Issue by ecchodun** [syd711/vpin-studio#188]
This is not working for me with 2.15.0.
![Overlap](https://github.com/syd711/vpin-studio/assets/78839467/3926cbf0-4381-4271-bb7a-68c0a2ae013e)

_Originally posted by @ecchodun in https://github.com/syd711/vpin-studio/issues/186#issuecomment-2025743063_

**Comment by ecchodun** [comment]
This is still a bug where the  pop-up table window exceeds the top of Vpin Studio (can't grab it to bring it down), but a workaround was to change your screen to portrait mode (from landscape), move the window down and then change the screen back.

**Comment by syd711** [comment]
The dialog is alway shown centered. So it is too big for your resolution and ends up partly outside the screen, right?

**Comment by ecchodun** [comment]
When I load Vpin Studio and click on Asset Manager, the window that pops up is already off screen at the top of my screen.  It looks like the attached.  I can barely see the change table icons at the top right and I'm forced to press Alt-F4 to close it to get back to the main dashboard.  I didn't have this issue with prior versions (prior to the last two updates).
![Example](https://github.com/syd711/vpin-studio/assets/78839467/db00788f-edc9-4e67-a3f6-f26193b3e420)

**Comment by syd711** [comment]
Ok, that's indeed pretty annoying. Sorry for that. I have no idea what have caused this. Can you also attach a full screen screenshot or give me the resolution of your screen?

**Comment by ecchodun** [comment]
No worries.  Full screen shot attached.  My resolution is 1920 x 1080.
![screenshot](https://github.com/syd711/vpin-studio/assets/78839467/a9b1cc1f-a251-4ee5-85a4-a5487d96574f)

**Comment by syd711** [comment]
I think you have and addition scaling of 125% set. Usually the dialogs fit and are never larger than HD.
Anyway, it's a shortcoming on my side. I'll see what I can do to reduce the size of the dialogs.

**Comment by ecchodun** [comment]
You're exactly right.  Scaling is set at 125% per recommended in Widnows.   I can always push it down when I used Vpin Studio.

**Comment by syd711** [comment]
I fixed both dialogs so that they will fit for your resolution again. The only other dialog that has a larger size is the highscore card template designer. But that dialog and be resized and the size is stored, so there should be no issue.
The fixed dialogs will come with the next update.

**Comment by ecchodun** [comment]
Thank you.

**Comment by syd711** [comment]
Fixed with 2.16.0.
I also checked the preferences and fixed a bunch of issues (when used on smaller screens) there too.
