### ISSUE TITLE
[Feature Request] High Score templates : "Apply to All" button

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#190]
templates are great... until you need to apply them to 200 tables ;-)

I suggest having multiple button options...
- Apply to Only this table
- Apply to All Tables
- Apply to Tables Highlighted on Table List  (left side of screen)

**Comment by syd711** [comment]
I thought about that. By default, all tables use the default template. So if you customize this, there is no need to apply anything.
The table list supports single and multi selection for the template selection. So in the and all these points are already supported, right?

**Comment by syd711** [comment]
As discussed, this seems to be solved.
