### ISSUE TITLE
Server side client not updated for remote updates

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#191]
Looks like the Server-side (on the Vpin) is not getting updated properly. Either the client and/or server software is not updating when doing it from a remote VPS client on the remote PC (not the local Vpin)

I was on the prior version on both the Vpin (VPS client & server) and my remote PC (VPS client). 

Connected from remote PC's VPC client to the Vpin (client & server) ... the VPS client showed the 2.15.0 update avaialble which I selected for it to install immediately.

the remote VPS client showed both client & server software completed without error. 

BUT when local on the Vpin, the client showed is was still on the older version -- showing the 2.15 version was available so I had to install in on the vPin locally.

**Comment by syd711** [comment]
Fixed with 2.16.0. The remote client is now updated too.
I noticed one label is not updated in the dialog yet, but will fix this small issue with the next update.
