### ISSUE TITLE
Font size not always changing in high score cards

### ISSUE THREAD

**Issue by ecchodun** [syd711/vpin-studio#195]
I'm not sure if it's overly long high score data, but changing the font size does not always show in the high score card display.  See example attached where I have a standard Arial font and change the size from 160 to 340px with no difference.
![pic1](https://github.com/syd711/vpin-studio/assets/78839467/f91436c8-dd6f-4e10-bb40-828207070297)
![pic2](https://github.com/syd711/vpin-studio/assets/78839467/fb30d84a-652b-481d-9df5-6337b0707ab3)

**Comment by syd711** [comment]
It's by intention. The font size gets downscaled, especially for large score texts, so that is matches with the card size.
Now that you can create custom cards this may not be required anymore. But I find it still useful. AC/DB is another good example here.

**Comment by syd711** [comment]
I assume I answered the question and close this ticket.
