### ISSUE TITLE
[Feature Request] Clone existing table to create different table versions

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#197]
Some tables have multiple versions but we may want to have the same exact images/video/etc in popper... and only change the table name/version.  LoTR and Stranger Things are two example where there are 3 similar yet different versions.

Having VPS clone an existing table and prompting the user to change/edit the meta data before it writes it would save TONS of time.

thx!

**Comment by Ltek** [comment]
rough draft below of what I was thinking for workflow. 

In order to have the naming convention and meta data updated as the user wants, with the least amount of clicks / selections...

1. highlight existing table you want to 'add' a version of     // add new, not replacing the existing table
2. right-click, select "Clone Table to Add Another Version"    // new VPS menu option
3. editable dialog box with meta data of existing table    // VPS copies existing meta data to tmp file, allows user to edit onscreen
4. dialog to select the .VPX file, B2S, etc all on the same screen   // that universal uploader feature request would help here ;-)
5. 'Finish' button   // VPS adds new table using edited meta data, and duplicates existing media - renaming to match metadata entered

**Comment by syd711** [comment]
Delivered with 2.16.0.

I toggled step 3 and 4 since the prefabrication might get lost when the upload fails. Since the Table Data Manager now opens right after uploading, I think the whole workflow has been significantly improved. The whole upload step can/will be improved once the universal upload is available.

**Comment by Ltek** [comment]
this is great!  now we can EASILY test or use different versions side-by-side with other versions and have all the right media/data/etc in the system!
