### ISSUE TITLE
Updating VpinMAME in System Manager does not have the color rom update (-sc- file)

### ISSUE THREAD

**Issue by djfraleo** [syd711/vpin-studio#198]
On System Manager, when you try to update VPinMAME on the VPin MAME tab, you can not select the -sc- version of the VpínMAME.zip on the Release Artifact selector.

The -sc- is necesary for certain color roms. If you install the version System Manager suggest, then you will lose DMD coloring of such roms.

**Expected behavior**
The user should choose which version they prefer to install.

**Screenshots**
![image](https://github.com/syd711/vpin-studio/assets/5881996/2a8be120-97e3-49aa-aaff-2486f055b7f9)

**Comment by syd711** [comment]
I see, thanks for letting me know! I'll fix this with the next release.

**Comment by syd711** [comment]
Fixed with 2.16.0
