### ISSUE TITLE
Support PrOPPER Renaming

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#199]
See
https://www.youtube.com/watch?v=AoVkUBsUT-Q

**Comment by syd711** [comment]
As a reference for my self: Here would be unrenamed original game:

![image](https://github.com/syd711/vpin-studio/assets/1169826/b02eefe9-65cb-4956-99eb-b37de0056ca3)


And the imported one:

![image](https://github.com/syd711/vpin-studio/assets/1169826/11554923-605b-4cce-a18f-5994ed327dc9)

**Comment by spaceangel1970** [comment]
This actually renames the filenames (gamename)(original 2024)(MOD)(author)(version)

**Comment by syd711** [comment]
Part of 2.17.0

**Comment by jasoncross** [comment]
This doesn't seem to be renaming related files like .ini files.  Presuming you want to replicate the functionality of Popper media manager, it should rename .ini and .directb2s files to match.

**Comment by syd711** [comment]
There was a bug, fixed with 2.17.3.
You used the latest version?
