### ISSUE TITLE
Client starts bigger than screen size

### ISSUE THREAD

**Issue by francisdb** [syd711/vpin-studio#2]
Windows 11 Home
2560x1440 screen

I connect to my cabinet and get this fullscreen

![image](https://github.com/syd711/vpin-studio/assets/161305/da234a69-d8f9-4998-b5f2-4cb0e6e049e0)

**Comment by syd711** [comment]
You have some additional scaling set for Windows? The UI starts with a width of 1920px, so I'm suprised that the initial size exceeds 2560px.

**Comment by francisdb** [comment]
Yes, it's related to scaling. At 100% I can use the app.

<img width="764" alt="image" src="https://github.com/syd711/vpin-studio/assets/161305/e7d84edf-fcc5-4f9c-becc-7a50bebf89a9">

This is a 14 inch laptop so 100% scale at that resolution is tiny.

**Comment by syd711** [comment]
I see. Thank you for your feedback. I'll come up with a better solution here with the next update. (~1 week)

**Comment by syd711** [comment]
I'm grateful for every feedback. The playlist management/support is something that will come. For the media search I would have to ask the PINUp Popper developer how open he is to share his infrastructure with other tools.

**Comment by syd711** [comment]
Fixed with 1.3.4
