### ISSUE TITLE
Vpin studio 2.16.2 Breaks my install

### ISSUE THREAD

**Issue by Meshuggah70** [syd711/vpin-studio#202]
**Describe the bug**
After updating when it goes back to Loading tables just hangs indefinably . if something is clicked  says Zulu platform not responding and vpinstudio not responding following that. re installed 3 time same result. Reverted back to Version 2.16.0 everything goes back to working normal

Windows 11 Pc, Ryzen 9 5950X

**Comment by syd711** [comment]
Thanks for reporting,  but I need the log files, located in the installation folder, in that case. Only then I'm able to reproduce what have happend and can fix it. I don't assume you have a copy of them? I'm usually eager to fix these critical bugs fast and my 2.16.2 installer did run smoothly.

**Comment by Meshuggah70** [comment]
I'm hoping they're still in the file. All I did was downgrade. I'm assuming
it didn't overwrite anything because my API key was still there. I'll check
later on tonight when I get home.

**Comment by ThePrintz** [comment]
Broke my install as well. See logs.
[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/15001794/vpin-studio-server.log)
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/15001795/vpin-studio-ui.log)

**Comment by Meshuggah70** [comment]
here are my Logs as well 

[vpin-studio-server.2024-04-15.log](https://github.com/syd711/vpin-studio/files/15004499/vpin-studio-server.2024-04-15.log)
[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/15004500/vpin-studio-server.log)
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/15004501/vpin-studio-ui.log)

**Comment by syd711** [comment]
Thanks guys! I found the issue and will push out another hotfix today.

**Comment by Meshuggah70** [comment]
No problem! It's an awesome program.
