### ISSUE TITLE
Show background on template editor

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#203]
While creating the templates iwould help to show the background on the editor, to help align to the image we are using
![image](https://github.com/syd711/vpin-studio/assets/1626802/6da6bf21-aa15-470f-a796-f2b0f48dc752)

**Comment by Ltek** [comment]
the new template overlays are working well!  being able to display the Popper Background on the main screen with help people align things quicker... right now, its a guessing, build, go back change, try again.

**Comment by syd711** [comment]
The background is there and for the "embedding" a separate ticket has been opened.
Fixed with 2.20.3
