### ISSUE TITLE
[Feature Request] Dedicated Horizontal and Vertical Controls for Wheel and Text, separately

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#204]
Seems like 'padding' sets both the horizonal and vertical at the same time... so its not possible to get the text, without a wheel, correctly placed on a given background, like the example where I want it in the lower FullDMD window but left justified-kinda.

![image](https://github.com/syd711/vpin-studio/assets/1626802/59b8e2de-e714-41b0-80fc-7c6c927c0413)

**Comment by syd711** [comment]
I'll add the additional properties "Margin Top/Left/Right". This way, this should solve the issue.

**Comment by Ltek** [comment]
thank you... this will make things work really nicely!

**Comment by syd711** [comment]
I've added margins and wheelsize properties and also fixed some calculations.
I assume the combination of these properties should be sufficient for now.

Part of 2.17.0

**Comment by Ltek** [comment]
nice - thank you!
