### ISSUE TITLE
[Feature Request] User Settable High Score Card Size and on-screen location, per template

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#205]
For some background images you can see we may want to specify a size of the 'box' for the card as to not overlap other images (bonzai) or in some cases (Big Buck) we may want to make the box block out some of the image

![image](https://github.com/syd711/vpin-studio/assets/1626802/b209119d-a042-4ce0-ba16-ec8be58c3e6f)

![image](https://github.com/syd711/vpin-studio/assets/1626802/c44d5067-561b-428e-9818-be070b1bd9c4)

**Comment by syd711** [comment]
I think I forgot to close this one. This is implemented by the "Canvas" feature in the card designer.
