### ISSUE TITLE
[Feature Request] Include other media types/checks in 'VPX Tables' tab

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#207]
Would love to be able the include (add/remove) what items will be checked for and validated for all tables... for example, I want to make sure that ALL of my tables have media for Help, Full DMD, Loading, etc... showing this on the VPX table, and using these in validation would e very very helpful

**Comment by syd711** [comment]
Hi Ltek! To rephrase you proposal: Your idea is that the user can select a mime-type, (e.g. video/mp4) for a screen, (e.g."DMD") and the validator checks that all DMDs have a video (instead just "some" media), right?

**Comment by Ltek** [comment]
2 part ask, I didnt explain well

1. Add column for each Media Screen function (FullDMD, Topper, Loading, etc)... want to know, does mean exist at all for them.
2. mime-type for each column: video, static image (png, jpg, etc). Not sure showing the exact mime matters,  I want to know "Do I have something there, and is it a video". 

For most things (FullDMD, Loading, etc) people prob want videos. But sometimes you may not... like maybe for a topper a user wants all to be a static banner (PNG, JPG, etc). 
This will help know, at a glance (single screen/grid), what tables have what media types... thus, if I see that some tables only have static images for FullDMD, I know I need to go look for videos (or make them). Or if the Help Cards are missing, etc

**Comment by syd711** [comment]
Ah, I see. Of course, the table would become crowed. Maybe this is something that can be combined with "Asset Manager View" - the topic we started in the other ticket. Then not only the asset manager would be shown, but also the table columns would change to these new ones.

**Comment by Ltek** [comment]
I see the goal of the main VPX Table tab is to see everything 'at a glance' and be able to filter, etc.
The reason to show the other media types is to quickly identify what 'needs' updating (not validated) and which items... thus I could quickly see that 25 of my 112 tables need media updates. This would not be possible if it was hidden in asset mgr.

To help for those who do not want to see... maybe add show/hide function for columns on the VPX Table?  I have a 32" screen so no worries for me :P

**Comment by syd711** [comment]
I didn't mean to hide this in the asset manager. I wanted to pick up your other idea of having the asset manager inside the table view (as a toggle view). I liked the idea to have a different view mode depending on the work you are focused. So my idea here was to show the column when this mode is used:

![image](https://github.com/syd711/vpin-studio/assets/1169826/89f868f9-4cea-461c-ae81-05b2f0aad397)

The right asset column would be smaller and the table view larget but with asset columns instead of the other "regular" ones.
This way, the idea would still work on smaller screens too.

**Comment by Ltek** [comment]
maybe this will make it more clear...
![Screenshot 2024-04-20 195057](https://github.com/syd711/vpin-studio/assets/1626802/599bb973-7626-46f5-a617-23e00db5bb21)
