### ISSUE TITLE
[Feature Request] Open folder button on Popper Media

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#213]
would be great to have a little icon on each media type to open the folder... helps if we need to edit/optimize the videos, etc. Yup, guess what I did today :-P

Not urgent of course but nice for convenience :)
maybe I use VPS too much ?  haha, not a chance, its awesome, I love it!

![image](https://github.com/syd711/vpin-studio/assets/1626802/4e969a89-baec-4fc4-9676-53d024826b14)

**Comment by syd711** [comment]
But you have them already: 
![image](https://github.com/syd711/vpin-studio/assets/1169826/d01703b3-e591-48d1-8a60-ed1127aa2843)

I jus noticed that the wrong icon and color is used there. but the button does what you want.

**Comment by Ltek** [comment]
that button doesnt exist in my setup... and I just updated 5 mins ago to .2, still not showing anywhere..

![image](https://github.com/syd711/vpin-studio/assets/1626802/e13477b6-04eb-4b56-9ed1-0fce9fab3807)

**Comment by syd711** [comment]
The folder button is only available when you work on the cabinet.

> would be great to have a little icon on each media type to open the folder

Maybe I got this wrong?

**Comment by Ltek** [comment]
OK, I just tested... I almost never run VPS client from the server so just checked... yes, that option is there when running locally. Can you add for when running it remote?  even if we have to manually input a network path in settings (during setup too).

**Comment by syd711** [comment]
That would be a nice feature. Once you open the VPin installation path to the network, almost all "yellow-ish" open button could be shown for a remote client too.

**Comment by syd711** [comment]
Released with 2.18.0
