### ISSUE TITLE
[Feature Request] Set Initial System Volume - makes PinVol work properly

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#214]
Since you have integrated PinVol startup, I think it would help users to also integrate SetVol... which IMO is required to run PinVol properly since PinVol has a bug and/or serious gap

I love PinVol but it doesnt work properly / has a serious design flaw. (see the bug I reported Mar 2023;  https://github.com/mjrgh/PinVol/issues/11) 

The workaround is set the system Volume level / control prior to launching PinVol.
... I'm sure you can do this native in VPS very easily.  I have been using a SetVol, a free command-line app.

PinVol needs to have an initialization on load/start level that sets the system volume in case the system volume changes for any reason... aka, it needs a baseline set on boot otherwise your PinVol set table volume "12" will mean different things based on the actual system vol which can be 20, 35, 60, etc... thus changing the meaning of volume 12 in PinVol since its a relative volume, not absolute.

I use SetVol in a BAT file that runs on user login (user I use for the pinball login) to set the OS volume to 100%. This way, PinVol will have the system's full range - and more importantly, same volume starting point on every reboot/re-login no matter what the user did to the volume prior. This essentially allows PinVol to properly normalize pinball table / cabinet volumes. 

Put another way... even if someone changes the OS volume prior to the last shutdown or log out (say they were using the system for something else: testing, work, etc) the user will not need to re-do volume level for pinball because SetVol will re-set the system the baseline level used to 'calibrate' your tables with PinVol

https://github.com/TommyMaes/SetVol

**Comment by syd711** [comment]
I think this is easily do-able - if I understood the ticket correctly.
The latest Studio versions uses nircmd.exe which also allows to set the system volume.
E.g.
https://superuser.com/questions/42039/change-windows-sound-volume-via-the-command-line

I could add a "Initial System Volume" preference which would then be executed on startup.
From what I read this is what you are doing (only with setvol), right?

**Comment by Ltek** [comment]
> I think this is easily do-able - if I understood the ticket correctly. The latest Studio versions uses nircmd.exe which also allows to set the system volume. E.g. https://superuser.com/questions/42039/change-windows-sound-volume-via-the-command-line
> 
> I could add a "Initial System Volume" preference which would then be executed on startup. From what I read this is what you are doing (only with setvol), right?

Yes, anything that can set the system volume -before- PinVol loads will work... we just need to make sure the "baseline" volume is set since PinVol doesnt do it.

**Comment by syd711** [comment]
You'll find a new setting sot allows to set the initial system volume before PinVol is started.
Fixed with 2.20.0.
