### ISSUE TITLE
[Feature Request] Score Cards... Set 'default' screen for Templates

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#221]
Please have the Templates save a background default -- and open/show that default when you select a table. When opening High Score Card section it defaults to Popper "Backglass". Each Template may have a different need... all of mine, as you know, need to use Popper "Menu" (aka FullDMD)

![image](https://github.com/syd711/vpin-studio/assets/1626802/250406d9-6e14-42f6-8a9a-ade24027ce85)

**Comment by syd711** [comment]
I just retested this. It is supposed to remember the latest screen selection. For me, it sticks to the selected screen, everytime I open the Studio. So for you it switches back to "Backglass" after restart?

**Comment by Ltek** [comment]
yes it does...

![image](https://github.com/syd711/vpin-studio/assets/1626802/612c789b-2259-45e2-aebe-3c368153f2dc)

**Comment by syd711** [comment]
Fixed with 2.20.3
