### ISSUE TITLE
[Feature Request] Extract media from B2S

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#224]
Would be cool to have VPS open a B2S and easily extract/save the media... a lot of good images/videos in those!

**Comment by Ltek** [comment]
that's what I'm thinking... since you already read the file. I dont know if there is a way to have it export the backglass (with the blinking lights, etc) as a video... I dont know B2S, barely looked at the Designer app but could not find it.

**Comment by syd711** [comment]
Released with 2.18.0
