### ISSUE TITLE
[Feature Request] Support media management for other emulators

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#225]
> swampyone. 
> Any chance of adding future pinball/fx3/fx, don't need full support, but would be super great, to manage their media remotely through vpin studio server rather than having to remote in and use the popper one.

If limited to the media management, it might a doable with reasonable effort.

**Comment by zestef** [comment]
+1 on this one for the basic management feature (no advanced feature needed).

**Comment by syd711** [comment]
Released with 2.18.0
