### ISSUE TITLE
[Feature Request] Drag-n-Drop file for File Uploads

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#227]
Would be nice to drag-n-drop the file for these dialogs...

![image](https://github.com/syd711/vpin-studio/assets/1626802/1893bfd1-ea28-43d8-8799-a61ba2623eed)

![image](https://github.com/syd711/vpin-studio/assets/1626802/994d9ae6-b303-4a48-9d11-0364004c7cb5)

**Comment by syd711** [comment]
Fixed with 2.20.0
Including drops out of 7z.

**Comment by Ltek** [comment]
was hoping for drag-n0drop for all file types. opened a new more specific FR here... https://github.com/syd711/vpin-studio/issues/276
