### ISSUE TITLE
[Feature Request]  High Score Card templates : Set number of scores on the card

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#231]
Prior to 2.18 the cards only showed 3 high scores, which was perfect to fit into a FullDMD window for a FullDMD Video. In recent versions I'm now seeing more than 3 scores. Would like to set/limit the # of scores shown by template.

**Comment by syd711** [comment]
2.18.2

**Comment by Ltek** [comment]
saweeet!
