### ISSUE TITLE
[Bug] High Score Cards : Background Preview stops after editing and saving a template

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#232]
Repro: Edit and save a template. Screen will refresh; preview goes blank. Preview will not show until you change tables in the left-side list

![image](https://github.com/syd711/vpin-studio/assets/1626802/e440bd9b-1450-4787-adf9-dc43a3352c6a)

**Comment by Ltek** [comment]
while fixing this maybe just move the 'preview' window to be an underlay for the larger display of the card, with an on/off checkbox. Not sure we need a small, separate preview and having it as an underlay will help with text/canvas positioning anyway.

**Comment by syd711** [comment]
This duplicates https://github.com/syd711/vpin-studio/issues/203 then, right?

**Comment by Ltek** [comment]
yup :)

**Comment by syd711** [comment]
Fixed with 2.18.2
