### ISSUE TITLE
[Feature Request] Provide Validator for Outdated Recordings

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#233]
> abhcoide 
> Would it be possible to compare the date of the direct2bs backglass files to the date of their Backglass counterpart in Popper media? And in circumstances where the date/time is newer in the tables directory it flags that you need to re-cord fresh media?
> Same could be done with Tables. 
> The relevance is that if you update your backglass or table to a new version or author, the media you’ve previously recorded in popper is outdated. 
> You could have it similar to the VPS updates maybe?   Maybe a settings where you could toggle which media you care about (backglass, playfield, topper, full dmd, dmd) like for me I only record backglass and playfield. 

E.g. when the video provided for a screen is older than the uploaded backglass for other media, the Popper screen recording is outdated.

**Comment by Ltek** [comment]
if you do this please make this disabled by default. 

- Many like myself do not use D2B recordings for Popper.
- I dont want a notification every time I update a table VPX file as most of the time they are nearly or completely identical to the prior table so I dont record a new one
- if I do change a table that is dramatically different, I know it and can go record it a few seconds after copying it in. I dont need to be reminded of the 1 or 2 (at most) tables I need to record.

**Comment by syd711** [comment]
Fixed with 2.20.0.
Note that I can not disable new validators by default.
But I added a gear icon to the validator settings so that validators can be disabled more easily.
