### ISSUE TITLE
[Feature Request] Asset Manager : auto-preview when selecting/clicking item

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#234]
Would be less clicks, and easier on my wrist ;-)  to single-click and item to show the preview Not sure why we need double-click or have the Preview button at all?

![image](https://github.com/syd711/vpin-studio/assets/1626802/d40068db-9f67-4172-ac05-d91acbd82c9a)

**Comment by syd711** [comment]
Good point. I just copied the Popper behaviour there without thinking. But it feels like an unnecessary hassle.

**Comment by syd711** [comment]
Solved, 2.18.3
