### ISSUE TITLE
[Feature request] High Score Card : link to settings in High Score area

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#235]
button in menu to quickly jump to the Settings would be nice.  

![image](https://github.com/syd711/vpin-studio/assets/1626802/abbd5a15-46bd-4998-8c02-4df6c69fe26f)

**Comment by syd711** [comment]
I'm not a 100% sure which settings do you mean. Another button to open the template editor for the selected table?

**Comment by Ltek** [comment]
yes, a button that directly goes to the settings instead of multiple clicks out to get there.

**Comment by syd711** [comment]
Solved, 2.18.3
