### ISSUE TITLE
[Bug] Popper Media - 'Gear icon' opens Setting page with error

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#236]
clicking on the 'gear icon' 

![image](https://github.com/syd711/vpin-studio/assets/1626802/f4c4201a-c94a-40c9-a3e5-cca3d306ad62)

takes you to Settings with this error...

![image](https://github.com/syd711/vpin-studio/assets/1626802/43201cf9-36c1-4fc4-adf1-b88948d4b29b)

**Comment by syd711** [comment]
Ah, thanks!

**Comment by syd711** [comment]
Solved, 2.18.3
