### ISSUE TITLE
[Feature Request] High Score Cards : enter HEX for Canvas color

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#237]
While creating card canvas, I need to use a color picker to find the correct color but cant find a way to the HEX for the canvas?
side note: maybe you have a color picker library to build in... not important just a thought.

![image](https://github.com/syd711/vpin-studio/assets/1626802/03dd950f-6995-4453-809f-8579fd1957bc)

**Comment by syd711** [comment]
I've hidden the link to custom colors, because there have been focus issues with the build in color picker dialog.
I just retested this and while the dialog behaves strange, it does what it is intended to do, so I'll re-enable it.

**Comment by syd711** [comment]
Solved, 2.18.3
