### ISSUE TITLE
[Bug] Asset Manager : using Arrows does not refresh Asset Mgr screens

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#238]
Asset Manager arrows changes the selected table in the main window - and the table in the Asset Manager (upper left drop-down), but none of the media in the Asset Manager window changes/refreshes to be the named table. Attached screenshot show the Loading screens are not the same, for example.

Would love to see you get rid of the separate Asset Manager window completely and move the functionality fully into a slide-out. The asset mgr window also lacks some functions (no drag-n-drop). As posted here... https://github.com/syd711/vpin-studio/issues/163

![image](https://github.com/syd711/vpin-studio/assets/1626802/0db096d9-3b19-4a4e-ad81-bd5e653c697a)

**Comment by syd711** [comment]
Thanks for reporting the bug.
Note that the asset-manager-view also supports drag-and-drop. You can drop the assets directly on the screens.

![image](https://github.com/syd711/vpin-studio/assets/1169826/1b493e11-5e8d-406b-9cab-24d663c8133e)
