### ISSUE TITLE
VPin-Studio.sh still not executable

### ISSUE THREAD

**Issue by francisdb** [syd711/vpin-studio#24]
#16 fixed the newlines but not the executable flag

Probably there is no way to keep this flag when cloning in windows?

**Comment by francisdb** [comment]
looking at https://github.com/syd711/vpin-studio/blob/553379ca2271f879353140422974fe1a4192da9f/vpin-studio-ui/pom.xml#L491-L502

I now understand why `unzip` does not see this file as a zip, it's actually a 7-zip file with `zip` instead of `7z` extension.

I wonder if there's a way to let 7z know it should apply the executable flag.

**Comment by syd711** [comment]
So 7z is the reason the flag gets lost? It wouldn't get lost when "regular" zip/unzip is used?

**Comment by francisdb** [comment]
> So 7z is the reason the flag gets lost? It wouldn't get lost when "regular" zip/unzip is used?

Don't think so, I guess windows has no way to keep this flag so it's already lost at clone. Maybe some more standard maven plugin can do the zipping and has an option to set executable flag?

On a side note i would make sure the file is a true zip.

**Comment by syd711** [comment]
Finally, I switched to "zip" so that this extraction error message is gone :)
Regarding the executable flag: For me its just a corner case I don't want to focus on too much. So I'll close this ticket for now.
