### ISSUE TITLE
[Feature Request] Add DND Support from Archives

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#243]
> spaceangel6998 — Today at 8:06 AM
Would it be possible to drag and drop media from a zip archive, as most of the media downloaded is archived.

Should be possible with the apache common compress library.

**Comment by Ltek** [comment]
this would definitely save a step of opening the archive (RAR/ZIP/7Z) and dragging the file into VPS's UI.  Would be needed for the Universal Uploader feature too
