### ISSUE TITLE
Keep Existing VPX filenames is ignored if updated table is in a zip/rar

### ISSUE THREAD

**Issue by oper8r00** [syd711/vpin-studio#246]
**Describe the bug**
When using **Update and Replace mode**, "keep existing VPX filenames" are ignored if file is in a zip/rar. 

**To Reproduce**
Pre-reqs: 
- Have a properly named table. Such as "RollerCoaster Tycoon (Stern 2002).vpx"
- Have a zipped/rar'd table update that contains a file "RollerCoster Tycoon (Stern 2002) VPW 1.1.vpx" (note: this is an example)

1. Go to VPX Table upload
2. Select **Upload and Replace**, ensure all three sub-options are selected. 
3. Click _Select _File_ and browse for your newly downloaded table update
4. Select the zip/rar file which contains your table update
5. Click _Upload_
6. On completion, VP Studio will now give a scan error message that backglass / pup is missing. On further investigation, you will find the file name is based on what is in the zip/rar.

**Expected behavior**
When using the option, the file name of the VPX file should be remain same as the existing as the existing table being updated. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11

**Additional context**
(Also minor text error with word "insteaf" for If enabled, the display name of the table is kept _insteaf._..

**Comment by syd711** [comment]
Thanks for reporting. Yes, I'm aware of this bug but forgot to write a ticket for this.
2.19.0 will come with a re-implementation of uploads and drag-n drop features where I will also take care of this.

**Comment by syd711** [comment]
Fixed with 2.20.0.
