### ISSUE TITLE
[Bug 2.18.4] Score Card preview no longer fits window when using Popper Scale setting

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#247]
I just changed to use the Popper Scale Setting... preview window no longer happy. Kill that small window already, put the image/video behind the editor ;-)

![image](https://github.com/syd711/vpin-studio/assets/1626802/5b6ba8f1-64e6-4e8e-b88b-31ce031c29a8)

**Comment by Ltek** [comment]
pretty please :)

waiting for the video/image to display as the background before I make the how-to video

**Comment by syd711** [comment]
On it, now that the uploader is out, I'm full on maintenance mode.

**Comment by syd711** [comment]
https://github.com/syd711/vpin-studio/issues/244 has been fixed, which was kind of a blocker this stuff. So there is progress here and I'll continue with the related highscore tickets of yours.

**Comment by Ltek** [comment]
not fixed in 2.20.2

![image](https://github.com/syd711/vpin-studio/assets/1626802/1a0e0265-578b-42d3-a40a-46e929f16b8c)

**Comment by syd711** [comment]
The screen is gone, so I close this issue.
Fixed with 2.20.3
