### ISSUE TITLE
[Feature Request] Overwrite the key binding for popper and utilitze them for "Pause screen"

### ISSUE THREAD

**Issue by Kongedam** [syd711/vpin-studio#249]
Popper has a key binding for showing asset for Info / Help screen
I would like Vpin Studio to overwrite these bindings, so im able to use the pause screen directly in the pinup popper menu, same way as I don it when the table is loaded. (Show, tutorial on back glass and Highscore on dmd)

This would help in serveral ways:
You do not need upload tutorials to the pinup popper media libary. (save space and time)
Pinup popper often miss the sound from the video, Im sure this could be fixed if Vpin Server is controlling it

**Comment by Ltek** [comment]
If by 'overwrite' you mean intercept and block Popper's keys -- that is not a good solution if it was possible but its probably not possible anyway.  
VPS would need a way to intercept and proxy all Popper key commands.
To do what you want, you can change the Popper key to key of your choice and/or use a key mapper (like Joy2Key) to make it send whatever command you want when any given key is pressed.

**Comment by syd711** [comment]
It was a user suggestion and I have not thought about it yet. But yes, your description fits.

**Comment by Kongedam** [comment]
Yes
I just want to be able to start the pausescreen direct from popper.

This way i can see the tutorial before i start a table and I do not need to download it as it would be streamed.

There are also sound problems with popper and tutorials as it mutes the sound when launching info/help assets.

The biggest problem for vpin studio is to see what table in popper is picked in popper and start the right  it tutorial. I do not know if its possible at all

**Comment by syd711** [comment]
On hold until the controller support has been released.

**Comment by syd711** [comment]
> The biggest problem for vpin studio is to see what table in popper is picked in popper and start the right it tutorial. I do not know if its possible at all

Since this is kept in memory, I see no way to offer a solution here.
