### ISSUE TITLE
VPS client and server should not use different database copies

### ISSUE THREAD

**Issue by ThePrintz** [syd711/vpin-studio#255]
VPS updates no longer showing.
Something broke the update indicators. Everything is selected in preferences but no markers in Studio.
<img width="655" alt="Skjermbilde 2024-05-14 kl  19 19 09" src="https://github.com/syd711/vpin-studio/assets/71230140/4645943b-1d17-4025-9994-2996a97f4ac3">

**Comment by syd711** [comment]
Right, I see the bot posted the updated so you should have a marker. I'll take a look this week.

**Comment by syd711** [comment]
All options in the UI settings are enabled for this?
I just tried to reproduce if there are issues, but the RollerCoaster update did work and I see the indicator.
Are there any errors in the log saying something about VPS?

**Comment by ThePrintz** [comment]
Hi, I was hoping the new matching system would fix this issue, but unfortunately no. I can not find out why...
Here I am sending you the log-files. Maybe you can find something. The log files are from a time I know there are updates. See also enclosed screen dump.
![Screenshot (7)](https://github.com/syd711/vpin-studio/assets/71230140/e0e0fe2d-47fb-4cef-bb1c-bc75985e8892)

[vpin-studio-logs.zip](https://github.com/syd711/vpin-studio/files/15408378/vpin-studio-logs.zip)

**Comment by syd711** [comment]
Thanks for the data, that helps. I'll take a look.

**Comment by syd711** [comment]
Do you leave your cabinet running? Was the cabinet restarted after the Leathal Weapon updates came out today? ~4pm Central European Time (CET)

**Comment by ThePrintz** [comment]
Hi. My cabinet runs 24/7. Only restart when absolutely necessary. At least 5 days since last restart. I exit out of pinup popper whenever I need to update something. Vpin Studio (not server) is manually opened and closes randomly when updating games. Hope this helps.

**Comment by ThePrintz** [comment]
I will try to restart the computer, but I have done all updates you have released (with server stop/start) without luck. Will post back as soon as cabinet restart.

**Comment by ThePrintz** [comment]
Just restarted, and still not working correctly. Is it a way to reset and rescan update/version status or is done everytime I scan the tables? 
Here is updated screenshot and logs
<img width="1254" alt="Skjermbilde 2024-05-23 kl  11 28 59" src="https://github.com/syd711/vpin-studio/assets/71230140/184b04b4-2662-4a9a-ab66-e8be0f711453">
[vpin-studio-logs (1).zip](https://github.com/syd711/vpin-studio/files/15414807/vpin-studio-logs.1.zip)

**Comment by syd711** [comment]
No, not yet. But at least now I am aware of this synchronization issue and can fix this. When fixing this, I will check again why the update flag is not set. I assume it's a side-affect of this. In any case: thank you for your feedback and provided data.

**Comment by ThePrintz** [comment]
Just at thought. Could this be a language issue. Maybe it has something to do with how different languages handle commas and full stops?

**Comment by syd711** [comment]
We have moved the VPS database completely to the server, so the client and server are always working on the same data.
We hope this fixes the issues and close this ticket for now.

Fixed with 2.20.1.
