### ISSUE TITLE
[Feature Request] Add FullDMD Info for Backglass Manager

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#256]
> leprinco — Today at 2:27 AM
> I'd like to see in one place if my backglasses are full dmd. Can a full dmd column be added in the backglass manager

![image](https://github.com/syd711/vpin-studio/assets/1169826/c76c576a-f59a-442d-be4f-4d0d5a395912)

**Comment by Ltek** [comment]
useful for sure

**Comment by syd711** [comment]
Fixed with 2.20.0.
