### ISSUE TITLE
[Feature Request] automatching improvements

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#258]
In order to improve automatching accuracy, following is proposed:
- first when table is already matched against VPS, system will control and confirm its accuracy
- if no match or matching not confirmed, a new matching is performed:
fuzzy match name + manufacturer + year and pick the first best match
version information are ignored
matching on name is case insentive, ignoring punctuation and misc transformation
best match are when table name follow convention : <name> (<manufacturer> <year>)
manufacturer like Bally/Midway, Original/TBA or Gottlied/Mylstar are considered same
a difference of 1 year degrades less the score than a difference of 2+ years

**Comment by syd711** [comment]
Fixed with 2.20.0.
