### ISSUE TITLE
Table count in table manager playlist view

### ISSUE THREAD

**Issue by spaceangel1970** [syd711/vpin-studio#265]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by spaceangel1970** [comment]
When selecting a playlist in table manager. Currently it shows the full table count rather than what the playlist contains.

**Comment by syd711** [comment]
Right, the label should be updated similar to filters.

**Comment by syd711** [comment]
Fixed with 2.20.0.
