### ISSUE TITLE
pinemhi window opens on backglass

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#272]
> AnthonyJS02 — Today at 2:35 AM
I noticed I have a small pinemhi window that shows up on the backglass. Is that something I should move somewhere else or turn off?

**Comment by leprinco** [comment]
I guess this is this window
![image](https://github.com/syd711/vpin-studio/assets/3083959/ad0f9143-4d78-42b7-b908-16763fb2ef9b)

can be ade shown / hidden by pressing L key

**Comment by syd711** [comment]
Not a bug
