### ISSUE TITLE
[Bug] PuP Packs not detecting / validating correctly

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#275]
In the Tables grid, many tables do not show a 'check' on the PUP column when they do have a PuP..

![image](https://github.com/syd711/vpin-studio/assets/1626802/d770791a-45a7-4745-a831-6f2046daf6e3)

**Comment by syd711** [comment]
I just tested this with TheMatrix, but I can not reproduce the issue. Could you provide the logs? Can you see anything that the affected tables have in common?

**Comment by Ltek** [comment]
I take it you repro'd?  It happens on many table for me

**Comment by syd711** [comment]
Fixed with 2.20.2
