### ISSUE TITLE
[Feature Request] Drag-n-Drop for non-media items: PUPs, ROMs, etc

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#276]
drag-n-drop doesnt work for: Tables, PUP packs, etc... only media. would be nice to not need to 'browse' every time. 

![image](https://github.com/syd711/vpin-studio/assets/1626802/10e98832-8acb-438f-8fbd-7994ac5bcaee)
![image](https://github.com/syd711/vpin-studio/assets/1626802/ef58ea77-d6e3-441d-89f9-3247b4e81d05)

**Comment by syd711** [comment]
Did you drop VPX or zip files into the table overview area? (as shown in [the YouTube video](https://www.youtube.com/watch?v=yWWlHm8iL5A&t=5s&ab_channel=VPinStudio) ?) 
I've not tested with a NAS, but I don't think it will make difference.

The PUP pack dialog here is from version 2.20.0 while the screenshot of the table upload dialog is from version 2.19.0. So I'm not sure if something is mixed up here.

**Comment by Ltek** [comment]
my clients shows 2.20 in the header

**Comment by syd711** [comment]
> I'm on 2.20 (I used an old screenshot). Opening the Upload dialog does not allow d-n-d, just shows a red circle with slash.
Ah, ok. I opened a separate ticket for this:
https://github.com/syd711/vpin-studio/issues/277

**Comment by syd711** [comment]
> I'd suggest looking at consolidating all into a single method - remove the old upload button options and have a dedicated menu item / landing space, where a user drags the item to -- then have it always open the modal dialog to ask the user what they want to do.

This is what the upload already does. It seems emphasizing the current table selection like the way I do it currently is confusing.
The selected table is only shown that **if** the dropped file is table related (e.g. a backglass) it is uploaded for the selected table. So the dropzone can remain where it is, but I should somehow visualize this better.
The upload menu will remain for a better accessibility. But for mixed asset bundles (e.g. backglass and popper media) a separate dialog can be provided.

> also, when drag-n-drop a PUP ZIP to the main window, it does not ask the user if they want to upload to the highlighted table, or to a different table... like VPX does. Could this cause an issue that if the user doesnt have correct table highlighted or will it not matter since the PUP name will be whatever is in the ZIP?

Yes, the path inside the archive determines where the PUP pack is uploaded. The selected table is not relevant for this. Same for ALTSound bundles.

**Comment by syd711** [comment]
I've added the dnd option for the dialog and changed the table area dnd-overlay so that the current table info is not shown anymore which should lead to less confusing.
The corresponding upload dialogs should show the actual upload details.

Solved with 2.20.1
