### ISSUE TITLE
[Bug] B2S preview not working

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#278]
using 2.20.0

I dont use a lot of B2S but installed one today and noticed this...

link to B2S used... https://vpuniverse.com/files/file/20332-pirates-life-100-the-revenge-of-cecil-hoggleston-hybrid-table/?tab=reviews&sort=newest#review-22454

VPS shows..
![image](https://github.com/syd711/vpin-studio/assets/1626802/d476f49d-6ee9-4b2d-a2c1-cb7788fff215)

actual B2S...
![image](https://github.com/syd711/vpin-studio/assets/1626802/d36cef6e-0982-4b62-b8bc-420a5caf1db4)

**Comment by leprinco** [comment]
hi, I tried to reproduce, here is what I get :
![image](https://github.com/syd711/vpin-studio/assets/3083959/cfb7661e-c35e-4be3-9f09-0d0de40de350)
![image](https://github.com/syd711/vpin-studio/assets/3083959/328884ad-b7ad-4daa-b0b8-46581096a690)
can you please try again and confirm us ? thanks a lot

**Comment by Ltek** [comment]
yup now working after exiting and restarting VPS.. odd!

**Comment by syd711** [comment]
Nice! I'll close the ticket then.
