### ISSUE TITLE
[Feature Request] Full integration of Virtual Pinball Spreadsheet (virtualpinballspreadsheet.github.io)

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#280]
<low priority ask>

VPS integrations for Virtual Pinball Spreadsheet (virtualpinballspreadsheet.github.io)

Ideas...

1. Separate VPS tab to view/use web page   *easiest
2. VPS can directly download any item posted on the spreadsheet; homed on vpforums, or vpuniverse
VPS would have two options: "Download, Storage, and Install to vPin" and "Download for Storage" (when you want to not install)

Example for 2:

- spreadsheet page has... https://www.vpforums.org/index.php?app=downloads&showfile=17672

- actual DL link is... https://www.vpforums.org/index.php?app=downloads&module=display&section=download&do=confirm_download&hash=3f88f166d57711f640aef4cb9d4e53c9

In VPS, user would have a "Storage" location set. For me, I use \Pinball\Storage\<table name> to store all my table items (VPX, media, B2S, etc)

Actions would look like this....
User selected "Download and Install"
VPS would download the files, place them in the 'Storage" folder (creating a new folder name if needed) and then upload to the users vPin
User would have default settings, and also have the option to select something else... using the existing modal dialog that shows when uploading anything now.

**Comment by syd711** [comment]
So much I like the idea of simplifying the whole table download and asset management stuff, I have to close this ticket as a won't fix. I don't want to by-pass the download options of these websites since it's likely to cause troubles with the owners. 

When starting with the Studio I had a similar discussion with Dazz, the admin of VPU. He imagined something like a Steam client for VPU, I even build a prototype back then. But we did not follow up on this since.

**Comment by Ltek** [comment]
> So much I like the idea of simplifying the whole table download and asset management stuff, I have to close this ticket as a won't fix. I don't want to by-pass the download options of these websites since it's likely to cause troubles with the owners.
> 
> When starting with the Studio I had a similar discussion with Dazz, the admin of VPU. He imagined something like a Steam client for VPU, I even build a prototype back then. But we did not follow up on this since.

Actually not suggesting bypassing any of the sites. VPU would embed them into a VPS window and then intercept DL's to automatically store and process (upload) them

example...
a VPS tab with the spreadsheet on the left side, selecting a table opens the spreadsheet popup as normal.
Then click on the actual table (as in the screenshot), changes the right-side of the VPS window to open the VPU location.
Where we can then download the table, pup, etc.

![image](https://github.com/syd711/vpin-studio/assets/1626802/46320e25-de78-4d4e-991e-b3902036a6d0)

then clicking on the "Download" button shows you the same inset VPU opens, like this...

![image](https://github.com/syd711/vpin-studio/assets/1626802/3326cfb4-45b4-429b-a136-68ee9e66ef08)

... BUT when you actually do the download... VPS does some magic.

VPS will directly download (instead of the browser itself) that item and present the user with two options: "Download, Storage, and Install to vPin" and "Download for Storage" (when you want to not install)

This might require an API call to VPU, not sure if you can intercept a browser call or not?
