### ISSUE TITLE
[Bug] dot in file extension being removed when uploading altcolor

### ISSUE THREAD

**Issue by dmccombs** [syd711/vpin-studio#282]
**Describe the bug**
When uploading a `.cRZ` altcolor file for a table in VPin Studio 2.20.0, the `.` in the extension is getting removed causing `filename.cRZ` to be uploaded to the vpin as `filenamecRZ` which of course fails to be found and loaded. Renaming the file on the vpin allows it to work, but causes VPin Studio to say the ALT Color is missing, looking for the filename without the `.`.

**To Reproduce**
1. Run the VPin Studio service on the vpin table, connect with a client
2. Select a VPX table from the list, click ALT Color in the pane on the right
3. Click Upload and upload a `.cRZ` file
4. See it listed as `filenamecRZ` without the `.` before the file extension
5. Play the vpin table and see there is no colorized DMD
6. Rename the file on the vpin to add the `.`
7. Game works with colorized DMD
8. Look at ALT Color for the table in VPin Studio and see it now says the file is missing

**Expected behavior**
Uploading the file should retain the `.` before the file extension, and VPin Studio should be looking for that file to validate.

**Screenshots**
![shot-2024-06-03_10-24-37](https://github.com/syd711/vpin-studio/assets/403277/787dbacd-faf3-49fa-ace5-ec6c357088ca)

**Desktop (please complete the following information):**
 - VPin OS: Windows 10
 - Client OS: Linux
 - Version 2.20.0 on both

**Additional context**
This is my first time using VPin Studio, so I'm not sure if this was a problem in previous versions as well or not.

**Comment by syd711** [comment]
Yep, noted. Fix is on its way!

**Comment by syd711** [comment]
Fixed with 2.20.1

**Comment by dmccombs** [comment]
@syd711 thanks for the ultra quick release - I confirmed that did the trick!
