### ISSUE TITLE
[Feature Request] Support PinballX

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#289]
The services accessing Popper are quite good encapsulated.
Let's open the Studio for other frontends like PinballX.

**Comment by Ltek** [comment]
I hope optimizing VPS for Popper and for VPX non-front-end users is your main focus. Looking into PinballX, PinballY, and Popper about 1.5 yrs ago showed me that Popper's user base is -at least- 10x the other two combined. I suspect its really more like 25x.

**Comment by syd711** [comment]
Based on a quick poll on Discord I would guess the same. 
Since I do/will use Popper on my cabinet, it is still the main focus for me. 
But even if there are not a lot of PinballX users, the separation will improve the overall architecture.

**Comment by syd711** [comment]
Delivered with 3.0.0
