### ISSUE TITLE
[Feature Request] B2S Indicator on Popper media screens

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#291]
Icon indicator on the Media screen showing when a B2S is installed for that table. Help users identify when they -do not- need to add Backglass and FullDMD media.

Change text from "No Media Found" to "No Media Needed, using B2S"

![image](https://github.com/syd711/vpin-studio/assets/1626802/683c056f-36ef-4328-a27b-6e860e490bc3)

**Comment by syd711** [comment]
These screens show only the Popper media that are shown on table selection.
The data, if a backglass/Full DMD is available should not be intermingled here.

**Comment by Ltek** [comment]
> These screens show only the Popper media that are shown on table selection. The data, if a backglass/Full DMD is available should not be intermingled here.

B2S indicator helps users identify when they **do not** need to add Backglass and FullDMD media... so today they see the "No media found" but may not remember every table and its config (I have 125 and dont remember).
this indicator reminds them "I dont need media for that since B2S is installed"

**Comment by syd711** [comment]
I can check if the backglass is available and has a DMD and I can add this information.
But I don't understand you last sentence:
> "I dont need media for that since B2S is installed"

When you scroll through the Popper menu, you want to see a video, e.g. of the backglass. Why is this not necessary when you have a backglass installed?

**Comment by Ltek** [comment]
3 possible scenarios...

B2S file exists AND Popper Media does not exist... studio B2S Indicator

reason: backglass WILL show since VPX will always use the B2S file if it exists

B2S file does not exist AND Popper Media does not exist... studio "No Media Found"

reason: no backglass exists, none will show so we should alert the user // VPX has no B2S to use, and no popper media exists

B2S file exists AND Popper Media exists... studio B2S Indicator -and- "Conflicting Media Found"

reason: backglass (B2S) will show once table loads (VPX will always use the B2S file if it exists) and so popper media is redundant and will not show during game play. Popper media may show for a second or so until the B2S is loaded.

**Comment by syd711** [comment]
> B2S file exists AND Popper Media exists... studio B2S Indicator -and- "Conflicting Media Found"

Ah, I think this is the point which confused me. For me, this is not a conflict but the "normal" setup. I have Popper backglass videos for all my tables so that the screen shows something during the T-ARC selection and when the table is loaded.

So I would keep the info label a bit more neutral, here is the draft:

![image](https://github.com/syd711/vpin-studio/assets/1169826/867e30a2-f6a1-4cd6-b3ad-2725892b33d6)

**Comment by Ltek** [comment]
> > B2S file exists AND Popper Media exists... studio B2S Indicator -and- "Conflicting Media Found"
> 
> Ah, I think this is the point which confused me. For me, this is not a conflict but the "normal" setup. I have Popper backglass videos for all my tables so that the screen shows something during the T-ARC selection and when the table is loaded.
> 
> So I would keep the info label a bit more neutral, here is the draft:

I forgot about that scenario -- I do that also!  Yeah, so maybe dont put the text at all, just overlay the B2S Indicator icon so people know there is both Popper & B2S.

**Comment by syd711** [comment]
Delivered with 3.0.0
