### ISSUE TITLE
[Feature Request] vPin Highscore Card indicator on Popper media screen

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#292]
adds an indicator icon to let users know there is a Highscore Card enabled on the given popper media type (screen). Can help identify if/when a card is missing also

![image](https://github.com/syd711/vpin-studio/assets/1626802/b50b3843-9686-4426-9374-f70b5f20ceeb)

**Comment by syd711** [comment]
Yes, makes sense to highlight the target screen for the cards.

**Comment by syd711** [comment]
Fixed with 2.21.1
Added plain indicator for the screen only.
