### ISSUE TITLE
Stuck on splash screen

### ISSUE THREAD

**Issue by Meshuggah70** [syd711/vpin-studio#295]
I have had it on a previous update to never go past the splash screen. I eventually figured out how to fix it.. I have been through many updates no problem. today I let it update to 2.20.2 and when I open it it hangs on the splash screen as it did in the past.. I cannot remember what I did last time but do remember it was kind of simple.. I have tried re installing. re starting. task manager etc.  any ideas as im at a loss for the "simple fix" I found last time to get it to launch.. I should have written it down what I did...

**Comment by syd711** [comment]
Can you append all log files from the installation folder here?

**Comment by Meshuggah70** [comment]
[vpin-studio-ui.log](https://github.com/user-attachments/files/15753210/vpin-studio-ui.log)
[vpin-studio-server-vps-updates.log](https://github.com/user-attachments/files/15753211/vpin-studio-server-vps-updates.log)
[vpin-studio-server.log](https://github.com/user-attachments/files/15753212/vpin-studio-server.log)
[vpin-studio-server.2024-06-08.log](https://github.com/user-attachments/files/15753213/vpin-studio-server.2024-06-08.log)

**Comment by syd711** [comment]
The server is still running on version 2.18.4.
I think the reason for this is the windows defender blocking the .exe file.
See also:  
https://github.com/syd711/vpin-studio/wiki/Troubleshooting#the-server-is-causing-high-cpu-usage-by-windows-defender

**Comment by Meshuggah70** [comment]
Thanks so much!. I did a folder exception and all is fine after a reinstall
and the server is now up to date

**Comment by syd711** [comment]
Awesome! I close the ticket then.
