### ISSUE TITLE
[Feature Request] Provide "Center" Option for Cards

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#297]
Provide an option for the score card generator to center the score list.

**Comment by Ltek** [comment]
Might be interesting to have settings for...

- horizonal center
- vertical center
- vertical top 1/3
- vertical top 1/4
- vertical bottom 1/3
- vertical bottom 1/4

not sure if that is easy?

**Comment by Ltek** [comment]
I'd think best for all users (an likley easiest for you?) is center everything/all that is actually being rendered based on the users template settings. 

Entire set of text or just the highscore list or wheel w/ highscore list, etc

With a few exception (Banzai Run and a few others) my cards are all...

1. Top 3 High Scores
2. Wheel with Top 3 High Scores

**Comment by Ltek** [comment]
bump :)

**Comment by syd711** [comment]
At least the score centering will be improved through https://github.com/syd711/vpin-studio/issues/408

**Comment by syd711** [comment]
The horizontal centering has been added.
For the vertical centering it is a bit more tricky. It would be appled for the score if not title and table name is set.

I see the vertical percentage option as a won't fix, since these are only applied once and most likely adjusted manually after that.

**Comment by Ltek** [comment]
The horizonal work awesome!  Might want to note in the docs that people need to go back into all templates and zero-out the horizontal numbers, otherwise its all messed up.

I get what you are saying about the vert centering. That seems perfect.
