### ISSUE TITLE
High Score Cards On Specific Tables

### ISSUE THREAD

**Issue by jasoncross** [syd711/vpin-studio#298]
I built my cabinet with screens for instruction and info cards, but have found about 40% of the tables I play don't have info cards.  I'd like to use the High Score cards for these, but I don't want to on all tables as some I like having the original info cards.  It would be great if there was a way to enable the high score card generation on just specific tables.

**Comment by leprinco** [comment]
There are many sites referencing instruction cards like below
https://arcarc.xmission.com/Pinball/Instruction%20%20Cards/

Issue is that each time, it is images. It would be good to have a site that reference them in text format, in multi language.. vpin-studio could then generate a nice one

**Comment by jasoncross** [comment]
@leprinco Sounds like a different feature request.  I was referring to info cards.  But it would be nice if vpin-studio could be leveraged to auto-create missing assets like info cards, instructions, etc.

**Comment by syd711** [comment]
Why not use the Other2 screen? Usually this one is not utilized for anything else.

**Comment by jasoncross** [comment]
> Why not use the Other2 screen? Usually this one is not utilized for anything else.

I wonder if I can set the Other2 to the same display as my GameInfo screen and only show it if the GameInfo media is missing?

**Comment by leprinco** [comment]
> @leprinco Sounds like a different feature request. I was referring to info cards. But it would be nice if vpin-studio could be leveraged to auto-create missing assets like info cards, instructions, etc.

yes sorry, my bad, I read too fast  :)

**Comment by syd711** [comment]
I think you can do this by just configuring Popper this way.
![image](https://github.com/syd711/vpin-studio/assets/1169826/e4f7c466-11bb-4440-94f2-b99b84c78ed4)

- enable transparency for the Other2 and GameInfo screen
- position them on the same location
- remove the default assets for these screens, maybe replace them with a transparent PNG
- play around with ForcePop/Show/on

When highscore card and game info card are shown, you can position the game info above the highscore card this way.
If no card is available, the transparency or missing Popper image will not be shown is is transparent and you will see the highscore card.

I have not tested this, but I'm sure it'll work this way.

**Comment by jasoncross** [comment]
> * remove the default assets for these screens, maybe replace them with a transparent PNG

I will give it a try!  Where can I find the default assets so I can replace them?

**Comment by syd711** [comment]
Here are the default assets for all emulators and screens:
C:\vPinball\PinUPSystem\POPMedia\Default

It looks to me you don't have to replace anything there, just try to configure the screens accordingly.

**Comment by jasoncross** [comment]
So I enabled transparency on the InfoCard layer.  Interesting impact.

* Some of the cards still fail back to the default popper image (with the lightning bolts)
* Some where I have info cards are interpreting part of the image (black?) as transparent and showing the Other2 layer "in between" parts of the info card image.

**Comment by syd711** [comment]
> Some where I have info cards are interpreting part of the image (black?) as transparent and showing the Other2 layer "in between" parts of the info card image.

What about changing the order, putting the info cards in the background (without transparency) and the highscore cards (Other2) in the foreground (with transparency)?

**Comment by Ltek** [comment]
@syd711 if I understand the FR correctly, I think the solution would be to have a per-table setting in VPS "disable high score card" ... and thus VPS does not create an image for it?

**Comment by syd711** [comment]
Yes, I had hoped to solve this with a better screen setup, but it doesn't seem to work out.
So I'll see where I can add a flag for this.

**Comment by syd711** [comment]
Fixed with 3.0.6

**Comment by Ltek** [comment]
> Fixed with 3.0.6

WHAT! ... ok, I'm testing this later. wahoo

**Comment by syd711** [comment]
![image](https://github.com/user-attachments/assets/cca19206-edb1-498d-9d8d-fd146814759c)

**Comment by Ltek** [comment]
will this save a unique layout card for each card - without create a new template?

**Comment by syd711** [comment]
No, that was your other ticket. This ticket only solved enabling/disabling the card generation for specific tables.
