### ISSUE TITLE
Rom alias seen as missing rom

### ISSUE THREAD

**Issue by francisdb** [syd711/vpin-studio#3]
![image](https://github.com/syd711/vpin-studio/assets/161305/2a06e36f-be3f-4624-891e-eb4f6b737621)

![image](https://github.com/syd711/vpin-studio/assets/161305/2d1f5682-cc3d-440d-918e-3d7956b1e48c)

**Comment by syd711** [comment]
Yes, found the bug too last week. Already fixed and comes with the next update (including an alias mapping dialog).

**Comment by syd711** [comment]
Fixed with 1.3.4
