### ISSUE TITLE
[Feature Request] VPS table screen, hide tables that are not installed

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#300]
Would be nice to have a radio button in the menu  of this tab to "Show only Installed Tables'

Then having the Date and sorting by that would make it really quick/easy to use that screen. 

![image](https://github.com/syd711/vpin-studio/assets/1626802/e99ae93e-e289-4c0c-a2c8-256153b1d35b)

**Comment by syd711** [comment]
Released with 2.21.0
