### ISSUE TITLE
[Feature Request] Highscore preview inset mini-window on/off

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#301]
The current 'card' button opens a new window shwoing the score format but no background... what about changing that to be a button to show a small inset window right in the tab itself? so that 'card' button become a 'preview' button, turning on/off the preview?

![image](https://github.com/syd711/vpin-studio/assets/1626802/3f93cf04-0599-445e-8b1f-cbceaa11401a)

**Comment by syd711** [comment]
Feels a bit too crowded there for my taste. Personally I'm mostly interested in the RAW score there.
We could put it below and larger, but it will be out of the view port.

**Comment by Ltek** [comment]
Its really just for a quick look-see to make sure the set template works/aligns as needed in case the user changes the video... alternatively, and prob even better, is to put the score overlay in the existing Popper section?

**Comment by syd711** [comment]
> Its really just for a quick look-see to make sure the set template works/aligns as needed in case the user changes the video...

So I assume in you case you not only want to see the image that is generated for the score card, but also the full overlay preview mode with the video running in the background.

**Comment by Ltek** [comment]
> > Its really just for a quick look-see to make sure the set template works/aligns as needed in case the user changes the video...
> 
> So I assume in you case you not only want to see the image that is generated for the score card, but also the full overlay preview mode with the video running in the background.

We dont need the video running.  2 reasons to have the image showing and having it on this screen makes validation far faster and easier vs switching to High Score card / template editor screen since we'll be on the given table at that time.

1. make sure the image is the image we want and think is set (and make sure one is set)
2. make sure the template is correctly set (aligned to the image)

**Comment by syd711** [comment]
Delivered with 3.0.0
I've add image below the raw score.
