### ISSUE TITLE
[Bug] Fix video playback

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#302]
I'm seeing this on/off... not sure why? the MP4 1080p videos play fine in VLC

![image](https://github.com/syd711/vpin-studio/assets/1626802/1770a212-71be-41a7-ae30-5ed54b264a6c)

![image](https://github.com/syd711/vpin-studio/assets/1626802/bb10531a-0b9f-474f-8e3a-f27e9f36ae16)

**Comment by syd711** [comment]
I assume it's only the "usual" hickup that somestimes the videos are not played (still have no solution for this, even a new Java version did not fix this issue). Does the video play after a restart of the Studio?

**Comment by syd711** [comment]
I assume this issue can be closed?

**Comment by Ltek** [comment]
It still happens sometimes, I have been ignoring it.

**Comment by syd711** [comment]
It's a known issue I wasn't been able to fix yet, trying several workaround and tried the newest Java version. The player sometimes crashes and it seems there is nothing I can do about this. I leave this ticket open for now. Maybe I find a solution in the original Java sources.

**Comment by Ltek** [comment]
Java bug, unfixable right now.
