### ISSUE TITLE
[Feature Requests] Play video on Backglass / FullDMD

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#306]
I see table experience gaps in these situations...

1. users/cabinets who do not use PinUp Popper (no PUP Player)
2. most tables have B2S backglass files (B2S) that do not include FullDMD
3. B2S doesnt run videos, at all... so far less fun; no attract videos, fun FullDMD videos, etc

B2S is made for, and great for, traditional backglasses : exact reproductions or originals; but lacks the enjoyment videos bring. 
Plus, most of the B2S do not have screens built in for FullDMD; which are quickly taking front stage on most cabinets.

The only way to get a video on a Backglass or FullDMD is to use PUP Player (from Popper)

the Idea... VPS controls (starts/stops) the videos.

This would allow use of attract videos (movie trailers, clips, etc), and some amazing FullDMD videos like Fabouh's (example: https://vpuniverse.com/profile/30150-fabouh/?tab=node_filestabprofile_filesTab)
... all without PUP

As I work on more tables I'm seeing this feature missing and could really enhance a table's experience. Swamp Thing is a great example (releasing v2 next week)

thoughts on ways to implement...

Option 1... VPS does everything, including assigning the videos to the tables :: setting in each table that assigns a Backglass / FullDMD

Option 2... VPS is only the control point to start/stop videos on the correct screens :: like B2S does, videos are named same as the table with a suffix to identify what screen they are for. VPS looks for this and run the video where the suffix tells it to. This is easier for users to add/remove/change videos without needing VPS (for whatever reason... sometimes its just easier to copy a file than open VPS)

Example...

SwampThing.VPX
SwampThing.B2S
SwampThing.B2S-DMD.MP4
SwampThing.B2S-BG.MP4

**Comment by syd711** [comment]
This would significantly extend the frontend features of the Studio. I like the idea, because I like building this type of features. But there is a lot of other stuff in the queue before dealing with this.

**Comment by Ltek** [comment]
> This would significantly extend the frontend features of the Studio. I like the idea, because I like building this type of features. But there is a lot of other stuff in the queue before dealing with this.

yup, totally understand. this just dawned on me a few days ago. :)

**Comment by syd711** [comment]
Although I like the feature, I'm not planning on implementing this. As you noticed the given Java implementation I use already has some hick-ups when it comes to video playback. I could work around that parameterizing VLC player, but I'd rather keep the focus (and resources) on the table management instead of starting a frontend alternative.
