### ISSUE TITLE
HighScore Card not displaying PNG

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#307]
1080p PNG not showing.

here's the file... https://vpuniverse.com/files/file/20480-hotel-transylvania-fulldmd-static-image-with-dmd-frame/

![image](https://github.com/syd711/vpin-studio/assets/1626802/8b2866c8-095c-4578-94be-8d905d686acc)

**Comment by Ltek** [comment]
something specific to this image VPS doesnt like.

**Comment by syd711** [comment]
![image](https://github.com/syd711/vpin-studio/assets/1169826/485c320a-37aa-44ba-b846-007014ab6b7b)

I assume your download is broken?

**Comment by Ltek** [comment]
its not broken, I created/posted that image. I'm using the original file I uploaded. 

very odd!

**Comment by syd711** [comment]
Ups, yes. I will deliver a patch.

**Comment by syd711** [comment]
Fixed with 2.21.1
