### ISSUE TITLE
[Feature Request] Configure PUP option for PUP Pack

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#308]
Would be pretty cool to have VPS show the user what PUP options are available and then to install the option for the users. Since its just running a given BAT file it would be easy for VPS to do it, and it would save users from needing to remote in or mess with the file system.

**Comment by syd711** [comment]
I'm a bit confused. This feature was already there right from the beginning. I hope it did not break. I'll take a look this later.

**Comment by syd711** [comment]
![image](https://github.com/syd711/vpin-studio/assets/1169826/72ccf9f9-d183-40a0-b032-b4e9a79a5588)

Still there...

**Comment by Ltek** [comment]
DUDE... you have too many features!
jk... yeah, I clearly missed it!

awe-s-ome
