### ISSUE TITLE
[Feature Request] Playlist grid characters to make understanding easier

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#311]
would be nice to have the visuals a bit easier to understand in the grid. Being able to assign keyboard characters (numbers, letters, etc) would make it really easy to identify what playlist the table is in, when viewing the VPS grid.

For instance... the screenshot shows the table is a Favorite -and- in the Home Playlist. But really, its not in the Home Playlist, just the Favorites. 

If I could assign letters for the grid, I'd do...

Home = 'H'   (for tables directly listed in the home menu - for me, that is none but others may want this)
Favorites = 'F'
Global Fav = 'G'
Visual Pinball X = 'X'
FX3 = '3'
Video Games = 'V'
Just Added = 'J'
Most Played = 'M'

![image](https://github.com/syd711/vpin-studio/assets/1626802/d4f2255c-274c-45fb-bb76-d94e04220cd2)

**Comment by syd711** [comment]
Version 2.21.2 has been released and contains the fix.
