### ISSUE TITLE
[Feature Request] Improve UI Customization

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#312]
For smaller screens the Studio is difficult to use since the right sidebar alone has a fix width of 600px.
~~Support scaling for the whole window which supports smaller screens while loosing less pixels.~~

**Comment by Ltek** [comment]
couple of thoughts / ideas...

1. make the right sidebar a slide-out
2. allow users to hide columns in the main frame (grid). 
 example, for me...

-  I only have VPX tables; I never need to see that column
- 'high score type' ... I never need to see/know that.
- 'POV' ... this will never be relevant for me
- 'rom' ... I never need to see this in the grid.
- 'INI' ... while many of my tables have INI, I dont see why I need to see it on the grid, I've never needed to see/know that.

to save more space, and IMO be more helpful as a visual...
I suggest separate each 'item' from 'Version' and 'VPS Status' columns so users can choose to see only what they care about. (when you allow hiding columns)
examples...
I dont need to know if there is a mapped VPS to that table so I'd hide that. 
I find table versioning is difficult to track/identify... so I dont look at that info in Studio. Maybe I just have not figured out how to do it right yet.
- 
- I think (?) is has duplicate info for if an update is avail, and other items.

**Comment by syd711** [comment]
Instead of scaling:
- make sidebar collapsible
- make columns configurable (persist changes)
- make sections configurable (persist changes)

**Comment by syd711** [comment]
Delivered with 3.0.0
