### ISSUE TITLE
[Bug] Playlists: Using Studio to set Global Favorite creates duplicates

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#314]
Global Favorites bugs with playlists...

1. places table on the Home menu
2. creates duplicate table in Favorites folder.

I suspect this is due to the way the VPS selection forces you to choose Home before the Favorites box is available.

**Comment by Ltek** [comment]
best to give you my DB....
[PUPDatabase.zip](https://github.com/user-attachments/files/15957539/PUPDatabase.zip)

**Comment by syd711** [comment]
Version 2.21.2 has been released and contains the fix.

**Comment by Ltek** [comment]
cool, I'll test
