### ISSUE TITLE
[Feature Request] Adding Popper Media... ask user: Replace or Add To Existing

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#315]
when media is already existing in a given type (back glass, DMD, etc)... if a user drag-n-drop a new file Studio is automatically adding the new media as additional file. In many cases users may want to overwrite / replace the existing file, not add to it. 

Happens when a newer/better MP4  video (back glass , FullDMD, etc) gets posted.

**Comment by syd711** [comment]
As discussed on discord, for these media assets and additional selection dialog makes sense here.

**Comment by leprinco** [comment]
implemented

**Comment by Ltek** [comment]
> implemented

Implemented where?  Its not working if a media file exists in a Popper media type (see screenshot) and I drag a new file to that window, Studio never asks

![image](https://github.com/user-attachments/assets/aae73747-fc88-44ef-be8a-84d70fbfb336)

**Comment by syd711** [comment]
Implemented but not yet released. We close tickets once we have delivered.
No worries, the release is planned for this month ;)

**Comment by Ltek** [comment]
> Implemented but not yet released. We close tickets once we have delivered. No worries, the release is planned for this month ;)

this month !? that could be "days" from now.. I'm not sure I will be able to handle that... I will need a lot of distractions.... potentially both legal and not. I'll try my best

**Comment by syd711** [comment]
Delivered with 3.0.0
