### ISSUE TITLE
[Feature Request] Support Enabling/Disabling Backglasses

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#316]
The new backglass server supports a disabling flag.
We should expose this to the Studio client.

Note that we somehow have to determine the backglass version for this.
If this is possible, the resolved version should also be used in the component manager.

> ED209 — 06/25/2024 2:27 PM
The newest b2s has an option to turn off the backglass on a per table basis, but leave the full DMD on (perfect pup packs). Can the option be added to studio?

**Comment by Ltek** [comment]
In what cases / tables is this useful?  When using a PUP, you can use Pinup Popper to set a backglass, FullDMD, topper, etc. I'm not clear on when a B2S 'just for DMD' is useful?

**Comment by syd711** [comment]
Delivered with 3.0.0
