### ISSUE TITLE
[Change Request] Revisit Outdated Recordings Validator

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#326]
Check the VPX file is not a good idea here since the file will change when only the script is edited.

**Comment by Ltek** [comment]
for clarity... is this referring only to Playfield videos for when Popper's menu has a given table wheel visible? 

I'm not sure I see the value here, no matter what the video / media type. My 2 cents...

a) some people download playfield videos, so those may be older or newer than that the VPX file date
b) a table version update often does not include visual changes... thus the existing video is 'current'.
c) if a person changes the table (VPX file), they will know if they need to update the video -- thus no alert or system validation is needed. 

As for the other media types... pretty impossible to do validation. New attract, dmd, backglass, loading, etc come out all the time from different authors. Not worth trying to do anything with that. Even the online spreadsheet shows things are updated (rules, altcolor, etc) when they really have not been. At least half the time I click on one that shows updated. Its not been changed in over a year
