### ISSUE TITLE
[Bug] Clicking URLs in Linux client freezes VPin Studio

### ISSUE THREAD

**Issue by dmccombs** [syd711/vpin-studio#329]
**Describe the bug**
Clicking website links to open them seemingly anywhere in VPin Studio does not open the link, and causes the VPin Studio client to freeze.

**To Reproduce**
1. Open VPin Studio and connect to a server
2. Click on 'System Manager' on the left side
3. Click on any of the Github URL links
4. VPin Studio freezes without any error message or stdout log output, and the link does not open anywhere.

**Expected behavior**
Clicking a link should open it in the default browser and not freeze the client.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chromium
 - Version: 126

**Additional context**
While there isn't an error in this case, I wonder if this is similar to #328 and there's a need to be using `xdg-open` to open URLs on Linux.

**Comment by syd711** [comment]
Seems to be a known issue in combination with Linux.
I'll add a fix in the next update.

**Comment by syd711** [comment]
Solved with 2.21.5
