### ISSUE TITLE
[Feature Request] Provide Backglass Frames

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#332]
> Galooch — Today at 5:49 PM
Here is my current workflow along with my working Mariner (Bally 1971).res file that uses the Protomech I posted above.  This will sound far more complicated than it really is:
- Download a frame file and note the size. For most of Protomech's files, they fall into about 16 total sizes, for which I created a .res template for each for my cab.
- Copy  template .res file (Mariner uses the 1210x1080 one), rename it to match the table (Mariner (Bally 1971).res), and move it into my Tables folder.
- Copy and rename Protomech's frame image (Mariner (Bally 1971) Frame.png), and move it to my frame folder (I have a sub-folder in Tables called ~B2S Frames)
- Edit the .res file with the PNG file name (C:\vPinball\VisualPinball\Tables~B2S Frames\NAME_HERE.png)
. Run the table to  set B2S DMD = Hidden and Background = Visible
I can provide more details, screenshots if that would help show more if anything is unclear

**Comment by syd711** [comment]
[Mariner (Bally 1971).res.txt](https://github.com/user-attachments/files/16203193/Mariner.Bally.1971.res.txt)

**Comment by leprinco** [comment]
Reopened and will be used to close this comment in ticket #494

https://github.com/syd711/vpin-studio/issues/494#issuecomment-2378539129

**Comment by leprinco** [comment]
fixed in 3.10.3
