### ISSUE TITLE
[Change Request] Auto-Switch to Overview Mode

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#336]
When you bulk upload a table having asset mode enabled, the view should switch back into the table overview mode when a new table is uploaded.
This is less confusing as you can immediately see available assets (backglass, etc) of the new table.

**Comment by Ltek** [comment]
not sure if you intend to cover this but same as if you upload a VPX... it should automatically highlight/switch to the table item that you just uploaded.

**Comment by syd711** [comment]
Delivered with 3.0.0
