### ISSUE TITLE
[Feature Request] top button : Disconnect and Start Popper

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#338]
would love to have a button for 'Disconnect and Start Popper'
at the top left the the Maintenance Button...
![image](https://github.com/user-attachments/assets/600267d3-42a8-4158-b00e-d6f8c6173b54)

This is really nice for when we are using Studio remotely and want to go play when we are done... saves a few steps.

**Comment by syd711** [comment]
Isn't this setting already sufficient?

![image](https://github.com/user-attachments/assets/eb353627-8401-47a4-8cb4-19ad3576a95f)

**Comment by Ltek** [comment]
only works -if- you are in maintenance mode... I rarely use 'main mode'; dont need it most of the time. 
Often I'm remote desktop'd into the PC for testing/building a table or Pup Pack... cant use Maintenance Mode at all. 

Studio is open at that time so when I'm ready to go to the cabinet, if I can just click "Disconnect Studio & Start Popper" would be nice :)

**Comment by syd711** [comment]
Sure, no thing. But just to clarify: You mean by "disconnect" the existing disconnect which brings you back to the launcher?
I assume you want to launch Popper when you exit the while Studio, right?

**Comment by Ltek** [comment]
correct, exit studio.  thx!

**Comment by syd711** [comment]
Fixed with 3.0.1

**Comment by Ltek** [comment]
loaded 3.0.2 and dont see this?

<img width="1029" alt="image" src="https://github.com/user-attachments/assets/fecf62e5-4ded-4dc0-9448-da9057a0201d">

**Comment by syd711** [comment]
There is nothing to see, it is an action triggered on closing the Studio window.
Does it not appear?

**Comment by Ltek** [comment]
I see... its when you use the X to close studio, then it has that option. I was thinking that button would just be on the top-right side of the window, next to Maintenance Mode so it would be single click. Yes, pure laziness ;-)
