### ISSUE TITLE
[Bug] 2.2.1.6 Table Script Editing throwing errors -- worked fine at initial release

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#340]
This is on the 'remote' client. The first release when the feature was added I used it just fine on a few tables.. with the remove client. Its been a while and I tried it today in 2.2.1.6... 

![image](https://github.com/user-attachments/assets/7b9055ef-b8d2-41c3-9710-251fde0091a7)

then

![image](https://github.com/user-attachments/assets/55cc8233-b22a-46b4-aa99-b0a3fa4d5f84)

**Comment by syd711** [comment]
I assume the problem is that you don't have any default programm associated to the file ending .vbs on your client.
That's why opening the script results in trying to execute it.
