### ISSUE TITLE
PrOPPER Renaming does not properly consider emulator table destination on filename check

### ISSUE THREAD

**Issue by oper8r00** [syd711/vpin-studio#341]
**Describe the bug**
When you have multiple emulators for VPX with different table paths VPin Studio throws a "Another VPX with name "abc (bally 1993).vpx" already exist. Please chooser another name" error when the table is not physically present in the destination table directory. 

**To Reproduce**
Prerequisites:
Have at least 2 VPX emulators defined in Popper with differing table paths. For my example, I have VPX & VPX VR.

1. Open Vpin Studio and verify you have table abc.vpx in VPX but NOT in VPX VR
2. Click on the "Upload VPX files to PinUP Popper" button
3. Drag a zip file containing table abc.vpx and import as a new table
4. When Table Data Manager opens, apply PrOPPER Naming. Ensure table name would be same as VPX emulator table name "abc (bally 1993).vpx"
5. Click apply button to change Gave Screen Name & Game File Name.
6. Click Save or Save & Close
7. Error is presented even though table file did not exist in destination folder

**Expected behavior**
PrOPPER naming check should consider the destination folder for existing table names.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version VPS 2.21.6

**Additional context**
1. There are some minor typos in the message as well. It should read ""Another VPX with name "abc (bally 1993).vpx" already exist**s**. Please choose(remove the "r") another name." 
2. A funky workaround is to append the table name with something like "MOD" then flag it for fixing once the bug is addressed.

**Comment by syd711** [comment]
I just tried to reproduce this with version 3.0.
I assume we have this fixed already?

**Comment by syd711** [comment]
I tried it again and can still not reproduce this.
