### ISSUE TITLE
[Bug] VNI key error... when there should not be

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#345]
![Capture](https://github.com/user-attachments/assets/7ff73261-8e9b-4426-bbe7-1e72027653fc)

**Comment by syd711** [comment]
I have another user with the same problem, but can' reproduce the issue.
Can you zip(!) and attach the file here?
I assume it is some encoding problem.

**Comment by Ltek** [comment]
[DmdDevice.zip](https://github.com/user-attachments/files/16401753/DmdDevice.zip)

**Comment by syd711** [comment]
Fixed with 3.0.1
