### ISSUE TITLE
[Feature Request] High Score Card Editor ... Show video resolution on menu bar

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#347]
Seeing the resolution would help in creating and choosing the correct templates. We often have videos that look like the DMD box is relatively in the same location (say 2/3rd down) but we still must make different templates for each since a template made on 1920x1080 video will not line up for a 800x600 video

would love to see it above the video preview window 
![Screenshot 2024-07-27 175619](https://github.com/user-attachments/assets/677eb167-22dd-410a-bf77-1353c33bdcff)

**Comment by syd711** [comment]
Fixed with 3.0.1
