### ISSUE TITLE
[Feature Request] Set Favorites icon a different color

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#361]
With the colors the same its hard to quickly see what tables are Favs

**Comment by syd711** [comment]
3.2.0 uses different colors now.

**Comment by Ltek** [comment]
Where do we set the color for Favorites?
<img width="443" alt="image" src="https://github.com/user-attachments/assets/bcb671d6-ae88-4901-b2fb-159c43520426">

**Comment by syd711** [comment]
They are hard coded right now, I did not add a custom color picker for them yet.
I reopen this ticket to add it.

**Comment by syd711** [comment]
Fixed with 3.3.0
