### ISSUE TITLE
Can't upload via drag and drop and other...

### ISSUE THREAD

**Issue by franzernst** [syd711/vpin-studio#369]
![Screenshot 2024-08-05 161025](https://github.com/user-attachments/assets/695a3d23-b09d-41e9-bc73-46861acec0f3)
I can't upload new files via drag and drop. Only the upload Button works. But after uploading I get this (see picture). Then I have to restart VPin Studio.
And it is not possible to click on the menues in the right pane (f.e. Playlists) - nothing happens.

**Comment by syd711** [comment]
A similar issues has been reported on Discord. I'm on it.

**Comment by syd711** [comment]
Fixed with 3.0.7
