### ISSUE TITLE
[Feature Request] Pause Menu Improvements

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#370]
~~If you prefer the overlay over the pause menu, it's a valid alternative.~~

**Comment by gorgatron1** [comment]
More info that might be useful:

- type of high scores, level of support (e.g. nvram, not supported)
- rom name if nvram (so you can tell if it is maybe a duplicate -- e.g. Aliens uses the Sorcerer sorcr_l1 rom)

**Comment by syd711** [comment]
The highscore card wont be added to the dashboard, since that one can alway be displayed and does not know anything about the current table. That's why only the pause menu might have some of these options.

**Comment by syd711** [comment]
Fixed with 3.7.0
