### ISSUE TITLE
When Game not recognized, VPXMonitoringService loops infinitely 

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#371]
To reproduce : start a table from VPX directly or by double clicking a VPX file, for a table that is not registered in the frontend

VPXMonitor will then detect a Game is started, and will try to notify GameStart.
As Game is not recognized, the GameStatus never enters in Active mode, which does not stop the VPX Monitoring
Then as the monitor still detects the window, he continues infinitely to try to notify GameStart

---
I'll correct by adding a forceActive status in GameStatusService to tell the system a Game is running, but GameStatus will be null as the Game is not recognized

**Comment by syd711** [comment]
Fixed with 3.2.0
