### ISSUE TITLE
[Feature Request] Add Clear Filter to filter bar at top

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#372]
Would be helpful to have a 'clear text filter' button... in the text box or directly to the right of the text box.  I'd suggest moving the Reload button to the far left side, to be the first button, similar to how Chrome browser has reload on the far left.

![image](https://github.com/user-attachments/assets/7c4e74ac-ac2a-4c0a-86f8-6749eabf7ece)

**Comment by syd711** [comment]
I agree. I noticed that too, but I have to change this for all views, not only for the table overview to keep the UI consistent.

**Comment by syd711** [comment]
- Provide real toggle group button for asset/table manager view #470

**Comment by syd711** [comment]
Fixed with 3.7.0
