### ISSUE TITLE
[Bug] VPin Studio goes crazy... ;)

### ISSUE THREAD

**Issue by franzernst** [syd711/vpin-studio#376]
When I start VPin Studio (3.08), it starts the program many many times and crashes then.
![IMG_1871](https://github.com/user-attachments/assets/d950facb-d374-4f4e-bce0-cddc29ee11c1)

**Comment by franzernst** [comment]
[vpin studio logs.zip](https://github.com/user-attachments/files/16543723/vpin.studio.logs.zip)
Here are the log files. Please tell me, if you need something else.

**Comment by syd711** [comment]
Thank's, I'll check them later.

**Comment by syd711** [comment]
Did this happen right after the update? Is the error still reproduceable when the cabinet is restarted?
It looks like the server is started multiple times. 
Can you check if there is an older vpin-studio... something....bat in your autostart folder?
If it exists, please delete it.

The server is started though the autostart registry entry. You should see it when you open the task manager and select the "Autostart" tab. There should be one **VPin-Studio-Server** entry.

If this does not help:
- backup you database installation folder **resources\vpin-studio.db**
- run the uninst000.exe (some odd name there) to uninstall the Studio
- make a full installation again and simply replace the new database with the old version (or start from scratch).

**Comment by franzernst** [comment]
Hallo Matthias, ist es ok, wenn ich auf auf Deutsch antworte?Vielen Dank für deine Nachricht und Hilfe. Ich habe alles ausprobiert: Neustart, Kaltstart etc. Nix hat geholfen. Das Problem hat sich einen Tag später von selbst erledigt. Keine Ahnung, wieso. Also, vielen Dank nochmals. Eine Frage noch: gab es in VPin-Studio im Pane Alt-Sound einen Knopf, um Alt-Sound ein-/auszuschalten? Ich seh den nicht mehr oder irre ich mich?Viele Grüße und schönes Wochenende, ArndAm 08.08.2024 um 17:28 schrieb Matthias Faust ***@***.***>:﻿
Did this happen right after the update? Is the error still reproduceable when the cabinet is restarted?
It looks like the server is started multiple times.
Can you check if there is an older vpin-studio... something....bat in your autostart folder?
If it exists, please delete it.
The server is started though the autostart registry entry. You should see it when you open the task manager and select the "Autostart" tab. There should be one VPin-Studio-Server entry.
If this does not help:

backup you database installation folder resources\vpin-studio.db
run the uninst000.exe (some odd name there) to uninstall the Studio
make a full installation again and simply replace the new database with the old version (or start from scratch).

**Comment by syd711** [comment]
Klar, kein Thema. Ja, ich habe gehofft dass das nur ein Schluckauf war. 
Bzgl ALT Sound:
Ja, kann man, aber nicht unter "ALT Sound" selber, sondern das wird von den MAME Settings kontrolliert.
![image](https://github.com/user-attachments/assets/10eb6f61-9231-4154-b108-cdc97e2382f2)

Darüber kann man den ALT Sound dann auch ausstellen.

**Comment by franzernst** [comment]
Ah, toll - vielen Dank 🙏 Viele Grüße, ArndAm 10.08.2024 um 12:57 schrieb Matthias Faust ***@***.***>:﻿
Klar, kein Thema. Ja, ich habe gehofft dass das nur ein Schluckauf war.
Bzgl ALT Sound:
Ja, kann man, aber nicht unter "ALT Sound" selber, sondern das wird von den MAME Settings kontrolliert.
image.png (view on web)
Darüber kann man den ALT Sound dann auch ausstellen.

**Comment by syd711** [comment]
Ich mache das Ticket erstmal zu.
Wenn noch was ist: Melden! ;)
