### ISSUE TITLE
[Feature Request] Add Upload to Backglass Manager

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#387]
> alk7mist — Today at 4:50 AM
@Syd711 | [MAT] Hi Matt, Would it be possible to integrate the upload feature (drag and drop) of a Backglass .directb2s file in the Backglass Manager?  Great info in this screen as to whether the table has a FullDMD and/or Grill, but if I want to update the table to have a FullDMD, I have to back out of this screen and do the upload from the Tables window which seems inconvenient?  Also, maybe it would be nice that when you right click a table and go into Backglass Manager it opens up the backglass details for that table instead of just taking you to a list of tables (and then you have to find the table your were just in, or filter for it which is more steps)

**Comment by leprinco** [comment]
- Added dnd overlay layer to drop b2s
- Reworked of TableOverviewDragDropHandler to share code with BackglassManagerDragDropHandler
- On drop of file, use universal uploader
- Removed the dependency of the uploader on TablesController by adding a tableUploaded new event
- (re?)added an upload button and fixed code
- improved the LoadingTableCellModel with a reload() method to refresh on item of the table
- Pass the current selected game to backglass manager  and select it by default

**Comment by syd711** [comment]
Fixed with 3.3.0
