### ISSUE TITLE
multiple table folder locations

### ISSUE THREAD

**Issue by rubadub-github** [syd711/vpin-studio#39]
for VPX I have a TABLES and TABLES_PUP folder -- Any way to incorporate both into the the software?

**Comment by syd711** [comment]
I had a similar request from a VR player. How do you setup the second tables folder in PinUP Popper? You add VPX twice, but with a different tables folder?

**Comment by rubadub-github** [comment]
> I had a similar request from a VR player. How do you setup the second tables folder in PinUP Popper? You add VPX twice, but with a different tables folder?

I have two emulators - one for the regular VPX and the second for the PUPs.  I pointed both to the same ROM and media folder, so that overlaps.

**Comment by syd711** [comment]
I see. Ok, I will take care of that.

**Comment by syd711** [comment]
Fixed with version 2.1.1
