### ISSUE TITLE
[Bug] Change Table Caching

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#392]
Right now the tables area stored by their emulator id and -1 for all VPX tables.
This may result in caching errors for non VPX tables.

**Comment by syd711** [comment]
I am thinking about caching all games by id and collect them later on by emulator id.
I'm not sure if that's feasable, since this maybe memory consuming.
I've downloaded 2000 MAME games and added them with an additional emulator. It should be added as test case when changing this.

(There is an automatic InternetArchive downloader in the utils module for this).

**Comment by leprinco** [comment]
caching by table makes sense and don't see why this would be more memory consuming

**Comment by syd711** [comment]
Fixed with 3.3.0
