### ISSUE TITLE
[Feature Request] CSV export feature

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#416]
Item mentioned by ED209 and Aetron with followup by gorgatron.

Idea:
- be able to export table data as CSV
- e.g. the current filtered list in the tables view
- export all available columns of data, e.g. what is shown in the tables view
- maybe: be able to pick which columns to export (I don't think this is critical as the csv is easy enough to remove columns)
- maybe: some other columns that are not visible like table stats, top 3 scores, table year, ids for ipdb, etc.

Use cases:
- a variety of tools and manual uses could easily consume a CSV file
- example 1 (ED209)
    - make a spreadsheet with all the tables to manually track which modes have been completed
- example 2
    - if this includes recent scores it could be used as a basis for manually tracking scores over time

As an example of that I built a little app that I can record scores manually or it can grab recent scores via the VPin Studio web service and I can track my score over time:

<img width="755" alt="image" src="https://github.com/user-attachments/assets/33dbeb3a-b2fd-4078-ba0f-2aa510ed8e90">

- example 3
    - keeping notes, tips, etc. starts with having a spreadsheet of tables

I don't have a good answer for how you deal with updates to these -- I suppose you might have to manually merge things in.

Idea 2:
- be able to export b2s data as a CSV
- e.g. the file names, height, width, grill height, maybe the checkboxes for parts being enabled

Use case:
- check out this tool: https://vpuniverse.com/forums/topic/10674-b2s-individual-aspect-ratio-calculating/ from Aetron
- it has a bunch of code to parse b2s files and create .res files that perfectly place things onto screens of known sizes
- this could be _greatly_ simplified if a program could just read a csv of the size data and generate the corresponding res files

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
I am particularly interested in the b2s files -- I have looked at the responses in the web service but they don't contain enough info to generate .res files.  I think the csv of the tables could be built that way (if you are a developer)

**Comment by shro2023** [comment]
Would really like this feature myself. I work on media for the table on a separate PC and be really useful to have either an offline view of the cabinet without powering it on or ability to export the lists to Excel.
