### ISSUE TITLE
[Bug] Filter updates not saved

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#418]
> alk7mist — Yesterday at 11:43 PM
@Syd711 | [MAT] Matt, I think this has been this way for awhile now, but upon launch of VPin Studio, Tables Asset Filters always has "Backglass Available" checked off.  Is that by design?  I find myself always having to uncheck that on load, or the filter gets in the way of the tables I'm trying to find.

You need to click on "Reset", otherwise the filter state is not saved again.

**Comment by leprinco** [comment]
see #426

**Comment by syd711** [comment]
Fixed with 3.5.0
