### ISSUE TITLE
[Feature Request] Mute System button on Top Menu

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#422]
This feature is useful when remoting into a system and wanting to make it silent. Could be for many reasons, including for table authors so when working/developing/testing a table, it does not bother people who may be in the area.

Currently I must kill PinVol manually and place OS on Mute

Ideally Studio's single 'Mute' button would do this...

1. Pause Pinvol / Temporary disable it
2. Mute the operating system volume

... and reverse when taken off mute.

**Comment by syd711** [comment]
Fixed with 3.6.0

**Comment by Ltek** [comment]
thank you!
