### ISSUE TITLE
[Bug] Detects Table incorrectly... Creature from The Black Lagoon as a few other tables

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#423]
I just drag-drop the table ZIP on Studio and it seems to think its Batman or Jurassic Park depending on the VPX file name.

Note:

- I have never installed this table or any variation
- name of file I tried to install... Creature From The Black Lagoon (Bally 1992) 1.2 Ejse83 LED Mod.vpx
- I tried it when showing all my tables in the grid, and when only showing 1. name or number of tables showing in grid does not affect
- same error even when 'Auto Match' is unchecked; changing this changes what Studio thinks the table is
 (see screenshots)
- changing the VPS file name changes what Studio thinks the table is
 (see screenshots)

<img width="935" alt="image" src="https://github.com/user-attachments/assets/b1342e2b-28b1-48ff-bc16-d427d325e773">
<img width="932" alt="image" src="https://github.com/user-attachments/assets/a89fbe82-6420-4fd2-a459-9b5e1786eb47">

**Comment by syd711** [comment]
Yes, we already got feedback about this. Text is confusing and the check too fuzzy.
It should work only as an additional security check in case one accidently selected the wrong table before.
This will be improved.

**Comment by syd711** [comment]
Fixed with 3.5.0
