### ISSUE TITLE
[Bug] Table Grid Filter does not clear when Reset or Unchecking box

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#426]
I have tried multiple times to clear the check box, and even use Reset. It does this correctly but upon restating Studio, that box is still checked - thus the filter is active, not cleared.

<img width="228" alt="image" src="https://github.com/user-attachments/assets/f0806f53-c997-42b2-861d-2dde1f56b5de">

**Comment by leprinco** [comment]
fixed in 3.5 by manually calling saveFilters when filter goes to all blank

**Comment by syd711** [comment]
Duplicates https://github.com/syd711/vpin-studio/issues/418

**Comment by syd711** [comment]
Fixed with 3.5.0
