### ISSUE TITLE
Playlists support for pinballX frontend

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#427]
Add playlist management for pinballX

**Comment by leprinco** [comment]
- added management of playlist by activate supportPlaylist for pinballX frontend
- Implemented load / save of pinballX playlists and favs
- concept of fav is  much simpler : a global favorite flag, not linked to playlist. So introduced supportPlaylistExtended in FrontendType to bifurcate between the simple mode of pinballX (false), and the complex one of popper (true)
supportPlaylistExtended = false  basically deactivates the local / global flag per playlist. Favorites playlist is just like any other playlist with no game played restriction
- added an optional emulatorId (always null for popper as not set and always not null for pinballX). And when it is set, a game from another emulator cannot be put in the playlist (checkbox disabled)

**Comment by syd711** [comment]
Fixed with 3.5.0
