### ISSUE TITLE
3.1.4: macOS drop in assets should ignore .DS_Store (maybe all dot files)

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#431]
**Describe the bug**
macOS drop in assets should ignore .DS_Store (maybe all files that start with a `.` as they would be hidden on a unix system, so this might apply to the linux client as well)

**To Reproduce**

1. set up the drop in asset directory
2. create a file name `.DS_Store` in it (Finder on macOS tends to create these files)
3. view the drop in assets drop down:

<img width="2431" alt="image" src="https://github.com/user-attachments/assets/9de47791-67fe-44e0-a422-43898a798833">

**Expected behavior**

Users may be confused by this file -- generally unix systems hide files that start with `.`

**Screenshots**

See above

**Desktop (please complete the following information):**
 - OS: macOS

**Comment by syd711** [comment]
Fixed with 3.5.0
