### ISSUE TITLE
[Feature Request] Defer loading of stats from initial start and add loading in Statistics tab 

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#439]
Todat stats are loaded at studio startup
Defer the first load to the first tab activation
Add a loading indicator
When reloading, empty the screen and disable buttons 

![image](https://github.com/user-attachments/assets/80099bd3-41b3-4505-aff5-03b896986b9d)

**Comment by syd711** [comment]
Fixed with 3.5.0
