### ISSUE TITLE
filters is too sticky -- on launch comes up with previous setting

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#444]
**Describe the bug**
filters is too sticky -- on launch comes up with previous setting.  Specifically I used "new version available" and even though I turn it off, when I rerun vpin studio (macOS 3.4.1 client) it comes back up with "new version available" checked.

**To Reproduce**

1. in the filter sidebar (see below) check "new version available"
2. use the app for a while
3. (maybe) quit the app, relaunch
4. un check "new version available"
5. quit the app
6. relaunch -- see that "new version available" is checked again

<img width="272" alt="image" src="https://github.com/user-attachments/assets/3c8cd54f-5418-461f-83db-33b07ad41052">

I am not 100% sure what the repro steps are because I can't get back into the unchecked state on launch :-)

**Expected behavior**

Having the filters be sticky on quit -> launch might be a nice feature, but when I uncheck a filter and quit it shouldn't come back on the next launch.

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by syd711** [comment]
Known issue, one has to click "reset" to actuall reset AND save the state.

**Comment by syd711** [comment]
Duplicates https://github.com/syd711/vpin-studio/issues/426

**Comment by syd711** [comment]
Fixed with 3.5.0
