### ISSUE TITLE
3.5.0: there are two of me!  duplicate entries in global player ranking (vpin mania)

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#450]
**Describe the bug**
duplicate entries in global player ranking (vpin mania)

**To Reproduce**

Went to VPin Mania and all the names are duplicated:

<img width="2176" alt="image" src="https://github.com/user-attachments/assets/e2522383-5510-4f8a-b18a-a02902378f22">

[vpin-studio-logs.zip](https://github.com/user-attachments/files/16915050/vpin-studio-logs.zip)

**Expected behavior**

Less duplication

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by syd711** [comment]
I saw that too and it was gone after a reload. On it.

**Comment by syd711** [comment]
Fixed with 3.5.1

**Comment by gorgatron1** [comment]
@syd711 I ran into this again in 3.5.1.  As you mentioned a reload did fix it.

**Comment by syd711** [comment]
I think it was because I build the last release with the non-update client for the vpin mania services.
Should be fixed with 3.5.2.
Please re-open this ticket if I'm wrong.

**Comment by syd711** [comment]
Note to myself: I think the issue is caused every time a new score is submitted.

**Comment by syd711** [comment]
Fixed with a timed re-creation of the list.
Fixed with 3.7.0
