### ISSUE TITLE
[Bug] Missing sync between VPX filename changes and backglass manager

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#452]
> alk7mist — Today at 5:33 AM
@Syd711 | [MAT] Matt, when doing a VPX table upload, "Upload and replace "Table name", if you make changes to the VPX game filename on the next screen, and Save and Close...if you right click that table and go to Backglass Manager, it won't display the Background Preview or DMD Preview  becasue it can't find the backglass file anymore.  The same thing happens if you simply update the game file name in Table Data Manager.  When in Backglass Manager, if you do a Reload all table data and go back to that Backglass, the preview is working again.  Maybe force a "Reload all table data" in the background for Backglass Manager if a game filename was changed will resolve this?  It's confusing for the user, as they'll think they don't have a Backglass (or can't be found) but they really do.  🙂

**Comment by leprinco** [comment]
fixed in 3.6 branch

**Comment by syd711** [comment]
Fixed with 3.6.0
