### ISSUE TITLE
[Bug] highscore.txt ignored

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#456]
**Describe the bug**

A table can have a rom name, alt rom, and high score.txt.  If the high score.txt is set it is ignored in the high scores section.

3.5.1

I thought I might have already filed this (it seems familiar), but I can't find it. 🤷 

**To Reproduce**

1. Table is Jungle Princess (Gottlieb 1977) FrankEnstein -- https://vpuniverse.com/files/file/21544-jungle-princess-gottlieb-1977/
2. I don't recall if I set this manually or it scanned it (it appears to be scanned in the UI, see screenshot below), but make sure the high score.txt file name to `jungleprincess_1977_v2a.txt`

From the script:

```
' Highscore stuff
Const HSFileName="jungleprincess_1977_v2a.txt"
```

4. Play a game to make sure it write out the text file
5. View the high score inspector for the table

<img width="2176" alt="image" src="https://github.com/user-attachments/assets/fee2ef77-0fa0-4549-a532-8ed2627148c1">

Note: the jungleprincess_1977_v2a.txt file does indeed exist.

**Expected behavior**

Expected: since this table doesn't have a nvram it should use the configure txt file instead it says no file found.

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by syd711** [comment]
You filed this, but for another table.
The issue is that no matching parser is found for the text file. So I will fix the error message in the section and support the textfile.
