### ISSUE TITLE
[Feature Request] Support Table Actions Log

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#463]
> zestef — Today at 4:05 PM
Hello,
Two feature requests (a simple and more complex one): 
Simple : Add, on the "All Tables" Tab, a new column that will display "Date Updated" (when I've modified something on my table : rom, alt color, alt sound, vpx, b2s, ...)
Complex : get an history/activity log off the table (09/11/24 - Alt Color Rom Updated / 08/23/24 - VPX Replaced / ....)
I don't know if it's possible for these two requests as I think VpinStudio don't manage his own database to store these type of informations (maybe by using a field in pinup popper database)

**Comment by leprinco** [comment]
Partially implemented, added in branch 3.6 the last update column + ability to show / hide the column in UI settings
The last update date is coming from frontend and mostly represent modification of the tabl iteself

to be discuss how to monitor all changes and add them in audit trail

**Comment by syd711** [comment]
The "Date Upated" has been added.
The audit trail is a won't fix.
