### ISSUE TITLE
[Bug] VPS Tables view have DirectB2S and Pup Pack column labels switched

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#465]
**Describe the bug**
VPS Tables view have DirectB2S and Pup Pack column labels switched

**To Reproduce**

Go to the VPS Tables tab.  Look at the DirectB2S and Pup Pack columns -- none of those old Stern tables have a Pup Pack but they do have a B2S -- I think these columns are swapped (the labels do not match the column data).

<img width="2119" alt="image" src="https://github.com/user-attachments/assets/ca955c5b-eb8d-44cb-aa05-a085582e8a60">

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by syd711** [comment]
Fixed with 3.5.4
