### ISSUE TITLE
Multiple listeners after disconnect / connect

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#474]
When user is disconnecting from server then reconnecting without stopping the UI, the applications restarts and reinitialize controllers

As EventManager and UILocalSettings are keeping a static list of listeners, after disconnect/reconnect, system ends with multiple listener registered

![image](https://github.com/user-attachments/assets/524c1441-ec5d-42dd-bdd4-696cbdd0bff0)

**Comment by leprinco** [comment]
fixed in 3.6

**Comment by syd711** [comment]
Fixed with 3.6.0
