### ISSUE TITLE
[Bug] Hangs on Client version mismatch with Server ... [Feature Request] move update code into Launcher

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#483]
I loaded 3.6.0 on the server yesterday, then today ran the remote client. I got the error in the attached screenshot and then it just hung on the splash screen, had to kill the process.

<img width="601" alt="image" src="https://github.com/user-attachments/assets/d2c4ffa0-ded3-45a9-b9b2-2036c555cd0c">

Recommendation: move the version check and update into the launcher itself. With an indicator that the client doesnt match the server version, before trying to connect to the server. This allow us to do the update without even loading the client, which in this bug it causes a crash.

<img width="596" alt="image" src="https://github.com/user-attachments/assets/efef4a88-cce8-482f-a744-eb1e70e4362a">

**Comment by syd711** [comment]
I've added a blind fix here for 3.7.0, but have not tested this yet.

**Comment by Ltek** [comment]
I think this is fixed. I tested updating the server (from the server) then opened the remote client. No issues. I like how it alerts you to the newer version prior to launching/showing the full client.

**Comment by syd711** [comment]
Thanks for reporting back about this!
