### ISSUE TITLE
[Bug] Changing media for a playlist in asset manager instead changes the selected table

### ISSUE THREAD

**Issue by dmccombs** [syd711/vpin-studio#484]
**Describe the bug**
Using the Asset Manager to change playlist media does not change the playlist media, but instead changes the selected table's media.

**To Reproduce**
1. Select a table, open Table Media, and select something to open Asset Manager
2. In Asset Manager, change upper-right radio button to "Playlists"
3. Select a playlist from the upper-left drop down (I chose Movies)
4. Select something to change (I chose wheel image)
5. Search for something, and click download
6. The image does not then show up in "Installed Assets" for the playlist, instead it updates the media for the table that was selected in the main window.

**Expected behavior**
This should update the playlist's media, and not a table's.

**Screenshots**
![shot-2024-09-21_17-35-37](https://github.com/user-attachments/assets/2491a8ab-8923-4a0e-bb26-4d1b055f2977)

**Desktop (please complete the following information):**
 - Client OS: Archlinux
 - Cabinet OS: Windows 10
 - VPin-studio version: 3.6.0

**Comment by syd711** [comment]
Fixed with 3.7.0
