### ISSUE TITLE
New high score not reflected after exiting table

### ISSUE THREAD

**Issue by ecchodun** [syd711/vpin-studio#489]
Last version of vpin-studio (updated today 9/23) and when I get a high score on a table and exit the table the high score is not reflected in vpin-studio's high score data until I rescan the table.  It's happened on three different tables.  I've even rescanned a high score on a single table and got a new high score on the same table and it didn't update on table exit.

Using front end pinup popper with Visual Pinball X.  

My script for Visual Pinball X on close does list the following command:

curl -X POST --data-urlencode "table=[GAMEFULLNAME]" http://localhost:8089/service/gameExit  

I wasn't sure if that line was put in their by vpin-studio and was relevant to this issue.

**Comment by syd711** [comment]
Yes, the Studio server adds this line so that it gets notified for table exits.

Does the event log of the table show something that explains this?

![image](https://github.com/user-attachments/assets/62b7eeb2-dd09-44cf-9714-a51f02336f7c)

**Comment by ecchodun** [comment]
The Open VPS Entry, Reset VPS Updates and Event Log are all grayed out in my version.

**Comment by syd711** [comment]
The event log is written when the table start + end events are detected. These are triggered through the CURL calls in the emulator.

![image](https://github.com/user-attachments/assets/e813824f-909a-42f7-9fed-3c02b54fd1ac)

Can you check if both entries are there? Can you also attach all server log files here?

**Comment by ecchodun** [comment]
I think I found the error?  I have the line "Exit Script" after the "if %FSMODE%...." line above.  I assume I should move it to perhaps after your curl -X POST command?

If that's not the case, how do I get you my log file?

**Comment by ecchodun** [comment]
Yes.  That fixed it.  Sorry for the trouble.

**Comment by syd711** [comment]
Happy that it works now!
