### ISSUE TITLE
Speed up tables filtering and auto refresh filtered tables when change happens on table

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#490]
Implemented filtering on client side, It speed up the process, avoiding a client / server exchanges

As filterids are no more maintained on client side but filters takes real data on GameRepresentation, when GameRepresentation is modifed, the filtered tables are automatically updated
ex : filter on notes = Any, then remove one note, the table immediately disappear

**Comment by syd711** [comment]
Fixed with 3.7.0
