### ISSUE TITLE
[Feature Request] Backglass Manager Improvements

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#494]
> gorgatron — Today at 8:17 AM
suggestion: 
in the table media full dmd / dmd area, be able to assign the image from the backglass if available (and it should probably indicate its size so you know if it is appropriate)
same idea, but also be able to convert the backglass image (minus grill, optionally) into an image for the backglass media
I normally use Popper to record videos for the backglass but often use static images for the dmd (e.g. https://vpuniverse.com/files/file/20556-static-dmdzip/).  Some of the backglasses have really nice static dmd images that would be great to use.

**Comment by syd711** [comment]
gorgatron — Today at 8:55 AM
Here is a first version of something that makes .res files.  There are some fixes coming for DMD dimensions (it looks like they are maybe in the next release) and I will update it then.  Let me know if you have problems or ideas to make it better!

You run it like this:

> python make_res.py --csv ~/backglasses.csv --output /tmp/res --match Spider
Spider-Man - Vault Edition (Ste
[make_res.py.txt](https://github.com/user-attachments/files/17160262/make_res.py.txt)
rn 2016) VPin Workshop (VPW) 2.1
Spider-Man (Stern 2007) Siggi 1.2.1
The Amazing Spider-Man (Gottlieb 1980) Xenonph 2.1
The Amazing Spider-Man (Gottlieb 1980) Xenonph 1.1


The resulting .res files will match the dimensions of the backglass (sans grill) so you won't have any stretching.  I am regenerating my backglass popper files now 🙂

**Comment by leprinco** [comment]
As part of this ticket resolution, only first part/comment will be done and we will close the ticket
The scond part (backglass frame) will be covered as part of #332 resolution

**Comment by syd711** [comment]
Fixed with 3.7.0
