### ISSUE TITLE
[Feature Request] User definable Popper Video Recording Options 

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#496]
I should have thought of this before, sorry. Would be good to have this 'user definable' so we can adjust the scripts and options to suit each user's need. For example, I dont see the added scripts showing if audio is kept/removed. Some of the scripts remove audio... for me, I always keep the audio.  

Even if its manually editing an INI, JSON, etc it would be nice to be allowed to add/remove scripts, especially for custom scripts.

https://github.com/syd711/vpin-studio/issues/317

**Comment by syd711** [comment]
You can add additional scripts.
Every **POPMedia_XXXXXX.bat** file in the C:\vPinball\PinUPSystem\Recordings folder will be added to the list of conversion options. Note that this list is only read once on server startup, so you have to restart the server if you added new scripts.

I think this is what you requested?

**Comment by syd711** [comment]
Documentation added 
https://github.com/syd711/vpin-studio/wiki/Table-Asset-Manager
