### ISSUE TITLE
Aladdin's Castle vpreg high scores not supported

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#498]
**Describe the bug**
Aladdin's Castle vpreg high scores not supported -- they have a slightly different format.

**To Reproduce**

1. Aladdin's Castle: https://www.vpforums.org/index.php?app=downloads&showfile=13502
2. Get a high score
3. Exit the table
4. Try to view scores in VPin Studio -- found VPReg entry but no scores in it

The format of the keys is slightly different:

<img width="445" alt="image" src="https://github.com/user-attachments/assets/3f94f335-982f-46a7-b685-454c9a0b48bb">

from the code:

```
Dim SavedVars : SavedVars = Array( _
	"ScorePlayer(1)", "CDbl", 0, _
	"ScorePlayer(2)", "CDbl", 0, _
	"Credits", "CDbl", 0, _
	"Highscore(0)", "CDbl", 70000, _
	"Highscore(1)", "CDbl", 0, _
	"Highscore(2)", "CDbl", 0, _
	"Highscore(3)", "CDbl", 0, _
	"HighscoreDate(0)", "", "6/16/1976", _
	"HighscoreDate(1)", "", "", _
	"HighscoreDate(2)", "", "", _
	"HighscoreDate(3)", "", "", _
	"HighscoreInits(0)", "", "GK[", _
	"HighscoreInits(1)", "", "", _
	"HighscoreInits(2)", "", "", _
	"HighscoreInits(3)", "", "", _
	"OptAlleyScoring", "CInt", 1, _
	"OptSpecialVal", "CInt", 0, _
	"OptReplayVal", "CInt", 0, _
	"OptReplay1", "CDbl", 65000, _
	"OptReplay2", "CDbl", 99000, _
	"OptBallsPerGame", "CInt", 3, _
	"OptFreePlay", "CInt", 0 _
)
```

**Expected behavior**

Ideally the scores would be read -- I want my 54000!

**Comment by syd711** [comment]
Fixed with 3.7.0
