### ISSUE TITLE
Little Joe (and others) highscore.txt not read correctly

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#499]
**Describe the bug**
Little Joe highscore.txt not read correctly -- looks like a different format

**To Reproduce**

1. Play Little Joe and score a high score: https://vpuniverse.com/files/file/16125-little-joe-bally-1972_teisen_mod/
2. View high scores

<img width="204" alt="image" src="https://github.com/user-attachments/assets/1a46c88d-d508-4aeb-a931-50b5978c2fa6">

Here is the txt file:
 
[LittleJoe_71VPX.txt](https://github.com/user-attachments/files/17176893/LittleJoe_71VPX.txt)

It looks like it has more leading lines than usual.  Aside from reading the high scores incorrectly I wonder if the reset would work correctly?  I wonder if it would work to ignore numeric lines with 1 or 2 digits (looking at the files by hand it looks like the scores are all over 2 digits).

**Expected behavior**
Scores would be read correctly.

**Comment by gorgatron1** [comment]
[User.zip](https://github.com/user-attachments/files/17177023/User.zip)

In case it might help I attached all the scores from my User directory (both text and vpreg).  I don't have high scores on all of them, but I do have quite a few tables (in case you wanted to scan the formats).

**Comment by gorgatron1** [comment]
Scanning through the text & vpreg scores and there were only a couple that didn't read right:

- the_fog_1979 (https://vpuniverse.com/files/file/8357-fog-the-gottlieb-1979-complete-package/) -- I think the 150000 shouldn't be there -- single score
- TeachersPet_1965 (https://vpuniverse.com/files/file/9355-teacher_s-pet-williams-1965-loserman-76-update/) -- corrupt
- Yukon_1971 (https://vpuniverse.com/files/file/8164-yukon-williams-1971/) -- corrupt

**Comment by gorgatron1** [comment]
- aztec.txt -- no parser found.  The 88640 is the high score

**Comment by syd711** [comment]
I think I have catched them all.
Fixed with 3.7.0
