### ISSUE TITLE
high score cards disabled gives flashing loop -- hangs client

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#500]
**Describe the bug**

If you set "high score cards enabled" to NO on a table and try to view the high scores the client goes into a flashing loop (see attached video).  macOS client, 3.6.1

**To Reproduce**

1. Select a table
2. Uncheck "high score cards enabled" in the high scores inspector
3. select a different table and go back to the original table
4. It looks like an alert (scanning high score updates) shows up, then vanishes
5. It does this in a loop and you have to kill the client to get it to stop

**Expected behavior**
Not show the high score card but otherwise behave the same as if it were checked.

**Screenshots**

[client-logs.txt](https://github.com/user-attachments/files/17182532/client-logs.txt)
[vpin-studio-logs.zip](https://github.com/user-attachments/files/17182533/vpin-studio-logs.zip)

https://github.com/user-attachments/assets/94394e69-ec35-4657-ab94-ee463ee72736

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by gorgatron1** [comment]
I see the same behavior on the windows client (on the cabinet machine)

**Comment by syd711** [comment]
Fixed with 3.7.0
