### ISSUE TITLE
[Bug] Adding a new table -- doesn't appear in Just Added

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#507]
**Describe the bug**

3.7.0

I added a new table and it did not appear in Just Added -- it looks like maybe the playlist was cached and I needed to force refresh before I saw it.

**To Reproduce**
1. Import a new table
2. Switch the playlist filter to Just Added
3. Observe that the new table is not present
4. Press the reload button (next to the filter on the left) -- this will deselect the playlist
5. Select Just Added again, now observe the table is there

I am pretty sure in the past the Just Added was more "live" -- I would use this playlist to import a few tables and then go apply all the various settings.

**Expected behavior**

The table should appear immediately or at least when the Just Added playlist is selected.

**Comment by syd711** [comment]
Ah yes, we tried to avoid the refresh, but possibly missed that.

**Comment by leprinco** [comment]
oups.. yes objective was to remove the global reload that takes time but most probably it was doing something in background that is not done anymore, I'll check. thanks !

**Comment by leprinco** [comment]
on table change event (addition or modification) playlists are refreshed
This correct this issue that is a regression but it also fixes issue when the playlist is computed based on name and the name is changed in the edit Table Data popup for instance. 
Also the playlist when selected is now reselected consecutive its refresh or global reload asked

**Comment by syd711** [comment]
Fixed with 3.7.2.
