### ISSUE TITLE
Support Playlist Media management

### ISSUE THREAD

**Issue by shro2023** [syd711/vpin-studio#510]
**Is your feature request related to a problem? Please describe.**
When updating media I have to use the PinUp Popper Media manager when wanting to change the default media files on a playlist

**Describe the solution you'd like**
I would like to be able to browse and edit playlists through VPINStudio both to update the media and also amend the SQL queries on the dynamic lists if possible.

**Describe alternatives you've considered**
Currently using PinUp Popper setup to manage playlist but this cannot be done remotely

**Additional context**
N/A

**Comment by shro2023** [comment]
Looks like this is already possible through table asset manager radio button to playlist.

**Comment by syd711** [comment]
Yes, there was a bug for some time, but with 3.7.0 is should be working.
