### ISSUE TITLE
backglass manager doesn't show correct information when I have two tables with the same name

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#511]
**Describe the bug**
backglass manager doesn't show correct information when I have two tables with the same name.  specifically the "B2S DMD Hidden" flag is not show correctly.

**To Reproduce**

1. I have 3 Gorgar tables: Gedankekojote97, RetroRitchie, UncleWilly.
2. The first two of those have this b2s: https://vpuniverse.com/files/file/9787-gorgar-williams-1979-authentic-b2s/
3. The third (and I am not sure this one matters) has: https://vpuniverse.com/files/file/12387-gorgar-williams-1979-b2s-with-full-dmd/

4. Go to the Backglasses tab and select the first table
5. Disable the B2S DMD
6. Select the second table
7. Notice that the checkmark is missing
8. (The exact behavior seems to be dependent on which one you select first, but one of them will show the checkmark and one will not)

**Expected behavior**

Per the actual VPX behavior and the All Tables / Backglass inspector it seems that there is only one state for both backglasses and I would expect the Backglasses tab to reflect that (as the All Tables view does)

**Screenshots**

This looks fine in the All Tables view with the Backglass inspector:

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/8571ca09-6525-4585-a53f-e09dee9f68d8">

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/9af9737f-3d03-4344-9033-046a33ea9471">

but in the Backglasses tab the first table doesn't show the Hidden flag or the Skip Lamp Frames:

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/ddb5e418-b796-41ac-85be-0003df52aebd">

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/e7da7013-ac6d-4b1d-a81f-2d6374956253">

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by leprinco** [comment]
starnge behavior on save(), now fixed

**Comment by syd711** [comment]
Fixed with 3.7.2.
