### ISSUE TITLE
backglass shows DMD preview but b2s server doesn't have a DMD

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#513]
**Describe the bug**
backglass shows DMD preview but b2s server doesn't have a DMD

**To Reproduce**

The backglass here: https://vpuniverse.com/files/file/10139-the-thing-balutito-reskin/

Notice the backglass inspector shows a DMD Preview:

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/db3794cf-4198-4a3c-ba5b-a6410be52690">

but when I actually run the table (or just the b2s server on the backglass) there seems to be no DMD at all

**Expected behavior**

Not show a DMD preview if there is none

**Comment by gorgatron1** [comment]
I think this b2s has the same issue: https://vpuniverse.com/files/file/15075-killer-klowns-b2s/

**Comment by syd711** [comment]
The information is correct. Both these backglasses have a DMD image available, but it looks the same as the backglass.
You can check for yourself by opening the backglass file with a text editor. 
So I'd say this is no bug.

**Comment by davidkoski** [comment]
Sure enough -- I wonder why the b2s server doesn't display the DMD image?  I just see the backglass.

**Comment by syd711** [comment]
> Sure enough -- I wonder why the b2s server doesn't display the DMD image? I just see the backglass.

I asked myself the same think. There must be some kind of check of config flag is in the backglass server I am not aware of.
