### ISSUE TITLE
[Bug] Short Circuit high score issues

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#514]
**Describe the bug**
Short Circuit high score issues

- failed to find filename
- unable to read score without rom set?
- unknown format for text file

**To Reproduce**

Table: https://vpuniverse.com/files/file/21686-short-circuit-rober-benoriginal-2024/

VPin Studio fails to find the high score settings with the scan -- here is the code:

```
Const HSFileName="ShortCircuitRB.txt"
```

I set this in the Score Data:

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/bcabb32d-b61e-4881-af59-e97aed3d310d">

and the green check _seems_ to indicate that it is ok.

but notice the text at the bottom indicating "No ROM name could be resolved" with a warning about reading scores -- ideally this would be indicated in the Score Data or even handled automatically.

Here is the score file:

[ShortCircuitRB.txt](https://github.com/user-attachments/files/17267437/ShortCircuitRB.txt)

**Expected behavior**

- ideally it would configure the scores correctly for the table
- if not, easy enough to set in the Score Data but this should either indicate the error (can't read without a rom name) or just fix it if the rom name is missing
- yet another high score.txt file format :-)

**Comment by syd711** [comment]
Fixed with 3.7.2.
