### ISSUE TITLE
[Bug] Update of table duplicated all the Table Media

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#515]
**Describe the bug**
update of table duplicated all the Table Media

**To Reproduce**

Table: https://vpuniverse.com/files/file/21686-short-circuit-rober-benoriginal-2024/

I had version 0.9.1 of this table installed.  The zip comes with PUP, Backglass, Media Pack, etc.  I went to upgrade it to 0.9.3 like this (I am just showing the panel -- it is already upgraded):

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/6255e4c0-e39f-45a2-b57e-dadb047ebe77">

all the media files were doubled up:

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/69116200-7cd5-4ca3-a027-6cd501acde07">

**Expected behavior**

I am not sure what I expect exactly, but not what happened.  Probably one of these:

- ignore the media on the upload & replace
- remove the old media before replacing
- ask me what I want to do (or have the option in the upload panel)

**Comment by syd711** [comment]
Fixed with 3.7.2.
