### ISSUE TITLE
[Bug] "Replace dmd media" offers to overwrite but does not if the other media is a video

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#518]
**Describe the bug**

"replace dmd media" offers to overwrite but does not if the other media is a video -- works ok if it is an image

**To Reproduce**

1. a table with a video asset in the full dmd, e.g. one of the nice animated dmd screens
2. in the Backglasses screen export the dmd from a backglass and overwrite the existing media

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/244ce957-696b-4aa4-80eb-6b6960798d37">

3. Go to the table media and observe that the .mp4 is still there and a .png was added

<img width="2230" alt="image" src="https://github.com/user-attachments/assets/99ada3f7-ddf5-4cd9-a684-8d4152ee2571">

**Expected behavior**

It can't overwrite the file but I would expect it to delete the old one.

**Comment by syd711** [comment]
Fixed with 3.7.1
