### ISSUE TITLE
[Change Request] Please create a shortcut for the startup

### ISSUE THREAD

**Issue by RetroTheArcadian** [syd711/vpin-studio#519]
**Is your feature request related to a problem? Please describe.**
When the startup launches the bat file for running the vbs server script it shows the console window.

**Describe the solution you'd like**
Create a shortcut .lnk in the installer where the bat in called from and properties is set to having "run" : "minimized"
Refer to that shortcut in the startup/registry rather than the bat file.

**Comment by syd711** [comment]
Do you run Win11? Iirc the Win11 users had more problems with this. The console window is not visible on my cab with Windows 10.

**Comment by Ltek** [comment]
I use Win 11. Only when ran manually, after login when the desktop is showing, you will see a 'flash' when the command window opens/closes. When it runs during login there is not a flash since it is ran prior to the splash/login screen going away and the desktop showing.
It is possible that on a very slow machine the command window could be visible for half a second.

**Comment by RetroTheArcadian** [comment]
I am running a 14kf intel with 4070 RTX on Windows 11 Pro. The cmd window stays open on my machine. Then I altered the registry to use the shortcut I described and now it starts up minimized.

**Comment by syd711** [comment]
Sounds good! I'll apply this.

**Comment by Ltek** [comment]
> I am running a 14kf intel with 4070 RTX on Windows 11 Pro. The cmd window stays open on my machine. Then I altered the registry to use the shortcut I described and now it starts up minimized.

something specific with your system, BAT files only stay open as long as the command takes to execute.

Also, registry has nothing specific to do with it. you can create the shortcut (.LNK file) set to run minimized and run it without flashing the CMD window... its still there, just minimized and 'open' just as long as if it wasnt.

@syd711 there are many ways to skin this cat. here's a great thread...

https://superuser.com/questions/62525/run-a-batch-file-in-a-completely-hidden-way

**Comment by syd711** [comment]
> @syd711 there are many ways to skin this cat. 
haha, I've never heard this phrase.

**Comment by syd711** [comment]
Fixed with 3.7.2.
A shortcut is generated for the start folder.
The shortcut is executed minimized from the autostart as initially suggested.
