### ISSUE TITLE
[Bug] table csv export missing escaping

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#520]
**Describe the bug**

table csv export missing escaping (I think)

**To Reproduce**

Consider this csv export.  There are three tables that have corrupt CSV:

- Champions League 2020 (Original 2020) Donuts 1.1
- Eight Ball Deluxe (Bally 1981) Bord 2.0
- Transformers (Stern 2011) RobbyKingPin 2.1

[tables.csv](https://github.com/user-attachments/files/17271243/tables.csv)

They have unquote semicolons e.g. in the Notes (gNotes) field:

```
number increases; next match will
```

**Expected behavior**

semicolons in text need to be quoted

**Comment by gorgatron1** [comment]
Oh, it looks like it is a lot more -- I just noticed those when I sorted by year and the number of fields wasn't correct:

- Radical! (prototype) (Bally 1990) VPW 1.0.1
- Scooby Doo (Original 2022) Mrjcrane 1.0.1
- Ace of Speed (Original 2019) mussinger 1.0.1
- Big Game (Stern 1980) Redbone 1.5.1
- Radical! (Bally 1990) JPSalas 4.0.0
- JP's Terminator 2 (Original 2020) JPSalas 4.3.0
- Apollo 13 (Sega 1995) UnclePaulie 2.1.4
- Star Trek The Next Generation (Williams 1993) VPin Workshop (VPW) 1.1
- Demolition Man (Williams 1994) Knorr 2.0
- Demolition Man (Williams 1994) OttOBuS59 1.0.0
- Dr. Dude and His Excellent Ray (Bally 1990) Arconovum 2.2-2.6
- Creature from the Black Lagoon (Bally 1992) Fuzzel 1.3
- The Machine - Bride of Pin-bot (Williams 1991) Wrd1972 2.1
- The Machine - Bride of Pin-bot (Williams 1991) VPW 1.0.4
- The X Files (Sega 1997) TastyWasps 1.29
- Funhouse (Williams 1990) Gedankekojote97 1.1
- Adventures of Rocky and Bullwinkle and Friends (Data East 1993) Cyberpez 1.0
- WWF Royal Rumble (Data East 1994) R and D Repair 1.09
- Cyclone (Williams 1988) RobbyKingPin 2.1.1
- Back to the Future (Data East 1990) TastyWasps 1.05
- JP's Cyclone  (Williams 1988) JPSalas 4.3.0
- JP's The Lost World Jurassic Park (Sega 1997) JPSalas 4.3.0
- Red & Ted's Road Show (Williams 1994) VPin Workshop (VPW) 1.4
- Space Jam (Sega 1996) JPJ 1.4
- Dr. Dude and His Excellent Ray (Bally 1990) Wrd1972 3.0
- Senna - Prototype Edition (Culik Pinball 2020) JPSalas 1.0.1
- Desert City (Fipermatic 1977) Loserman76 1.0.0f
- Satin Doll (Williams 1975) Loserman76 1.0.0f
- Yukon (Williams 1971) Loserman76 1.0.0f
- Concorde (Emagar 1975) Loserman76 1.0.0f
- Jolly Roger (Williams 1967) HauntFreaks 2.0.1
- Canada Dry (Gottlieb 1976) Teisen 1.1.0
- Blue Note (Gottlieb 1978) EMUnderdogs 1.1.1
- Hot Hand (Stern 1979) Armyaviation 1.0
- Secret Agent (Original 2024) Wizball 1.0.0
- Eye Of The Tiger (Gottlieb 1978) Styx 1.1
- JP's Metallica Pro (Stern 2013) JPSalas 1.0.1
- Fallout (Original 2024) LTek 2.0.1
- Serious Sam Pinball (Original 2017) JPSalas 4.3.0
- Spirit of 76 (Gottlieb 1975) RajoJoey 1.0.0
- Melody (Gottlieb 1967) Loserman76 1.0.0f
- Hi-Deal (Bally 1975) Leeoneil 1.1.0
- Old Chicago (Bally 1976) Leeoneil 1.2.0
- Hokus Pokus (Bally 1976) Loserman76 1.0.0f
- Amigo (Bally 1974) Teisen 1.0
- Road Race (Gottlieb 1969) Bord 1.0.0
- Triple Action (Williams 1973) Teisen 1.0
- Surf Champ (Gottlieb 1976) GauGau 1.2.0
- Super Spin (Gottlieb 1977) RajoJoey 1.0.0
- Close Encounters of the Third Kind (Gottlieb 1978) RajoJoey 1.2.0
- Star-Jet (Bally 1963) Bord 1.2.0
- Count-Down (Gottlieb 1979) JPSalas 4.0.0
- Jungle Queen (Gottlieb 1977) Wiesshund 4.0
- Skylab (Williams 1974) Ext2k 1.0.0
- Space Walk (Gottlieb 1979) BorgDog 2.0
- Super Nova (Game Plan 1980) HSM 1.0b
- Super-Flite (Williams 1974) EMUnderdogs 1.1.1
- Target Alpha (Gottlieb 1976) Teisen 1.0.0
- Gigi (Gottlieb 1963) EMUnderdogs 1.2
- Retroflair - BAM Edition (PinEvent)

Very likely all the same issue

**Comment by syd711** [comment]
The semicolons are escaped now using the escape character '\'.
Quoting would be also possible, but the escape char felt more lightweight.

**Comment by syd711** [comment]
Fixed with 3.7.2.
