### ISSUE TITLE
[Feature Request] Highlight search results in VPS view

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#527]
> can searchterms be highlighted (dunno color, bold font or smth that fits the look of the tool) in the table overview for easier finding the correct result ?

![image](https://github.com/user-attachments/assets/489868a9-cbf7-4a53-bfde-8a3bda427a94)

**Comment by leprinco** [comment]
linked to #401

**Comment by leprinco** [comment]
fixed in 3.8
