### ISSUE TITLE
[Bug] Windows task bar does not show after exiting Maintenance Mode

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#530]
Repro:

- Start Popper
- Launch Studio 'remote client'
- Enable Maintenance Mode
- Exit Studio : selecting Exit only (do not select to Start Popper)
- Desktop will show without Task Bar

If you open Task Manager you will see that 'Windows Explorer' process is not listed (thus not running). In order to get the task bar back, the user must 'Run New Task' from 'Task Manager' and start "Explorer" TWICE. First launches File Explorer, second launches task bar

**Comment by syd711** [comment]
Fixed with 3.8
