### ISSUE TITLE
[Feature Request] Permanently disable Sticky Keys in Windows OS

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#536]
Would be nice to have a setting in Studio to enable/disable to help Windows users. Sticky Keys never really gets disabled unless you change the Registry (HKEY_CURRENT_USER\Control Panel\Accessibility\StickyKeys :: set to 506)

Even when Windows Accessibility settings show it disabled (Setting>Ease of Access>Keyboard>Use Sticky Key>Turn off)

Sometimes it hoses your game and you must reboot the PC since it locks up the system.

**Comment by syd711** [comment]
Fixed with 3.9.0
