### ISSUE TITLE
VPS Tables, Add last update date filter

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#538]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by leprinco** [comment]
implemented in 3.8 branch
![image](https://github.com/user-attachments/assets/069f5fb2-d5ea-4905-98a9-5c45c3d84c83)

**Comment by syd711** [comment]
Fixed with 3.8
