### ISSUE TITLE
[Feature Request] View and Edit PinVol settings, in bulk or per table.

### ISSUE THREAD

**Issue by Ltek** [syd711/vpin-studio#540]
A table for PinVol settings show all tables, and each PinVol setting per table... with ability to edit each or multiple (maybe checkboxes?) 
You could connect this to the TODO and Validations. I dont think I'd use them with TODO and Validations since I'd need to adjust the settings while at the table, at least at first. But, if the system changes, and you 'know' you need to change the sound volume for all table (or many of them) this bulk editing could be very helpful. For instance, editing 100+ tables all at once to lower/raise the volume on just the backglass because you changed the backglass amp, or something like that.

**Comment by syd711** [comment]
I recently started with SSF and realized how tedious the volume setup can be.
Yes, at least an overview would help to see which tables have been adjusted for the correct volume and balance of stereo and SSF volume.

**Comment by syd711** [comment]
Note to myself: check also the Popper settings for conflict:

> odradek — Today at 5:15 PM
hi, finally i found the issue, i have the custom option VolumeChange=1 in popper. i have to set to VolumeChange=0 so it works properly with PinVol, nothing related to vpinstudio. thanks for your help!

**Comment by syd711** [comment]
Fixed with 3.11.0

**Comment by Ltek** [comment]
nice!
