### ISSUE TITLE
[Bug] Windows 11 - WMIC not enabled by default

### ISSUE THREAD

**Issue by spiralrewind** [syd711/vpin-studio#544]
**Describe the bug**
After installing vpin studio server on a new windows 11 machine, the software just hung up at the splash screen.

after reviewing the server log, the log indicated that wmic could not be run. 

`16-10 09:25:10.199 WARN  [/api/v1/system/info]d.m.v.r.u.SystemUtil - Failed to resolve cpu id: Cannot run program "wmic": CreateProcess error=2, The system cannot find the file specified`

After investigation, it appears that newer installations of windows 11 have wmic disabled by default.
no error messages aside from the server log indicated the problem.

After enabling wmic in Optional Features, everything is running correctly.

I hope this helps someone else
C

**Comment by syd711** [comment]
Funny coincidence. I got my new Window 11 PC from work and noticed the same thing yesterday.
Patch will go out this weekend.

**Comment by spiralrewind** [comment]
great news. hopefully this is an easy one for fix.

Cheers.

**Comment by syd711** [comment]
Fixed with 3.8
