### ISSUE TITLE
Invalid characters problem

### ISSUE THREAD

**Issue by ThePrintz** [syd711/vpin-studio#56]
Working on Norwegian installation and unable to parse the high scores. Reading unknown characters "ÿ".

Log file (parts)
10:57:03.410 [main] INFO  d.m.v.s.s.SystemService - Locale:                          norsk (Norge)
10:57:03.410 [main] INFO  d.m.v.s.s.SystemService - Charset:                         windows-1252

10:57:20.603 [/api/v1/games/scan/32] INFO  d.m.v.s.u.VPXFileScanner - Finished scan of table C:\vPinball\visualpinball\Tables\Tales of the Arabian Nights v4.vpx, found ROM 'totan_14', took 33 ms for 2917 lines.
10:57:20.663 [/api/v1/games/scan/32] INFO  d.m.v.s.g.GameService - Created GameDetails for Tales of the Arabian Nights (Williams 1996)
10:57:20.843 [/api/v1/games/scan/32] INFO  d.m.v.s.h.p.HighscoreParser - Failed to parse highscore string '9ÿ250ÿ000', ignoring segment '9ÿ250ÿ000'
10:57:20.844 [/api/v1/games/scan/32] INFO  d.m.v.s.h.p.HighscoreParser - Failed to parse highscore string '9ÿ000ÿ000', ignoring segment '9ÿ000ÿ000'
10:57:20.903 [/api/v1/games/scan/32] INFO  d.m.v.s.h.p.HighscoreParser - Failed to parse highscore string '9ÿ250ÿ000', ignoring segment '9ÿ250ÿ000'
10:57:20.904 [/api/v1/games/scan/32] INFO  d.m.v.s.h.p.HighscoreParser - Failed to parse highscore string '9ÿ000ÿ000', ignoring segment '9ÿ000ÿ000'
10:57:20.922 [/api/v1/games/scan/32] INFO  d.m.v.s.h.HighscoreService - Saved updated highscore for Tales of the Arabian Nights (Williams 1996)
10:57:20.923 [/api/v1/games/scan/32] INFO  d.m.v.s.h.p.HighscoreParser - Failed to parse highscore string '9ÿ250ÿ000', ignoring segment '9ÿ250ÿ000'
10:57:20.924 [/api/v1/games/scan/32] INFO  d.m.v.s.h.p.HighscoreParser - Failed to parse highscore string '9ÿ000ÿ000', ignoring segment '9ÿ000ÿ000'
10:57:20.924 [/api/v1/games/scan/32] INFO  d.m.v.s.h.c.CardService - Skipped card generation for Tales of the Arabian Nights (Williams 1996), no scores found.
10:57:20.924 [/api/v1/games/scan/32] INFO  d.m.v.s.h.HighscoreService - Skipped highscore change event for "Tales of the Arabian Nights (Williams 1996)" because the no score change for rom 'totan_14' detected.
10:57:20.931 [/api/v1/games/scan/32] INFO  d.m.v.s.u.VPXFileScanner - Finished scan of table C:\vPinball\visualpinball\Tables\Tales of the Arabian Nights v4.vpx, found ROM 'totan_14', took 6 ms for 2917 lines.
10:57:20.947 [/api/v1/games/scan/32] INFO  d.m.v.s.g.GameService - Created GameDetails for Tales of the Arabian Nights (Williams 1996)
10:57:21.097 [/api/v1/games/scan/32] INFO  d.m.v.s.h.HighscoreService - Skipped highscore change event for "Tales of the Arabian Nights (Williams 1996)" because the no score change for rom 'totan_14' detected.

**Comment by syd711** [comment]
Thanks, I'll look into it next week.

**Comment by ThePrintz** [comment]
Perfect, the score card generation is gone as well? Can't find the background settings and card-generation button. I can preview the card but it is not updated (in my case in custom2).

**Comment by syd711** [comment]
Ah, I remember another user reported a similar problem, but i could not really fix it. I thought it's because of the pre-selected font. But your encoding issue might be the root cause. Could you create a separate ticket with the log files and screenshots? That would be really helpful.

**Comment by syd711** [comment]
Regarding the highscore card editor: I accidently removed it. A hotfix for this is on its way.
Regarding the ending problem: Could you try: https://github.com/syd711/vpin-studio/wiki/FAQ ?

**Comment by syd711** [comment]
The link has changed to: https://github.com/syd711/vpin-studio/wiki/Troubleshooting#i-got-encoding-problems-on-my-highscore-cards

I hope it fixed you issue. If not, feel free to re-open this ticket.
