### ISSUE TITLE
[Feature Request] Add todo from VPS link

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#565]
When browsing the VPS for updates, it may not be a proper time for downloading assets (VPU limit reach for instance), so with right click add an automatic TODO comment with the link for download

**Comment by leprinco** [comment]
Done in 3.9
![image](https://github.com/user-attachments/assets/57df835a-8d95-470e-8f7f-5726a7fe8561)

After click on menu link, a //TODO link is inserted
![image](https://github.com/user-attachments/assets/671834d2-aada-4e35-8a1e-a6c5f900b4c1)

**Comment by syd711** [comment]
Fixed with 3.9.0
