### ISSUE TITLE
[Bug] Cannot upload a zipped backglass

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#567]
When uploading a zipped, cf link below, studio detects it is a backglass but goes through table import process then fails

https://vpuniverse.com/files/file/7335-class-of-1812-gottlieb-1991-2-3-screens-directb2s-b2s-db2s/?do=download&r=132238&confirm=1&t=1&csrfKey=2af0fa6aba6801d024c16f4c37293b07

**Comment by syd711** [comment]
Unfinished uploads v2
