### ISSUE TITLE
Unable to restore highscore from backup

### ISSUE THREAD

**Issue by ThePrintz** [syd711/vpin-studio#57]
Trying to restore hiscores from backup. The UI just reverts with no change.
Pictures clearly showing that there is difference in scores.

The log output this;
09:37:48.645 [/api/v1/highscorebackups/restore/264/2023-11-30-22-22-41.hsbckp] INFO  d.m.v.s.h.HighscoreService - Skipped highscore change event for "Addams Family, The (Bally 1992)" because the no score change for rom 'taf_l7' detected.
09:37:48.768 [/api/v1/highscorebackups/restore/264/2023-11-30-22-22-41.hsbckp] INFO  d.m.v.s.h.HighscoreService - Skipped highscore change event for "Addams Family, The (Bally 1992) Bigus1" because the no score change for rom 'taf_l7' detected.
09:37:48.891 [/api/v1/highscorebackups/restore/264/2023-11-30-22-22-41.hsbckp] INFO  d.m.v.s.h.HighscoreService - Skipped highscore change event for "Addams Family, The (Bally 1992) G5k" because the no score change for rom 'taf_l7' detected.
09:37:48.891 [/api/v1/highscorebackups/restore/264/2023-11-30-22-22-41.hsbckp] INFO  d.m.v.s.h.HighscoreService - Setting highscore change events to: false
<img width="867" alt="Skjermbilde 2023-12-01 kl  09 35 53" src="https://github.com/syd711/vpin-studio/assets/71230140/59e97fb0-afd2-46c4-8509-8fdc848af35e">

**Comment by syd711** [comment]
I could reproduce the issue.
The fix will be part of the next update.
