### ISSUE TITLE
Add WOL support

### ISSUE THREAD

**Issue by karlsnyder0** [syd711/vpin-studio#574]
Add Wake-On-LAN support for VPin Studio hosts that go into sleep / stand by mode on a LAN.

- Should work both from Windows and macOS Vpin Studio clients.
- Should work for hosts configured in the connection launcher or with previously discovered clients via. broadcast.

**Comment by Ltek** [comment]
nice idea!

**Comment by Kongedam** [comment]
I'd love to see Wake-on-LAN functionality added to VPin Studio in a future update.

My cabinet is located in my garage, and it would be incredibly convenient to be able to wake it up remotely using VPin Studio itself. Currently, I have to rely on a separate program to do this, which adds an extra step to my setup.

Integrating Wake-on-LAN would streamline the process and make VPin Studio an even more comprehensive solution for managing my virtual pinball setup.

Thanks for considering this request!

**Comment by syd711** [comment]
@karlsnyder0 I close this issue as fixed.
Let's create new tickets if there are follow-ups.
