### ISSUE TITLE
[Feature Request] Support Table Patching

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#575]
> Aetron — Today at 6:38 PM
can you include upload .dif file process.
upload dif
select table
pipe everything into bspatch
copy new table to table folder and keep name
https://github.com/mendsley/bsdiff 

> gorgatron — Today at 7:42 PM
yeah, i presume this is the command line form of this:
https://vpuniverse.com/files/file/2581-vpuremix-system-vppatching-system-vpx-only/
there are a bunch of new tables that use this technique:
https://vpuniverse.com/files/file/22110-attack-from-mars-cabinet-mod/
it can be fiddly and not apply the patch if you don't have the right base file.  you should try the tool and see how to use it -- it isn't a great UI because it is just file selection boxes but we have all the paths right here

same goes for fun house from Gedankekojote97 
https://virtual-pinball-spreadsheet.web.app/game/O1-qbuxg/
yeah and jurassic parc be Supergibson
https://virtual-pinball-spreadsheet.web.app/game/i47o-Nvr/

**Comment by Ltek** [comment]
nice!

**Comment by syd711** [comment]
Duplicates https://github.com/syd711/vpin-studio/issues/584
Fixed with 3.10
