### ISSUE TITLE
VPX Script Editing

### ISSUE THREAD

**Issue by brentgl** [syd711/vpin-studio#576]
Am I having a blonde moment?
I cannot see anything for vpx script editing in either the remote client or on machine. not on the right menu or by right clicking.
Running VPin Studio 3.9.0

Is there something in settings?

Sorry for this
Brent

**Comment by syd711** [comment]
No problem, it is a bit confusing since VPS files are seen as JavaScript files by Windows and trying to be executed.

You have to link .vbs files to an editor of your choice on your operating system..

Workaround: use the internal editor

![image](https://github.com/user-attachments/assets/2ba099c3-ec31-4e29-88d9-9c7a050c3572)

**Comment by brentgl** [comment]
I have changed the default of vbs files to open in notepad for now, but my problem is that I do not have that option on the side bar neither on the actual machine or remote
VPin Studio 3.9.0 - 


![image_2024-11-02_162902812](https://github.com/user-attachments/assets/d17c3d2f-b5e2-4947-8d4e-628d41490aa9)

**Comment by syd711** [comment]
The panel is only available when you have selected a VPX emulator in the toolbar.
Can you post a screenshot of the complete window?

**Comment by brentgl** [comment]
sure here you go - like I said it's probably something silly on my end.  Thanks

![image_2024-11-02_180254974](https://github.com/user-attachments/assets/894b5aac-ac1c-4e2e-bb4b-677b80802d7b)

**Comment by syd711** [comment]
In the preferences, check these settings:
![image](https://github.com/user-attachments/assets/e1fb669f-292f-4a94-9a09-0149b6d7e57f)

**Comment by brentgl** [comment]
as I said - something stupid on my part - ticked and working - sorry for the waste of time :)
