### ISSUE TITLE
[Bug] Upload & replace table loses VPS table

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#577]
**Describe the bug**

upload & replace table loses VPS table -- it looks like it reruns the match and sometimes loses it

**To Reproduce**

Consider the Gargamel Park table (I have run into this a bunch of times with changing version to VR Room but this is an example):

- https://www.vpforums.org/index.php?app=downloads&showfile=15066

1.  Import the table, pick the VPS table (the initial state -- presumably it would be a different version but it doesn't matter for the repro)
2. Drag the table in again and chose to replace the selected table
3. the table data manager comes up and it has lost the VPS table "Gargamel Park" and now shows "VR Room Educational Toyboy (Original 2020)"
4. The common theme is the files have "VR Room" or something similar in the filename: `VR ROOM Gargamel_Park_v1.2.1VR1.0.0.vpx`

**Expected behavior**

- I don't expect it to lose the previous VPS selection at all -- I wonder if it can avoid resetting it?  I am _replacing_ the table so I presume it is the same (except maybe in the oddball case where I am replacing with a "JPs" version, but I would just make a new table in that case)
- it looks like strings of numbers are removed for the match, maybe "VR ROOM" and "VRRoom" should also be removed?

**Screenshots**

<img width="866" alt="image" src="https://github.com/user-attachments/assets/d5773fbe-4a7e-4fd1-a9a9-c74f5a086ca8">

**Desktop (please complete the following information):**
 - OS: macOS 15

**Comment by syd711** [comment]
Good catch, the config flag for the auto-match of the dialog was indeed ignored for all 3x upload types.

**Comment by syd711** [comment]
Fixed with 3.9.1
