### ISSUE TITLE
[Bug] VPS filtering not always consistent -- VPS data may be inconsistent

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#578]
**Describe the bug**

VPS filtering not always consistent -- VPS data may be inconsistent:  a game may be missing its "features" even though the tables have them

**To Reproduce**

Consider "Shooting the Rapids":

- https://virtualpinballspreadsheet.github.io/games?game=5RaindsR7o

In VPin Studio this does not show up under the VR filter, but it does on the VPS website:

<img width="526" alt="image" src="https://github.com/user-attachments/assets/1c64e949-02db-4c27-9c4a-3ed3ffdcb20d">

It looks like VPin Studio uses the features on the game itself for the first pass of filtering, but that is not always a union of the individual entries.  I noticed that there were a couple games where it showed under the VR feature but none of the tables had VR.  Shooting the Rapids is the opposite: the table has it but it doesn't show using the VR filter in VPin Studio.

**Expected behavior**

I am not sure if it is a bug or a feature request but I expect that the filtering would honor the union of the features on the tables (at the game level) as it does on the website.  I do think the VPS data is inconsistent, but maybe the game level feature data should be ignored and computed instead.

**Comment by syd711** [comment]
Yes, we missed to analysize the features of all version here too.

**Comment by syd711** [comment]
Fixed with 3.9.2
