### ISSUE TITLE
Hiscore card template

### ISSUE THREAD

**Issue by ThePrintz** [syd711/vpin-studio#58]
After update I am unable to change the template for hi-score. The "button" on left side is gone. Has it been moved elsewhere?
<img width="142" alt="Skjermbilde 2023-12-01 kl  09 26 57" src="https://github.com/syd711/vpin-studio/assets/71230140/929ab51a-f69d-41b4-9f91-3f9669bd8d97">
<img width="656" alt="Skjermbilde 2023-12-01 kl  09 27 13" src="https://github.com/syd711/vpin-studio/assets/71230140/2000ea5e-65df-4b69-bd52-928d3a677332">
<img width="684" alt="Skjermbilde 2023-12-01 kl  09 27 26" src="https://github.com/syd711/vpin-studio/assets/71230140/6337b98a-d975-4eb7-aad8-b11bb2a8d04e">

**Comment by syd711** [comment]
Caused by an hasty update, I'll fix this ASAP.

**Comment by syd711** [comment]
Fixed.
Patch will come with 2.3.1
