### ISSUE TITLE
VPU Remix Patching Support

### ISSUE THREAD

**Issue by jasoncross** [syd711/vpin-studio#584]
As more table updates (especially the cabinet mod updates by LoadedWeapon) are using the VPU Remix System, it would be great to integrate this functionality with VPin Studio. 

https://vpuniverse.com/files/file/2581-vpuremix-system-vppatching-system-vpx-only/

Potentially useful would be to store the mod file separately so it could be automatically reapplied when the base VPX file is updated.

**Comment by syd711** [comment]
![image](https://github.com/user-attachments/assets/e7abb81b-adb8-4c87-a1bc-19c49deae270)

It is already implemented, but the 3.10 release takes a bit longer than usual ;)

**Comment by jasoncross** [comment]
Sweet!  Does it retain the patch to rematch if the base table updates?

**Comment by syd711** [comment]
Depends on the option you choose, cloning will create a new copy and leaves the original untouched.

**Comment by jasoncross** [comment]
Sorry, let me clarify.  Let's say I patched the VPW version of Diner with the cabinet mod, and then VPW releases an update?  I assume I would need to re-patch.  Just think how cool it would be if the patch files were retained via the VPinStudio so the patch could be automatically re-applied to the updated version?

**Comment by syd711** [comment]
Ah, I see. No, right now we do not manage any assets files that have been downloaded, so these patch files are handled like any other asset.
But we are planing the improve the drop-in folder so that after an installation, files are moved from the drop-in folder into a configurable backup folder.

**Comment by Ltek** [comment]
@syd711 suggestions for DIFF file mgmt:

Naming... <table name>_DIFF.ZIP

Storing the ZIP'd DIFFs...
Directly in the tables folder, so users and Studio "knows" that DIFF was used. 
-or-
In an 'Active Table Patches' folder in the root of the Tables folder.

-

**Comment by syd711** [comment]
Fixed with 3.10

The handling of the diff are not scope of this ticket.
See https://github.com/syd711/vpin-studio/issues/596
