### ISSUE TITLE
smb rom marked invalid -- vpinmame says ok

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#595]
**Describe the bug**
smb rom marked invalid -- vpinmame says ok

**To Reproduce**

There is a validation error showing in VPin Studio saying that the `smb` rom is invalid:

<img width="2203" alt="image" src="https://github.com/user-attachments/assets/6f318a46-9724-498d-838d-c05b19763a31">

but when I run vpinmame ([v3.6.0-1122-79a301d](https://github.com/vpinball/pinmame/releases/tag/v3.6.0-1122-79a301d)) on it, it says ok:

<img width="405" alt="image" src="https://github.com/user-attachments/assets/71829383-e783-4907-8431-dd66aedd1d70">

[vpin-studio-logs.zip](https://github.com/user-attachments/files/17783293/vpin-studio-logs.zip)

**Expected behavior**

Should agree with vpinmame

**Comment by syd711** [comment]
Can you attach the rom here?

**Comment by syd711** [comment]
Since this is a Gottlieb ROM, it is not listed for download.

**Comment by syd711** [comment]
![image](https://github.com/user-attachments/assets/42bb13ce-717d-4aae-a298-0fced6b9f3c4)

you tested with 32-bit or 64-bit?

**Comment by gorgatron1** [comment]
I just tried with the 32 bit vpinmame and it also shows `smb` as OK.

**Comment by syd711** [comment]
Odd, I've tested with both and both show show the same error.
I will "soften" the validator message. If there are a few false positives, one can still discard this message.

**Comment by syd711** [comment]
Fixed with 3.11.0
