### ISSUE TITLE
[Bug] Revisit b2s server location

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#597]
> OrdeS — Today at 9:55 AM
I'm also having an issue with B2S server location. I used to have it in a versioned location but once I moved up few versions I realized it was not a good idea to keep piling them up so I removed the version from the folder and its now in: c:\vPinball\VisualPinball\B2SServer where it is properly registered and working, but VpinStudio still thinks its in the previous location c:\vPinball\VisualPinball\B2SServer-2.1.1-win
Using studio 3.10.0 fyi

**Comment by leprinco** [comment]
not a bug
