### ISSUE TITLE
[Bug] Update server from remote client 

### ISSUE THREAD

**Issue by leprinco** [syd711/vpin-studio#598]
on remote client, connecting to a server, the update dialog controller was using the current localhost client then getting a null server version
![image](https://github.com/user-attachments/assets/305662bf-f119-483d-aa7d-6a796a74c72c)

**Comment by leprinco** [comment]
fixed in main for 3.10.1

**Comment by syd711** [comment]
Ah, thank you so much. That was giving me a headache.

**Comment by syd711** [comment]
Fixed with 3.10.1
