### ISSUE TITLE
NVOffset validator is too strict

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#599]
**Describe the bug**

NVOffset validator is too strict -- complains about setting for two games for the same table

**To Reproduce**

Consider this:

<img width="2203" alt="image" src="https://github.com/user-attachments/assets/22259674-33af-4582-9e86-70bd5e8726d9">

I have 4 cc_13 tables:

- Cactus Canyon Continued (LW), NVOffset=2 (selected in screenshot)
- Cactus Canyon Continued (VPW), NVOffset=2
- Cactus Canyon (VPW), NVOffset=2
- Cactus Canyon (VPW + DarRDog), NVOffset=2

The validation shows: NVOffset = 2 but Cactus Canyon Continued (VPW) also has the NVOffset 2

In my opinion this is correct -- both games are for table https://virtualpinballspreadsheet.github.io/?game=gBpX0hxi&fileType=table so they _should_ have the same NVOffset.

I think the uniqueness of NVOffset should be for:

- same rom
- different tables (game=XXX)

**Comment by syd711** [comment]
Fixed with 3.10.1
