### ISSUE TITLE
Drop In Folder - Install Automatically?

### ISSUE THREAD

**Issue by jasoncross** [syd711/vpin-studio#608]
I'm a bit confused about the drop-in folder.  Under settings it says "In checked, archives downloaded into the selected drop-in folder will be imported once the download is finished."  This seems to indicate that it auto-imports items dropped in.  When I add items to the folder, it shows a star next to the Drop-In Assets button, but I still need to click to install them directly.  Should they be auto-installed?

**Comment by syd711** [comment]
No they don't, the text is misleading. The auto-appear inside the dropdown menu.
They should not be installed automatically. 

Since I'm not a native speaker, here is the is the corrected version:
> If checked, new files of the selected drop-in folder will be shown in the menu once the download is finished.

**Comment by syd711** [comment]
Fixed with 3.10.2
