### ISSUE TITLE
[Change Request] Icons on Asset Manager

### ISSUE THREAD

**Issue by brentgl** [syd711/vpin-studio#613]
As seen from the screenshot below:
![Screenshot from 2024-11-20 11-30-00](https://github.com/user-attachments/assets/9478769d-7399-4d16-9b6d-20d978d29990)

Can the missing items be changed to something other than a greyed-out picture icon? It's not easy to see the missing ones when scrolling through. A red icon or X may be something that differentiates them easily.
Or is this something that can be done myself?

Thanks
Brent

**Comment by syd711** [comment]
No, but you made a good point here. I'll improve this.

**Comment by syd711** [comment]
![image](https://github.com/user-attachments/assets/a7fc27f7-d40f-4130-9fca-4e9de439c9cf)

The icons are darker know, the new color comes with the next patch.

**Comment by brentgl** [comment]
looks a lot better.  Nice One.
