### ISSUE TITLE
[Bug] Last Updated not Updating

### ISSUE THREAD

**Issue by jasoncross** [syd711/vpin-studio#617]
The last update column in the table list doesn't seem to populate on any of the tables.

![VPIN_Last_Update](https://github.com/user-attachments/assets/a1097da6-0a5a-4cb3-b701-6340b4a83638)

**Comment by syd711** [comment]
Yes, I noted that too and fixed it. Comes with the next update.

**Comment by syd711** [comment]
Fixed with 3.10.3
