### ISSUE TITLE
[Bug] Tables not showing up in table list

### ISSUE THREAD

**Issue by apophis79** [syd711/vpin-studio#621]
**Describe the bug**
I just installed VpinStudio (full installer) on my cab and I am not seeing any tables listed. I use PinballY and I have an unconventional folder structure. My guess is that VpinStudio just doesn't know where to look on my system.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - PinballY 1.1.0 beta 10

**Additional context**
 - Logs:
    [vpin-studio-ui.log](https://github.com/user-attachments/files/17920683/vpin-studio-ui.log)
    [vpin-studio-server.log](https://github.com/user-attachments/files/17920764/vpin-studio-server.log)
 - VPX folder location:  C:\VisualPinball
 - Tables folder:   C:\VisualPinball\Tables
 - VpinMame folder:     C:\VPinMAME

**Comment by syd711** [comment]
@leprinco Altough looking like a PinballY issue, I assume the issue is caused by the MAME setup, which is valid, but not "standard". I'll take a look.
