### ISSUE TITLE
[Bug] Patched table was not placed in subfolder if the origin table is imported as subfolder

### ISSUE THREAD

**Issue by dsync89** [syd711/vpin-studio#622]
Table that is patched and cloned to a table that was previously imported as subfolder won't be placed in a new subfolder name.

The original table path and folder structure before patch.
![image](https://github.com/user-attachments/assets/b919a0e1-68d2-4ed2-95d7-7793e8606279)

Patching

![image](https://github.com/user-attachments/assets/92c3423d-3905-4572-828e-6ea1bb53b90d)

After patching

![image](https://github.com/user-attachments/assets/0af35b66-d91f-4c17-9bc0-e0797104d358)

## Expected Outcome

The patched folder should reside in a new subfolder with an appended name, e.g. [Patched], instead of the same folder as the origin table. Vpin Studio probably assume a non-subfolder path by default.

## Current Workaround

To workaround this, I still follow the patch and clone method, but have to move the patched table elsewhere and reimport again as subfolder.

**Comment by syd711** [comment]
Good catch, fix comes with the next release.

**Comment by syd711** [comment]
Fixed with 3.10.3
