### ISSUE TITLE
[Bug] Table Data Manager Edit Dialog buttons cut-off if the game screen name is too long

### ISSUE THREAD

**Issue by dsync89** [syd711/vpin-studio#624]
Just decided to try out a descriptive name following the naming convention from a torrent VPX packs as the game screen name, but noticed the buttons will be cut off if it's too long.

Game screen name example:

**Big Trouble in Little China (Original 2022)(Balutito, TeamTuga)(1.8)[Source Table Wrath of Olympus JPSalas][PuP-Pack]**

![image](https://github.com/user-attachments/assets/02853f14-d8a6-45c6-bba3-3928049a7e5b)

**Comment by syd711** [comment]
Fixed with 3.10.3
