### ISSUE TITLE
[Bug] Loading tables: java.lang.NullPointerException - Client error when 3.10.3 remote client opens

### ISSUE THREAD

**Issue by beit-no1** [syd711/vpin-studio#643]
As per our Discord discussion I recently updated to 3.10.3 and immediately after an addition of a table I'm now getting a Java NullPointer exception when I open the remote client.  I have to ok the error and then all appears to function.  I noticed that after loading more tables I got what appeared to be an exception per each table.

My server is on Windows 10 pro and has most all updates applied.. My remote clients are both Windows 11.

I have attached what I believe are the server logs you were looking for

![Screenshot 2024-12-04 212242](https://github.com/user-attachments/assets/76277b75-177d-41ca-b3d9-490d8da68aa3)
[vpin-studio-server-logs.zip](https://github.com/user-attachments/files/18016518/vpin-studio-server-logs.zip)

**Comment by beit-no1** [comment]
[VPin-Studio-Client.zip](https://github.com/user-attachments/files/18031224/VPin-Studio-Client.zip)
Here is the log file zip from one of my two local clients... if this is not sufficient then I can get from the other, but I'm receiving the error on both clients.

**Comment by beit-no1** [comment]
No longer getting the issue with 3.10.4 now after update

**Comment by syd711** [comment]
Nice, thanks for the feedback!
