### ISSUE TITLE
No High Scores with The Bally Game Show

### ISSUE THREAD

**Issue by CrushedByCode** [syd711/vpin-studio#645]
Highs scores cannot be read because table uses ROM "gs_lu4"

Table is PGQ7zs8u

[https://www.vpforums.org/index.php?app=downloads&showfile=15288]

The list of nvram's supported includes:

gs_l3
gs_l4
gs_la3
gs_lg6
gs_lu3
gs_lu3 <--- this entry is in the list twice. I wonder if it is supposed to be gs_lu4

Perhaps it isn't supported but wanted to submit this just in case the list itself was the problem, not the .nv file.

**Comment by syd711** [comment]
Good catch, the system output here is not correct from pinemhi.
I added a test and realized I've also forgotten to add the latest +50 new ROM from pinemhi.

The database has been updated. Since this database file is updated on server start, I resolve this ticket as fixed.
