### ISSUE TITLE
[Bug] macOS client fails to show release notes after update (last two releases)

### ISSUE THREAD

**Issue by gorgatron1** [syd711/vpin-studio#654]
**Describe the bug**
macOS client fails to show release notes (error) after update (last two releases)

**To Reproduce**

Update the macOS client + server via the UI.  After the client comes back up (correctly now for these last two releases, yay!) I get an error displaying the release notes:

<img width="2203" alt="image" src="https://github.com/user-attachments/assets/f36954e7-4a1f-4567-bcb8-f4c37185b98c">

client log:

[vpin-studio-ui.log](https://github.com/user-attachments/files/18071109/vpin-studio-ui.log)

**Expected behavior**

Release notes are shown

**Comment by gorgatron1** [comment]
Aside from this the client seems to be working perfectly!

**Comment by syd711** [comment]
There is the Windows shortcut to reopen the dialog with CTRL+ALT+U.
I don't know what is the matching one on macOS, but does it work to reopen it this way?
The log tells me that there was a connection error, but it's odd that this happend twice.

**Comment by syd711** [comment]
@gorgatron1 

I close this ticket for now. Feel free to reopen it when the error remains.
