### ISSUE TITLE
[Bug] Wrong name in PUPACK DATA for GREASE tables

### ISSUE THREAD

**Issue by djfraleo** [syd711/vpin-studio#662]
**Expected behavior**
For tables using vpinmame ALIAS, the name in PUPACK DATA should display the ALIAS name, not the original ROM, if a pupack with an ALIAS name exists.

**Screenshots**
![image](https://github.com/user-attachments/assets/445d2a00-ff87-4c16-bd69-587d58b54543)

**Desktop (please complete the following information):**
 - OS: win 11 PRO
All vpx systems upgraded by vpinstudio to latest VPXRC6 at 16/12/2024

**Additional context**
Grease pupack has Options on bat file, but cannot select the file because of the incorrect name.

**Comment by djfraleo** [comment]
Yes, the same bug is for altsound and altcolor. 

For altcolor, it seems it doesn't matter if name is upper or lower case. Serum altcolor name is Grease

**Comment by syd711** [comment]
I'm  a bit confused here.
I've installed the table + pup pack and added the alias as documented with

> grease,elvis

The PUP pack section shows "grease", which is the correct name, but not the correct folder name.
I will add a second label for this. 

![image](https://github.com/user-attachments/assets/86152520-f150-47a6-8fbe-2da0d13549ec)

The "Option Selector.bat" which can be called is an interactive one which is not supported by the Studio.
So I'm not sure how you managed it to get "elvis" as PUP name if you have added "grease" as alias.

**Comment by djfraleo** [comment]
On older tables, it has elvis rom definition, without any alias.

So, I added the code for the alias and volilá!. It worked on pinup popper.
Buy the VPIN Sutudio didn't catch the update.

[cid:8e0d5bc3-a907-4f8e-8edd-d8f514ff0967]

So, if I make this kind of corrections, updating the table view, and Scannig the rome name AGAIN, should catha te corrected alias or rom, anch change pups accordingly. It doesn´t do that. You need to correct the bug.

To repeat the error, try enabling line 135 and disabling the grease alias line, and see if VPIN catch the folder name (should be elvis instead of grease)

This is important when we had several pup for the same table (perhaps in other language like the flintstones, or B/W show, cartoon, and movie pup like Adams Family or ninja turtles, or transformers)
________________________________
De: Matthias Faust ***@***.***>
Enviado: miércoles, 18 de diciembre de 2024 08:50 a. m.
Para: syd711/vpin-studio ***@***.***>
Cc: DJFRALEO ***@***.***>; Author ***@***.***>
Asunto: Re: [syd711/vpin-studio] [Bug] Wrong name in PUPACK DATA for GREASE tables (Issue #662)


I'm a bit confused here.
I've installed the table + pup pack and added the alias as documented with

grease,elvis

The PUP pack section shows "grease", which is the correct name, but not the correct folder name.
I will add a second label for this.

image.png (view on web)<https://github.com/user-attachments/assets/86152520-f150-47a6-8fbe-2da0d13549ec>

The "Option Selector.bat" which can be called is an interactive one which is not supported by the Studio.
So I'm not sure how you managed it to get "elvis" as PUP name if you have added "grease" as alias.

**Comment by syd711** [comment]
Fixed with 3.11.1
