### ISSUE TITLE
Service installations issues

### ISSUE THREAD

**Issue by lonestarpinball** [syd711/vpin-studio#68]
**Describe the bug**
Apparently it expects my popmedia folder to reside within the pinup system folder, mine is on a separate drive. And it expects the AutoStart folder to be under a user folder with the same name as my computer name. There is no user with that name, so there is no vpin-studio-server.bat anywhere. 

**To Reproduce**
Try to install the service after the install on my computer

**Expected behavior**
For it to act as it does in the install video you have on youtube. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] chrome
 - Version [e.g. 22] 120.0.6099.72 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by syd711** [comment]
Hi there! Thank you for your request.
Since there have several issues with the autostart batch file, I will change the installer accordingly.

Regarding your media folder: I indeed didn't assume someone changed this default configuration.
Just to be sure, you changed the "Media Dir" for the emulator, right?

![image](https://github.com/syd711/vpin-studio/assets/1169826/47c842be-df1d-4054-bb3c-7ef02a06e29e)

I'll fix this, most likely already this week.

**Comment by lonestarpinball** [comment]
Correct irt changing the location of popmedia, I changed it because of space,

**Comment by syd711** [comment]
Version 2.5.0 has just been released and (hopefully) fixes your issues.
Download the latest installer and try again. Let me know if its working.

**Comment by lonestarpinball** [comment]
Same issue where there is no batch file in the auto start folder. But no w
at least I can get it to look in a different folder   . I’d create it
myself if I knew what was supposed to be in it

**Comment by syd711** [comment]
Ok, thanks for your feedback! I'll close the ticket then.

**Comment by lonestarpinball** [comment]
You may not have read my feedback, this is not resolved, just different. it
now points to the correct folder for autostart, but no
"vpin-studio-server.bat" is in that folder. if you tell me what is supposed
to be in that batch file, i can make it myself. i have tried using a
renamed "server.bat" from the application's folder but it gets stuck
attempting to make initial contact.

**Comment by syd711** [comment]
I misread your ticket indeed and I'm very sorry for that!

I documented the process now in case other users having this problem too.
I hope this description will fix your issue:
https://github.com/syd711/vpin-studio/wiki/FAQ#there-is-no-bat-file-in-the-auto-start-folder
