### ISSUE TITLE
Server installation failed

### ISSUE THREAD

**Issue by adstotz** [syd711/vpin-studio#71]
When performing a fresh full install and progressing to the step of "Install Service", there is an error received:

"Error: File 'C:\Users\<myuser>\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup' exists but is a directory.

<myuser> here is the correct user directory for my system.

 - OS: Windows 11 Pro
 - Version: 23H2

**Comment by syd711** [comment]
Thanks for reporting! Could you attach the log files here? I'm planning a release this week so I can include the bugfix for this.

**Comment by syd711** [comment]
Also, the workaround for the problem can be found here:
https://github.com/syd711/vpin-studio/wiki/Troubleshooting#there-is-no-bat-file-in-the-auto-start-folder

**Comment by adstotz** [comment]
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/13787144/vpin-studio-ui.log)

It looks like the code is maybe not appending the filename to the directory when opening the file output stream?

**Comment by syd711** [comment]
Ah, right, I added additional lookup methods for the auto-start directory with the latest release. For these, the actual filename is not appended.

**Comment by syd711** [comment]
I just released https://github.com/syd711/vpin-studio/releases/edit/2.6.0 which should fix this issue.
Please reopen this ticket if there are still problems.
