### ISSUE TITLE
no highscore cards will be issued

### ISSUE THREAD

**Issue by GerhardPK** [syd711/vpin-studio#73]
if i usE "highscore settings" i see  "Error"
i found this in the log file 
[/api/v1/cards/generatesample/725] ERROR d.m.v.s.h.c.CardService - Failed to generate overlay: argument "content" is null

**Comment by syd711** [comment]
Hi there!

Thank you for reporting the error! 

Can you attach the .log files located in the installation folder here?
Does the error happen when you try to generate a card in the "Highscore Card" section?

**Comment by GerhardPK** [comment]
[vpin-studio-server.log](https://github.com/syd711/vpin-studio/files/13795302/vpin-studio-server.log)
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/13795303/vpin-studio-ui.log)
thanks for the prompt answer. 
The Error is in the "Highscore card settings"
![Screenshot 2023-12-29 185253](https://github.com/syd711/vpin-studio/assets/155166726/af0f3eb5-023c-4db0-8b53-d5568e8c544e)
thanks for your help.
by the way - cool program

**Comment by syd711** [comment]
Thanks! And thank you for sending the log files. I'll take a look and get back to you!

**Comment by syd711** [comment]
I could reproduce and fix the issue.
The bugfix will be included in the next release.

**Comment by GerhardPK** [comment]
Hello,
thanks for working. So i will wait.
My best wishes, happy new year
gerhard

________________________________
Von: syd711 ***@***.***>
Gesendet: Samstag, 30. Dezember 2023 15:54
An: syd711/vpin-studio ***@***.***>
Cc: GerhardPK ***@***.***>; Author ***@***.***>
Betreff: Re: [syd711/vpin-studio] no highscore cards will be issued (Issue #73)


I could reproduce and fix the issue.
The bugfix will be included in the next release.

**Comment by syd711** [comment]
Hallo and a Happy New Year to you too!
The issues should be solved with 2.7.0.
Reopen this ticket if the problem still occurs.

**Comment by GerhardPK** [comment]
Hi,
enclosed copy of my logfiles.

grüsse aus dem saarland
gerhard

**Comment by syd711** [comment]
Soo...ich hoffe mit 2.10.0 ist das Problem behoben.

**Comment by syd711** [comment]
Hat dann doch eine Runde länger gedauert :-/
Der Fix ist in 2.10.1 enthalten, welches heute released wurde.

**Comment by GerhardPK** [comment]
Das eintragen der tables funktioniert gut. danke

mit den highscorecards bin ich noch am testen. dieses schreiben der neuen card
mit geändertem score nach ende des tables scheint noch nicht zu funktonieren (bei mir). Gehe mal die
verschiedenen highscore arten durch und melde mich nächste woche.

ps wenn ich die Karten vom client generell generiere scheint die Änderung berücksichtigt.

Deine Arbeit ist super, das Programm klasse

gerhard

________________________________
Von: syd711 ***@***.***>
Gesendet: Sonntag, 21. Januar 2024 15:01
An: syd711/vpin-studio ***@***.***>
Cc: GerhardPK ***@***.***>; Author ***@***.***>
Betreff: Re: [syd711/vpin-studio] no highscore cards will be issued (Issue #73)


Hat dann doch eine Runde länger gedauert :-/
Der Fix ist in 2.10.1 enthalten, welches heute released wurde.
