### ISSUE TITLE
Hiscore card and overlay placement

### ISSUE THREAD

**Issue by ThePrintz** [syd711/vpin-studio#74]
Wish for option to manually place hiscore pop-up card and overlay. I am playing on rotated display and all overlays and pop-up comes up on playfield in wrong size, rotated and in wrong location.

Is it possible to add some user setting for these? Ex. placement x, y and width/height?

**Comment by syd711** [comment]
I'll start with the rotation option for both first., should be quick-win.

Regarding the overlay positioning: since the overlay is fullscreen to rotation option should be sufficient.
Regarding the highscore card positioning: I'm planning a bigger overhaul there anyway, adding some more option. These include the positioning and also the included options in this pop-up. So it will be possible, but this will come a bit later.

**Comment by syd711** [comment]
The rotation option has been added and will come with the next update.
I leave this ticket open until there are news about the positioning options.

**Comment by ThePrintz** [comment]
Thank you, great service and great software!
The scorecard is now rotated but I need no place it differently on the screen as part of hi-score is not visible. See picture.
The overlay is not rotated (but I don't use this feature).
Need a way to move the scorecard on screen and maybe set width and height? 
Possible?

Best,


<img width="676" alt="Skjermbilde 2024-01-05 kl  23 28 29" src="https://github.com/syd711/vpin-studio/assets/71230140/617df20d-b2ca-4ff2-b2b5-5e789aec3731">
<img width="676" alt="Skjermbilde 2024-01-05 kl  23 28 19" src="https://github.com/syd711/vpin-studio/assets/71230140/05cfc714-a1e7-4b76-a278-ff535e354a7e">

**Comment by syd711** [comment]
Ah, thank you for the screenshots, these are helping indeed.
The idea is that I use the Popper Screen configuration. So you position e.g. Other2 and the highscore card will pick up the location, size and rotation of that screen. I will add this in one of the next updates.

Regarding the score board. I'll check if simply rotating with fullscreen will do the trick.

**Comment by syd711** [comment]
The highscore card issues are fixed with version 2.9.0.
Regarding the rotation of the overlay: I've opened https://github.com/syd711/vpin-studio/issues/90 to handle this in a separate ticket.

**Comment by syd711** [comment]
Thanks, it was more tedious as expected, but I hope everything works as expected.
