### ISSUE TITLE
Highscore PINemHi

### ISSUE THREAD

**Issue by GerhardPK** [syd711/vpin-studio#76]
I'm testing the high score function for VPX. It would be very helpful if there was a note in the tablelist that the romfile is supported by PINemHi. Or does it mean that when a card  is created (generate all) , PINemHi is also supported??
gerhard Krill

**Comment by syd711** [comment]
If a table highscore is not supported by pinemhi, a message is shown in the highscore section of the table overview.
So yes, if a card is generated, it is supported. But note that there are other highscore score types: https://www.youtube.com/watch?v=Nv5CwiXmnEQ&ab_channel=VPinStudio

The tricky part is to determine the correct ROM name for a table or the correct name of the highscore file. While the Studio tries to resolve these automatically, there may be tables where it does not work and you have to set the ROM name in Popper or Studio manually.

Feel free to re-open the ticket if you have any more question. But I hope the video explains it properly.
