### ISSUE TITLE
Unable to connect from the client to server over OpenVPN

### ISSUE THREAD

**Issue by maestro7879** [syd711/vpin-studio#78]
**Describe the bug**
Unable to connect from the client to server over OpenVPN

**To Reproduce**
1. Connect OpenVPN remotely, I can ping the pinball machine successfully.
2. Add IP to client and attempt to connect. Program hangs.

**Expected behavior**
Client connects to pinball machine (server)

**Additional context**
This link used remotely shows a game list, connectivity is there.  - http://192.168.50.218:8089/api/v1/games/knowns

Client logs - 
[vpin-studio-ui.2024-01-02.log](https://github.com/syd711/vpin-studio/files/13821371/vpin-studio-ui.2024-01-02.log)
[vpin-studio-ui.log](https://github.com/syd711/vpin-studio/files/13821370/vpin-studio-ui.log)

**Comment by syd711** [comment]
I thinks its because the media preview is enabled by default. So when the UI is opened, the media for the first table are immediatly streamed. I imagine this causes heavy load on the VPN connection.

I recommend to disable the preview on your cabinet and try to connect again.

**Comment by maestro7879** [comment]
> I thinks its because the media preview is enabled by default. So when the UI is opened, the media for the first table are immediatly streamed. I imagine this causes heavy load on the VPN connection.
> 
> I recommend to disable the preview on your cabinet and try to connect again.

Same issue with it disabled.

**Comment by syd711** [comment]
Mmh, trying to reproduce this is a bit more effort. Could you first also append the server log?

**Comment by maestro7879** [comment]
> Mmh, trying to reproduce this is a bit more effort. Could you first also append the server log?

I'll get that. One thing I do see is that the client isn't reaching out to the server IP. Verified using Wireshark. I will double check that though. It is using 192.168.2.x as the client and 192.168.50.x for the server. Not sure if the IP is doing something odd in that configuration.

**Comment by syd711** [comment]
There is the option to hard-code the IP address in the framework which I'm using. I'll check if I can expose this flag, so one can assign an alternative IP for the startup.

**Comment by maestro7879** [comment]
With 2.90 this is now working. Thanks !
