### ISSUE TITLE
Highscore Refresh Bug - Filename mismatch

### ISSUE THREAD

**Issue by adstotz** [syd711/vpin-studio#79]
I have a Medieval Madness table that I renamed (display name and file name) after importing to VPin Studio. This left me with PinUP Popper Table Settings of:
Game Name: 1455577933_MedievalMadness_Upgrade(Real_Final)
Game Display Name: Medieval Madness
Game File Name: Medieval Madness.vpx

When the highscore card media is generated, it is not being picked up correctly as the "Other2" media in the table. I'm wondering if there is a mismatch between the filenames being generated for the media and the lookup name of the table to associate that file with?

My other Leprechaun King table seems to work:
Game Name: Leprechaun King (Orbital 2020)
Game Display Name: Leprechaun King
Game File Name: Leprechaun King (Orbital 2020).vpx

**Comment by syd711** [comment]
Ah, thank you. I got another similar ticket yesterday and tried all evening to reproduce that. This seems to point me in the right direction. I get back to you soon!

**Comment by syd711** [comment]
I picked the wrong target name for the card generation.
The issue will be fixed with 2.8.0
