### ISSUE TITLE
Missing github ci build

### ISSUE THREAD

**Issue by francisdb** [syd711/vpin-studio#8]
`mvn clean test` fails here

Would be great if everything at least builds on win / mac / linux and has a matrix github ci build for every pr / commit to main.

This also means no dependencies on existing file structure outside the project dir

**Comment by syd711** [comment]
Yes, I'm aware of this pile of shame. Right now the test are more or less some tooling utils but far away from production. I can't say when or if this ever will reach a "production" state as this is a one-man show and I'm usually more focussed on new features than technical debts (except bugs).

**Comment by francisdb** [comment]
I might be able to help but but let me first try to talk to you on discord

**Comment by francisdb** [comment]
Not a pile of shame, great tool. Just not ready for other ppl to get involved.

**Comment by syd711** [comment]
There is a embedded testsystem available now. I haven't deleted my local environment to check if there are still hidden references, but I think I covered everything.

**Comment by francisdb** [comment]
still not compiling on mac here:

```
UnsatisfiedLinkError: 'java.lang.Integer org.jnativehook.GlobalScreen.getAutoRepeatRate()'
```

What is that used for?

**Comment by syd711** [comment]
Looks like it belongs to JavaFX? I tried stackoverflow, but since I can't reproduce it without a mac its tricky for me.

**Comment by francisdb** [comment]
Strange that this fails on the server module

<img width="804" alt="image" src="https://github.com/syd711/vpin-studio/assets/161305/b9e47324-a95d-48ac-b0a7-195ee7f7c9a8">

**Comment by francisdb** [comment]
anyway, don't have the time to look into this now
