### ISSUE TITLE
High scores shown in pinup popper shown before launching the game.

### ISSUE THREAD

**Issue by maestro7879** [syd711/vpin-studio#81]
While browsing for a game to play in pinup popper it would be nice to have something that shows the high scores of the game before launching the game. (This might be possible already and I'm missing it)

**Comment by syd711** [comment]
Yes, this is already part of pinup popper. I only provide the highscore as an asset for another Popper screen.
E.g. you can bind the Other2 screen in the controller section. If you configured the screen correctly, you can invoke the scores for the selected game before launching it.
See also: https://www.nailbuster.com/wikipinup/doku.php?id=other_settings

I close this ticket then.
