### ISSUE TITLE
Persist upload folder location

### ISSUE THREAD

**Issue by syd711** [syd711/vpin-studio#82]
Do not only remember the latest used folder in memory, but also store it in the preferences.
Most users will simply always use their downloads folder, so this will save a lot of time.

**Comment by Kongedam** [comment]
Maybe change the behavior on how to upload files
Today I have to push "Upload", then "select file" and "Upload" one more time

![Asset uploading](https://github.com/syd711/vpin-studio/assets/3888787/095d6f83-d33c-4692-a906-12a5de2306f6)

Why not show "select media" as soon as you press "upload" first time
and when you press "open" then it should just load it
it would save the user for 2 steps

**Comment by syd711** [comment]
Resolved.
Included in 2.9.0.
