### ISSUE TITLE
Option to dismiss the OK confirm to launch table from VPS

### ISSUE THREAD

**Issue by bele20097** [syd711/vpin-studio#86]
It would be much more convenient to have the OK button selected by default in the confirmation dialog for launching a table so we can just hit ENTER instead of reaching out for another mouse click.

or better, have an option to « ignore for future launch » or settings in the App.

thanks

**Comment by syd711** [comment]
For confirmation dialogs, the submit button has the focus now.
The VPX table start dialog has a "Do not show again" checkbox now.

Fixed with hotfix 2.8.1

**Comment by bele20097** [comment]
Thanks for this awesome program and your prompt attention to bugs and suggestions!
