### ISSUE TITLE
VPINMAME Flags not reloaded on SCAN

### ISSUE THREAD

**Issue by bele20097** [syd711/vpin-studio#88]
When  we get a warning ALT sound or ALT color not enabled, launching the table, F1 then setting up Alt Color and Alt Sound properly, VPS still complains they are not enabled.

VPINMAME flags should be reloaded when we do a SCAN for the table. I have to manually add these flags in the VPin Mame tab to remove the warning.

![image](https://github.com/syd711/vpin-studio/assets/8573463/5a5b02ee-dad3-4515-9a16-8a69d0530fec)

![image](https://github.com/syd711/vpin-studio/assets/8573463/cecf8683-3c23-444a-ae93-482adca95dbe)

**Comment by syd711** [comment]
Right, these values are cached and this cached is not resetted on res-scan.
Will be fixed.

**Comment by syd711** [comment]
Fixed.
Will be part of version 2.9.0.
