### ISSUE TITLE
Improved Virtual Pinball Spreadsheet Integration

### ISSUE THREAD

**Issue by yoshi98bc** [syd711/vpin-studio#96]
I was wondering if you could add a feature that gives the ability to compare tables I have installed on my vpin to what is available on virtualpinball spreadsheet.  It doesn't need to be the various tables versions that are available for each table just that the game is installed.  This way I can see what games are available that I do not have.  It would help to catalog all installed tables versus all available tables on the spreadsheet.  I think this would be a useful feature.

**Comment by syd711** [comment]
Mmmh, I'm not sure about this. Right now there are over 1700 tables on VPS. If you want to "collect", yes, that would come in handy. But I usually try to improve the management of a single table. If the VPS guys add some analytics data one one day, it would be intesting to compare if you got all the (e.g.) TOP 100 downloaded tables. Or do you really try to install all tables that are available out there?

**Comment by yoshi98bc** [comment]
I am not trying to install all the tables.  I am just looking for an easier way to see what is available versus what I have installed.  I know that there is a downloadable excel document but it is constantly updated so its obsolete after you download it.  And the virtualpinball spreadsheet is great but not the most user friendly when looking at what is available.  I find it easier to use when I know what table I want.  When you have a lot of tables it can be a little difficult to remember all you have.  

And I agree on the Top 100 downloaded tables.  That would be a great feature.

**Comment by syd711** [comment]
I see. I can add a view which includes all VPS tables, including an "installed" marker. I put it on the list.

**Comment by yoshi98bc** [comment]
That would be great

**Comment by syd711** [comment]
The first version is coming with 2.11.0.
Feel free to write additional tickets with improvements.

**Comment by yoshi98bc** [comment]
Nice. Thanks
