### ISSUE TITLE
Closing VPIn client launches Popper on cabinet

### ISSUE THREAD

**Issue by yoshi98bc** [syd711/vpin-studio#97]
Whenever I close VPin Studio client on my laptop pinup popper starts up on my cabinet.  Is there a setting to turn this feature off?  Or is this a bug?

**Comment by syd711** [comment]
It is intended. Because it is likely that the VPin Server process has to kill all Popper processes to be able to write some data, I simply restarted Popper again on disconnect. But I get that this may be annoying and will add a settings for that.

**Comment by syd711** [comment]
I added a checkbox for this in the preferences, will come with the next update.

**Comment by syd711** [comment]
Fixed with 2.10.1
