### ISSUE TITLE
Quick navigation via keyboard

### ISSUE THREAD

**Issue by ordes** [syd711/vpin-studio#98]
It would be nice if one could use keyboard to quickly navigate to a letter in a long list, just as you can in Pinup popper games manager. 
Long list of games make for too much scrolling to get to the right game as is.

**Comment by syd711** [comment]
Haha, really: I had exact the same idea YESTERDAY!
Will do!

**Comment by syd711** [comment]
Will be part of 2.11.0, coming this week.
