### ISSUE TITLE
Updating tables 

### ISSUE THREAD

**Issue by yoshi98bc** [syd711/vpin-studio#99]
I am not sure if this is possible with the current release but does vpin studio allow you to update the table in pinup popper. 

Popper has an update button in game manager that allows you to drag a new table to it and it will update all the files for that table to match. Does your program offer this? I would love to be able to do this remotely. 

Thanks

**Comment by syd711** [comment]
There are several way to update your table and it's data:
- You can use the upload button from the toolbar to upload a new VPX file of an existing table. You can also upload new ones or clone existing ones.
- Double-clicking a table opens the Popper Data dialog. You can edit the table's metadata there.
- Additionally, you can use the "auto-fill" function in the VP-Spreadsheet (VPS) section. When the table has a mapped VPS entry, the VPS data and the VPX files inner metadata is used to auto-fill the table data of Popper. Make sure you have enabled the flag in the UI preferences for this!

I hope this is what you looking for.
I wanted to make a "Getting Started" video about this, but did not find the time yet.

**Comment by syd711** [comment]
You will also find help on my Discord: https://discord.com/invite/69YqHYd3wD
I'm online quite often and do usually faster respond there.

**Comment by syd711** [comment]
Ups, seems the link expired, here is the new one: https://discord.gg/AMPwvAZHvy
I'll close this ticket for now. Don't hesitate to write if you miss something or got ideas for improvements.
